### PR TITLE
[skip ci] use uid instead of username, required for docker deployment

### PR DESCRIPTION
**Pull request by foosinn**
When deploying ceph in docker containers there is no user ceph on the host. Other tasks also use `ceph_uid` to work around this issue.

### CODE REVIEW

**Comment by foosinn** [comment]
Updated commit message and signed it. Can you check if everything correct?

**Comment by guits** [comment]
In any case we should use these facts here anyway.

**Comment by foosinn** [comment]
Updated to master branch.

**Comment by foosinn** [comment]
I'm not a 100% sure about that. I have migrated to a none Docker deployment, since i needed to use Ceph on LVM volumes. Cant check anymore

**Pull request closed without merging**
