### PR TITLE
Add support for containerized iscsi deployment

### PR DESCRIPTION
**Pull request by leseb**
Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
@guits the problem is that iscsi-gw won't show up in service map until a lun is mapped. Let me try something though.

**Comment by guits** [comment]
@leseb I was thinking of very basic tests like, for instance, checking the service is running with systemd

**Comment by leseb** [comment]
More info on this one, it seems that Kernel `3.10.0-823.el7` is required, which mean 7.5 (currently in beta). There is no image for vagrant for that yet... So there is no way for us to test this as we can not create gateways, see:

```
-bash-4.2# docker exec -ti rbd-target-api bash
[root@94fa81866ebd /]#
[root@94fa81866ebd /]# gwcli
/iscsi-target...-igw/gateways> create 94fa81866ebd 172.17.0.3
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
Failed : 94fa81866ebd failed package validation checks - OS is unsupported,Kernel version too old - 3.10.0-823.el7 or above needed
/iscsi-target...-igw/gateways>
```

For now, I guess we could only check (just like @guits said) if units are running. Although this is not ideal (if a failure occurs the check could run while the units appear to be running but will fail afterwards). Anyway, that's the only thing we can do for now.

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
This must wait for https://github.com/ceph/ceph-container/pull/985

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
Here it is https://app.vagrantup.com/centos/boxes/7/versions/1804.02

**Comment by leseb** [comment]
```
/iscsi-target...-igw/gateways> create 4028018738d1 172.17.0.4
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
ok
```

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Pull request merged**
