### PR TITLE
ceph_keys: pass in module for error messages

### PR DESCRIPTION
**Pull request by noahdesu**
fixes: #3421

it looks like this will need to be backported too, but I'm not sure how that process works. Are there docs for that?

### CODE REVIEW

**Comment by leseb** [comment]
@noahdesu for backports just assign the right label :)

**Comment by leseb** [comment]
@noahdesu we just need a BZ for the downstream backport.

**Comment by noahdesu** [comment]
donzo

**Comment by noahdesu** [comment]
seems like travis needs to be kicked off again, but that usually happens even with a force push. not sure what's up with that.

**Comment by noahdesu** [comment]
well, apparently i should just try refreshing the page.

**Pull request merged**
