### PR TITLE
update: various fixes

### PR DESCRIPTION
**Pull request by guits**
- remove a legacy task
- add a health check early
- only mask and stop unit in mgr sequence

### CODE REVIEW

**Comment by guits** [comment]
jenkins test dev-centos-non_container-update

**Comment by guits** [comment]
jenkins test dev-centos-non_container-update

**Comment by guits** [comment]
needs #4097 backported in stable-3.2 first

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test dev-centos-non_container-update

**Comment by guits** [comment]
jenkins test dev-centos-container-update

**Comment by guits** [comment]
jenkins test dev-centos-container-update

**Comment by guits** [comment]
jenkins test dev-centos-container-update

**Comment by dsavineau** [comment]
unrelated CI failure

**Pull request merged**
