### PR TITLE
Cephx false skip key permissions

### PR DESCRIPTION
**Pull request by stpierre**

### CODE REVIEW

**Comment by leseb** [comment]
Test this please

**Comment by stpierre** [comment]
I'm pretty new to ansible, and the `tests/` directory in ceph-ansible is pretty sparse so I don't have much to go from. Can you point me in the direction of some documentation that will get me started writing a test for this? Thanks!

**Comment by leseb** [comment]
test this please

**Comment by leseb** [comment]
@stpierre unfortunately the `tests/` directory was a first attempt to build functional tests. I've never really used them yet, so I'd say do not bother with that for now.

**Pull request merged**
