### PR TITLE
ceph-rgw-loadbalancer: Add keepalived non-distro install option

### PR DESCRIPTION
**Pull request by slam1987**
Currently keepalived installs the distro version which is 2 years behind.
Add feature which allows the user the option to specify the version number of keepalived to install.

Signed-off-by: Stanley Lam <stanleylam_604@hotmail.com>

### CODE REVIEW

**Comment by slam1987** [comment]
jenkins test centos-container-all_daemons

**Comment by slam1987** [comment]
jenkins test centos-container-lvm_osds

**Comment by nikosmeds** [comment]
jenkins test all

**Comment by dsavineau** [comment]
Please don't use this jenkins command

**Comment by nikosmeds** [comment]
TIL, sorry @dsavineau

**Comment by slam1987** [comment]
bump

**Pull request closed without merging**
