### PR TITLE
Sync config_template from upstream

### PR DESCRIPTION
**Pull request by cloudnull**
This change pulls in the most recent release of the config_template module
into the ceph_ansible action plugins.

Signed-off-by: Kevin Carter <kecarter@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
Would it be possible to have the exact same file than upstream ?
Currently there's an extra line at the end of the file causing the checksum to be different.
That's just a minor thing but let's keep the exact same file between projects.

**Comment by cloudnull** [comment]
Good catch @dsavineau updating that now and will resubmit.

**Comment by guits** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
unrelated CI failures

**Pull request merged**
