### PR TITLE
use host specific value for monitor_interface in ceph.conf creation

### PR DESCRIPTION
**Pull request by andrewschoen**
this fixes issue #1660

### CODE REVIEW

**Comment by GregMeno** [comment]
jenkins test this

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by guits** [comment]
jenkins test this please

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-purge_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_docker_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_docker_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_docker_cluster

**Pull request merged**
