### PR TITLE
tests: support update scenarios in test_rbd_mirror_is_up()

### PR DESCRIPTION
**Pull request by guits**
`test_rbd_mirror_is_up()` is failing on update scenarios because it
assumes the `ceph_stable_release` is still set to the value of the
original ceph release, it means it won't enter in the right part of the
condition and fails.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-update_docker_cluster

**Comment by guits** [comment]
luminous-ansible2.4-update_cluster

**Comment by leseb** [comment]
jenkins test pipeline

**Comment by guits** [comment]
luminous-update_cluster

**Comment by leseb** [comment]
jenkins test luminous-update_cluster

**Comment by guits** [comment]
jenkins test luminous-update_cluster

**Pull request merged**
