### PR TITLE
Use upstream config_template collection

### PR DESCRIPTION
**Pull request by noonedeadpunk**
In order to reduce need of module
internal maintenance and to join forces on plugin development,
it's proposed to switch to using upstream version of
config_template module.

As it's shipped as collection, it's installation for end-users
is trivial and aligns with general approach of shipping extra modules.

Signed-Off-By: Dmitriy Rabotyagov <noonedeadpunk@ya.ru>

### CODE REVIEW

**Comment by noonedeadpunk** [comment]
I also pulled latest commit made by ceph-ansible https://github.com/ceph/ceph-ansible/commit/a0bc5afe26b29c7d1dd9e3102d2c7cfcc6613d87 to the collection: https://review.opendev.org/c/openstack/ansible-config_template/+/824601

**Comment by guits** [comment]
need to be rebased

**Comment by noonedeadpunk** [comment]
Tests failed due to upstream packages issues... How to re-test all failing ones?:)

**Comment by noonedeadpunk** [comment]
jenkins test

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-all_daemons

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-update centos-non_container-switch_to_containers centos-non_container-subset_update

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-update
jenkins test centos-non_container-all_in_one

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-update

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-subset_update

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-purge

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-lvm_batch

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-external_clients

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-collocation

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-all_in_one

**Comment by noonedeadpunk** [comment]
jenkins test centos-non_container-all_daemons

**Review by guits — APPROVED** [review]

**Pull request merged**
