### PR TITLE
Inclusive language update

### PR DESCRIPTION
**Pull request by djgalloway**

### CODE REVIEW

**Comment by guits** [comment]
```
fatal: [osd2]: FAILED! => changed=false 
  connection: close
  content: |-
    504 Gateway Timeout
  
    The gateway has timed out.
  
     no repository is ready for: ceph/main
  content_length: '89'
  content_type: text/plain; charset=UTF-8
  date: Tue, 24 May 2022 20:11:25 GMT
  elapsed: 0
  msg: 'Status code was 504 and not [200]: HTTP Error 504: Gateway Timeout'
  redirected: false
  server: nginx
  status: 504
  url: https://shaman.ceph.com/api/repos/ceph/main/latest/centos/8/repo?arch=x86_64
  x_pecan_controller: list index out of range
  x_pecan_hooks: '[''TransactionHook'', ''RequestViewerHook'']'
  x_pecan_method: GET
  x_pecan_params: '[(''arch'', ''x86_64'')]'
  x_pecan_path: /api/repos/ceph/main/latest/centos/8/repo
  x_pecan_status: 504 Gateway Timeout

```

is shaman ready for that?

**Comment by zmc** [comment]
jenkins retest this please

**Comment by djgalloway** [comment]
jenkins retest this please

**Comment by zmc** [comment]
The query in @guits' comment works now

**Review by zmc — APPROVED** [review]

**Comment by djgalloway** [comment]
Built.  Retrying now.

**Comment by djgalloway** [comment]
I believe all the tests that are supposed to pass are passing now.

**Comment by guits** [comment]
jenkins test centos-container-lvm_batch

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-container-external_clients

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Comment by guits** [comment]
jenkins test centos-container-all_in_one

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Pull request merged**
