### PR TITLE
Remove MGR from stable-2.2

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
@GregMeno @andrewschoen @guits

**Comment by andrewschoen** [comment]
I think anything 'tests:' might need to stay. This for instance is very important for our downstream testing: https://github.com/ceph/ceph-ansible/pull/1559/commits/d7d515d084431e84cf0bf0d213c7e1e573f67fac

**Comment by ktdreyer** [comment]
What problem does this solve?

What is the risk of not taking this?

**Comment by leseb** [comment]
@andrewschoen the mgr issues we were discussion yesterday. See: https://jenkins.ceph.com/view/ceph-docker/job/ceph-docker-nightly-ceph_ansible2.2-jewel-centos7-cluster/6/consoleFull#-1961402874bf3c8a86-8876-45aa-9016-a5bacffc83b0

We decided to not push the ceph-mgr in this release as 2.2 does not include Luminous. ceph-mgr is only usable/relevant with Luminous.

**Comment by leseb** [comment]
@andrewschoen not sure what happened, I just rebased and removed 2 commits.

**Comment by leseb** [comment]
@andrewschoen "allow for insecure docker registries when testing rhcs" is still in stable-2.2 not sure to understand your issue.

**Comment by andrewschoen** [comment]
@leseb I guess I was just confused by this PR initially, I thought all those commits were being removed.

Taking a look at this branch though I see that the line that was failing from the jenkins log still exists though: https://github.com/ceph/ceph-ansible/blob/481316dfdf2f3a849bff3600482035e3e02946c4/roles/ceph-mon/tasks/docker/fetch_configs.yml#L16

At this point maybe it's just easier to backport this commit that fixes the line in question: https://github.com/ceph/ceph-ansible/commit/05331a26348e162e4083131d2a259f6c983f3ec9

**Comment by leseb** [comment]
@andrewschoen are you sure? I don't this line anymore, this line was introduced by 2aa528654 which has been removed from this branch.

**Comment by andrewschoen** [comment]
@leseb I think so anyway. I see that line in both ``rm-mgr`` and the current ``stable-2.2``.

https://github.com/ceph/ceph-ansible/blob/rm-mgr/roles/ceph-mon/tasks/docker/fetch_configs.yml#L16

and

https://github.com/ceph/ceph-ansible/blob/stable-2.2/roles/ceph-mon/tasks/docker/fetch_configs.yml#L16

The diff on this PR doesn't show the line being removed either. Am I missing something?

**Pull request closed without merging**
