### PR TITLE
Enable use of Custom ceph repository on SuSE/SLES

### PR DESCRIPTION
**Pull request by nitinkamble**
This commit allows using custom ceph repository with ceph-ansible deployments on Suse/SLES distributions.

Signed-off-by: Nitin Kamble <Nitin.Kamble@Teradata.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test dev-centos-container-lvm_auto_discovery

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_auto_discovery

**Comment by nitinkamble** [comment]
These changes backport to the current stable branch v3.2 cleanly.

**Comment by nitinkamble** [comment]
These changes backport to current stable v3.2 branch cleanly.

**Comment by guits** [comment]
@leseb why should we backport this into stable-3.2 ? Is there a BZ for this ?

**Comment by guits** [comment]
we only backport bugfixes into stable branches

**Pull request closed without merging**
