### PR TITLE
purge: add remove_docker tag

### PR DESCRIPTION
**Pull request by clwluvw**
This can help to skip docker removal tasks

Signed-off-by: Seena Fallah <seenafallah@gmail.com>

### CODE REVIEW

**Comment by clwluvw** [comment]
ping @dsavineau @guits

**Comment by clwluvw** [comment]
@guits Should it retest all failed stages?

**Review by guits — APPROVED** [review]

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Comment by guits** [comment]
failures are unrelated to this patch

**Pull request merged**
