### PR TITLE
Define readable vars for Ceph version comparisons

### PR DESCRIPTION
**Pull request by alfredodeza**
Fixes issue #736 

Adds vars all the way up to kraken

### CODE REVIEW

**Comment by alfredodeza** [comment]
@bengland2 I think you once mentioned these vars as being confusing. Can you also take a look and let me know your thoughts on the new vars?

**Comment by leseb** [comment]
@alfredodeza thanks for that, you need to set `include: facts.yml` after the package is installed.

**Comment by alfredodeza** [comment]
@leseb of course! so silly :( will fix

**Comment by alfredodeza** [comment]
@leseb re-pushed and now the tests are happy!

**Comment by leseb** [comment]
Thanks!

**Pull request merged**
