### PR TITLE
restart_osd_daemon.sh.j2 - consider scrubbing pgs as OK

### PR DESCRIPTION
**Pull request by mcv21**
After restarting each OSD, restart_osd_daemon.sh checks that the
cluster is in a good state before moving on to the next one. One of
the checks it does is that the number of pgs in the state
"active+clean" is equal to the total number of pgs in the cluster.

On large clusters (e.g. we have 173,696 pgs), it is likely that at
least one pg will be scrubbing and/or deep-scrubbing at any one
time. These pgs are in state "active+clean+scrubbing" or
"active+clean+scrubbing+deep", so the script was erroneously not
including them in the "good" count.

Fix this by summing the total of pgs in these 3 good states, and
comparing that to the num_pgs in pgmap; do this as an integer
comparison.

(could this be backported to at least stable-3.0 please?)

Closes: #2008
Signed-off-by: Matthew Vernon <mv3@sanger.ac.uk>

### CODE REVIEW

**Comment by mcv21** [comment]
As a quibble, I think `{1,}` is unconventional regex style, and `+` would be clearer - the `{1,}` were introduced in #2965 (previously they were `{1,2}`). Would you be open to my changing `{1,}` to `+`? If so, in this PR, or as a subsequent one?

**Comment by guits** [comment]
@mcv21 I think you can add a commit in this PR for that

**Comment by kcwong-verseon** [comment]
> As a quibble, I think `{1,}` is unconventional regex style, and `+` would be clearer - the `{1,}` were introduced in #2965 (previously they were `{1,2}`). Would you be open to my changing `{1,}` to `+`? If so, in this PR, or as a subsequent one?

I'm used to `+` from my Perl days as well, but believe it or not, it's not universally supported (I've encountered failure with some version of `sed`, and so `{1,}` actually has broader support. That said, we are already using the `grep -E` and `+` is in the alternate regex.

**Comment by mcv21** [comment]
Having looked at this further, there are other good states (e.g. active+clean+snaptrim); so instead modify the check to be "is there 'active+clean' in the state of this pg", since that catches all the good states.

**Pull request merged**
