### PR TITLE
[skip ci] shrink_osd: stop osd services before marking them out

### PR DESCRIPTION
**Pull request by wumingqiao**
I have tested many times to shrink more than one osds from a HEALTH_OK cluster. After the task is done, sometimes certain pgs will stuck in 'unknown' state, and only recover to active after I run 'ceph osd down xxx' to force them re-peering.

After I move 'stop osd services' in front of 'mark osds out', the issue never accur. I don't exactly know how it works.

Signed-off-by: wumingqiao <wumingqiao@beyondcent.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test dev-centos-non_container-shrink_osd

**Comment by guits** [comment]
jenkins test dev-centos-container-shrink_osd

**Comment by dsavineau** [comment]
not sure this is the right order

http://docs.ceph.com/docs/master/rados/operations/add-or-rm-osds/#removing-osds-manual

**Comment by guits** [comment]
@wumingqiao any update?

**Comment by guits** [comment]
closing this due to inactivity, feel free to reopen if needed

**Pull request closed without merging**
