### PR TITLE
remove kernel.pid_max

### PR DESCRIPTION
**Pull request by leseb**
This is now managed by Ceph packages.

See: https://github.com/ceph/ceph/pull/18544/files

http://tracker.ceph.com/issues/21929

Closes: https://github.com/ceph/ceph-ansible/issues/2410

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test v

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_container

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by guits** [comment]
the failure here is unrelated (new scenario added that needed to be fixed).

**Pull request merged**
