### PR TITLE
Support for libvirt provider in vagrant

### PR DESCRIPTION
**Pull request by lpabon**

### CODE REVIEW

**Comment by lpabon** [comment]
Tested using the following commands:

```
$ sudo vagrant up --no-provision --provider=libvirt
$ sudo vagrant provision
```

**Comment by rootfs** [comment]
please also update README.md

**Comment by leseb** [comment]
@lpabon Thanks the PR! I've been looking for something similar in order to setup a CI machine.
At the moment, I'm struggling with the following issue:

`undefined method `persistent?' for #<Libvirt::StoragePool:0x007f7778225758>`

Looking around Google gave me some hints but I'm still stuck, I know it's because of the patch, but just in case you have an idea ;). So I don't have anything to test that patch, if you tell me it works fine then I'm fine merging it :).

**Comment by lpabon** [comment]
@leseb Weird.  I wanted to make sure it worked, so I setup a clean Fedora 23 system and was able to setup ceph-ansible.  I have attached the output logs also.
[up.txt](https://github.com/ceph/ceph-ansible/files/51379/up.txt)
[provision.txt](https://github.com/ceph/ceph-ansible/files/51380/provision.txt)

**Comment by leseb** [comment]
@lpabon ok thanks for the logs, I'm good with that.

**Pull request merged**
