### PR TITLE
remove the gpgkey line from the red hat storage repo template

### PR DESCRIPTION
**Pull request by andrewschoen**
See: https://bugzilla.redhat.com/show_bug.cgi?id=1339439

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

Resolves: rhbz#1339439

### CODE REVIEW

**Comment by alfredodeza** [comment]
This looks OK to me

**Comment by ktdreyer** [comment]
LGTM (it would be good to test this)

**Comment by andrewschoen** [comment]
@ktdreyer I've tested this on rhel 7 with a beta signed ISO, everything installed fine after importing the beta key.

**Comment by ktdreyer** [comment]
awesome!

**Comment by ksingh7** [comment]
@andrewschoen @leseb  perfect and thanks

**Pull request merged**
