### PR TITLE
[skip ci] 2.4-3.0-backward-bkp

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by ktdreyer** [comment]
The commit log for this backport says:
```
(cherry picked from commit 302e563601cd6820b1ae44fabdfb1506688c7c9b)
```
But 302e563601cd6820b1ae44fabdfb1506688c7c9b is a dangling ref, not on master.

When we have "cherry picked from" lines that mention un-merged commits,  it makes it difficult to back-track to find the pull requests where the bugs were originally fixed in master. This makes it difficult to reverse-search Bugzilla too.

I can make my tool skip these cases of where my clone can't find the sha1, but then I could miss recording that we're fixing Bugzilla tickets.

Before merging pull requests, would you please ensure that the "cherry picked from" sha1s are correct?

**Comment by leseb** [comment]
@ktdreyer Not sure what happened here but we only do backports from merged commits, always.
302e563601cd6820b1ae44fabdfb1506688c7c9b was actually cherry-picked from another PR and this commit from that other PR was also fixing this PR so I decided to put it here.

**Comment by ktdreyer** [comment]
Thanks @leseb for explaining that 302e563 was cherry-picked from another PR. When I look at that commit in the GitHub UI, there's no indication of its original PR, and I'm guessing that's because it was later amended/rebased?

What do you think about not adding "cherry picked from" lines for master PRs? It makes it a lot simpler to comprehend the backport actions when we only use "cherry picked from" for backports.

**Comment by leseb** [comment]
Correct Ken, we took that commit out of that PR, so I agree the mention `cherry-picked from` is misleading.
Next time I do this I won't add `-x` on the cherry-pick command, it's just a habit from me.
Thanks for raising this.

**Comment by ktdreyer** [comment]
Thanks, I appreciate it!

**Pull request merged**
