### PR TITLE
ceph-facts: rm useless condition

### PR DESCRIPTION
**Pull request by leseb**
This condition is useless and it's also creating issues we don't see in
our CI. ceph_release is set by either ceph-common or ceph-docker-common
so let's keep it this way.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
Need rebase on https://github.com/ceph/ceph-ansible/pull/3056

**Comment by leseb** [comment]
Closing this due to inactivity, feel free to re-open, thanks!

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Pull request merged**
