### PR TITLE
DNM: osd: add a summary message of the osd deployment

### PR DESCRIPTION
**Pull request by leseb**
Closes: https://github.com/ceph/ceph-ansible/issues/1686
Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
Need a container version

**Comment by leseb** [comment]
jenkins test this please

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.2-bluestore_dmcrypt_journal_collocation

**Comment by guits** [comment]
jenkins test luminous-ansible2.2-docker_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.2-centos7_cluster

**Pull request closed without merging**
