### PR TITLE
Mon port

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
Seems that master is fixed, however we need to investigate that:

`ceph-mon : fetch ceph initial keys ----------------------------------- 2105.50s``

This task took 21min to complete.

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
`ceph.conf` example:

```
[root@ceph-mon0 ceph]# cat ceph.conf
# Please do not change this file directly since it is managed by Ansible and will be overwritten
[global]
cluster network = 192.168.2.0/24
fsid = e4553761-ef4a-4a4d-bf1e-fa3df421700a
mon host = [v1:192.168.1.10:6789,v2:192.168.1.10:3300],[v1:192.168.1.12:6789,v2:192.168.1.12:3300],[v1:192.168.1.11:6789,v2:192.168.1.11:3300]
mon initial members = ceph-mon0,ceph-mon1,ceph-mon2
osd_pool_default_size = 1
public network = 192.168.1.0/24
```

**Comment by guits** [comment]
jenkins test dev-update_cluster

**Comment by guits** [comment]
jenkins test dev-update_docker_cluster

**Comment by guits** [comment]
jenkins test dev-update_docker_cluster

**Comment by guits** [comment]
jenkins test dev-update_docker_cluster

**Comment by guits** [comment]
jenkins test dev-update_cluster

**Pull request merged**
