### PR TITLE
ci: test on ansible 2.4.2

### PR DESCRIPTION
**Pull request by leseb**
Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-xenial_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_container

**Comment by ktdreyer** [comment]
`git grep "2.4.1"` shows this version number is hard-coded in a couple more places

**Comment by leseb** [comment]
@ktdreyer thanks, update.

**Pull request merged**
