### PR TITLE
tests: run all tests for jewel and kraken

### PR DESCRIPTION
**Pull request by andrewschoen**
Signed-off-by: Andrew Schoen <aschoen@redhat.com>
(cherry picked from commit 1b6b6d6255fedddd6f44b932f0da5d2390920092)

Conflicts:
	tox.ini

backports #1410

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-update_dmcrypt

**Comment by andrewschoen** [comment]
jenkins test kraken-ansible2.2-update_cluster

**Comment by andrewschoen** [comment]
jenkins test kraken-ansible2.2-update_dmcrypt

**Comment by andrewschoen** [comment]
I expect the docker scenarios to fail, I don't think they've ever passed on the stable-2.1 branch.

**Comment by andrewschoen** [comment]
we're missing some scenarios, will need to backport more commits here

**Comment by leseb** [comment]
@andrewschoen bump

**Pull request closed without merging**
