### PR TITLE
add playbook to migrate systemd unit to podman

### PR DESCRIPTION
**Pull request by guits**
this commit adds a new playbook to force systemd units for containers to
use podman instead of docker.
This is needed in the rhel8 upgrade context so after the base OS is upgraded containers can be started using podman.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
wip

**Comment by dsavineau** [comment]
jenkins test dev-centos-container-podman

**Comment by dsavineau** [comment]
@guits found the issue. I think you removed a taks during the iscsi containerized/systemd refact.
There's a task to create the log directories which isn't present in this PR.

https://github.com/ceph/ceph-ansible/commit/91bef94b6c1ee159173a64cbca36385c67a186de#diff-8543c5196317a6a1ae0edd3392ba0f23R2

Without this task, the rbd-target-{api,gw} services don't start.

**Comment by dsavineau** [comment]
@guits I've rebased this PR to include the missing code

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Pull request merged**
