### PR TITLE
generate_group_vars_sample: merge role variables

### PR DESCRIPTION
**Pull request by leseb**
In some case, ceph_docker_registry does not match with a defined host
group in the playbook so we make this variable widely available.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1447179

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
I'm not sure that this is the correct path here. I don't like duplicating variables from ``ceph-docker-common`` into ``ceph-common`` just because ``generate_group_vars.sh``  can't put vars from both roles into ``group_vars/all.yml.sample``.

Moving forward we'll have to continue this duplication for every var we put into ``ceph-docker-common``.

**Comment by leseb** [comment]
@andrewschoen I'm not still not sure why we need to do that btw.
The meta declaration in the role should point to `docker-common.yml` once the role is started right?

**Comment by andrewschoen** [comment]
@leseb the meta declaration just includes the role, it does nothing with the group_vars. For ansible to use files defined in ``group_vars/`` the name of the file *must* match a host group. Like ``mons``, ``osds``, etc. There is no group ``docker-common`` so the variables defined there are never used, as proved by https://bugzilla.redhat.com/show_bug.cgi?id=1447179 and the ansible documentation.

**Comment by leseb** [comment]
@andrewschoen oh yes, thanks for the refresh :). I'll work on a different approach. Stay tuned.

**Comment by leseb** [comment]
jenkins test kraken-ansible2.2-centos7_cluster

**Comment by GregMeno** [comment]
@leseb so it seems like the intent here is to move the ceph_docker_registry in the all.yml.sample right?

**Comment by leseb** [comment]
@GregMeno correct

**Pull request merged**
