### PR TITLE
alertmanager: remove warning about untrusted certs

### PR DESCRIPTION
**Pull request by guits**
When using self-signed/untrusted CA certificates, alertmanager displays
an error in logs. With this commit this should make those messages
disappear.
    
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1936299

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
valid failure given the endpoint isn't yet ready because of this patch
```
    urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f65c97dc550>: Failed to establish a new connection: [Errno 111] Connection refused
```

**Comment by dsavineau** [comment]
closing in favor of https://github.com/ceph/ceph-ansible/pull/6748

**Pull request closed without merging**
