### PR TITLE
Update ceph_keys.yml

### PR DESCRIPTION
**Pull request by WingkaiHo**
jewel version need to build the {{ cluster }}.client.admin.keyring exists key

### CODE REVIEW

**Comment by leseb** [comment]
Jewel works well without this, what's the issue? Do you have any logs to share?

**Comment by WingkaiHo** [comment]
wait for {{ cluster }}.client.admin.keyring exists

timeout

**Comment by leseb** [comment]
Is the monitor started? The `ceph-create-keys` should be triggered by systemd, so we don't need to. Can I have a look at your systemd unit file for ceph-mon?

**Comment by WingkaiHo** [comment]
[Unit]
Description=Ceph cluster monitor daemon

# According to:
#   http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget
# these can be removed once ceph-mon will dynamically change network
# configuration.
After=network-online.target local-fs.target time-sync.target ceph-create-keys@%i.service
Wants=network-online.target local-fs.target time-sync.target ceph-create-keys@%i.service

PartOf=ceph-mon.target

[Service]
LimitNOFILE=1048576
LimitNPROC=1048576
EnvironmentFile=-/etc/sysconfig/ceph
Environment=CLUSTER=ceph
ExecStart=/usr/bin/ceph-mon -f --cluster ${CLUSTER} --id %i --setuser ceph --setgroup ceph
ExecReload=/bin/kill -HUP $MAINPID
PrivateDevices=yes
ProtectHome=true
ProtectSystem=full
PrivateTmp=true
TasksMax=infinity
Restart=on-failure
StartLimitInterval=30min
StartLimitBurst=3

[Install]
WantedBy=ceph-mon.target

**Comment by WingkaiHo** [comment]
ok thank

**Pull request closed without merging**
