### PR TITLE
flake8 library/igw_purge.py

### PR DESCRIPTION
**Pull request by hswong3i**
Split from #5711

Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

### CODE REVIEW

**Comment by guits** [comment]
@hswong3i thanks for these contributions, we appreciate that. However, you should have sent only 1 PR for this, there's no need to have 1 commit = 1 PR for this (it's wasting precious CI resources).
Even 1 commit for all modules would have been enough.

**Comment by hswong3i** [comment]
> @hswong3i thanks for these contributions, we appreciate that. However, you should have sent only 1 PR for this, there's no need to have 1 commit = 1 PR for this (it's wasting precious CI resources).
> Even 1 commit for all modules would have been enough.

I try everything in 1 PR before by suddenly all CI from green become failed. Don't know if it is related to other else commit or my changes, that's why I split it into multiple PRs...

May I confirm that master CI should be all passing now, right?

**Comment by guits** [comment]
@hswong3i you should close all these PRs and reopen the #5711

**Comment by guits** [comment]
closing in favor of #5739

**Pull request closed without merging**
