### PR TITLE
Osd dir exist and purge fixes

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test  ansible2.2-purge_cluster

**Comment by leseb** [comment]
jenkins test ansible2.2-purge_dmcrypt

**Comment by andrewschoen** [comment]
@leseb the ``ansible2.2-purge_cluster`` and ``ansible2.2-purge_dmcrypt`` testing scenarios won't work until https://github.com/ceph/ceph-ansible/pull/1250 is merged. 

Now that I think about it, we're not testing a purge with xenial, only centos7. I'll change ``ansible2.2-purge_cluster`` to use xenial instead.

**Comment by leseb** [comment]
jenkins test ansible2.2-purge_cluster

**Comment by leseb** [comment]
jenkins test ansible2.2-purge_cluster

**Comment by andrewschoen** [comment]
jenkins test ansible2.2-purge_cluster

**Comment by andrewschoen** [comment]
jenkins test ansible2.2-docker_cluster

**Pull request merged**
