### PR TITLE
[skip ci] tox: add cephadm_adopt scenario

### PR DESCRIPTION
**Pull request by dsavineau**
This adds an optional cephadm_adopt scenario which is based on
all_daemons.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
This needs https://github.com/ceph/ceph-build/pull/1609 first.

**Comment by guits** [comment]
jenkins test centos-container-cephadm_adopt

**Comment by dsavineau** [comment]
jenkins test centos-container-cephadm_adopt

**Comment by dsavineau** [comment]
jenkins test centos-container-cephadm_adopt

**Comment by dsavineau** [comment]
jenkins test centos-container-cephadm_adopt

**Pull request merged**
