### PR TITLE
Make install-ansible.sh work with Linux Mint and enable swap by default but decrease vm.swappiness

### PR DESCRIPTION
**Pull request by mcsage**
1. Just a small one to make it work with Linux Mint
2. I would like to see the swap enabled by default to guarantee a better resilience. Instead of turning swap completely of the way to go for better performance is to decrease vm.swappiness

### CODE REVIEW

**Comment by leseb** [comment]
Please execute the script to generate group vars files. It's at the root of the repos

**Comment by mcsage** [comment]
Thanks leseb. I'll close the pull request here. Feel free to add the Linux Mint thing.

Cheers

**Comment by leseb** [comment]
@mcsage why did you close this?

**Comment by leseb** [comment]
test this please

**Pull request merged**
