### PR TITLE
Discover osd_objectstore on the fly for container activation

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by ktdreyer** [comment]
What does "expose fi" mean?

**Comment by leseb** [comment]
Needs https://github.com/ceph/ceph-container/pull/1261

**Comment by guits** [comment]
lgtm
can we remove the [skip ci] ?

**Comment by leseb** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
jenkins test dev-lvm_osds_container

**Pull request merged**
