### PR TITLE
Ability to generate repos for localmirror

### PR DESCRIPTION
**Pull request by bdastur**

### CODE REVIEW

**Comment by leseb** [comment]
:-1: That's not the way to do it, this should be embedded within the playbook.

**Comment by bdastur** [comment]
@leseb : Thanks for your comment. Can you clarify more where it should be located. From our previous conversation in Issue #620, I understood that you did not want this as part of any roles in the ceph-ansible playbook. 

So I decided to move that logic as a separate play, part of the top level playbook.  Let me know if I misunderstood, I can make the appropriate change.

**Comment by leseb** [comment]
Hum in the end, let's keep this separated. Can you just integrate the variable using a var section in the `localrepo-site.yml.sample`? Thanks!

**Comment by bdastur** [comment]
2nd patchset, moved the repolist variable in the localrepo-site.yaml.sample.

**Comment by leseb** [comment]
Looks like there is still something on `group_vars/all.sample`, could you please fix this?

**Comment by bdastur** [comment]
k sure, let me know if it looks ok now.

**Comment by leseb** [comment]
Thanks!

**Comment by bdastur** [comment]
Thanks @leseb

**Pull request merged**
