### PR TITLE
rhcs: remove ISO install method

### PR DESCRIPTION
**Pull request by dsavineau**
Starting RHCS 5, there's no ISO available anymore.
This removes all ISO variables and the ceph_repository_type variable.

Closes: #6626

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
Thanks. This looks good.

I noticed one more thing to clean up: `infrastructure-playbooks/purge-cluster.yml` always deletes `/tmp/rh-storage-repo` (instead of `ceph_rhcs_repository_path` or `ceph_stable_rh_storage_repository_path`)

**Comment by dsavineau** [comment]
> Thanks. This looks good.
> 
> I noticed one more thing to clean up: `infrastructure-playbooks/purge-cluster.yml` always deletes `/tmp/rh-storage-repo` (instead of `ceph_rhcs_repository_path` or `ceph_stable_rh_storage_repository_path`)

Nice catch ! I'll update the PR

**Review by guits — DISMISSED** [review]

**Comment by guits** [comment]
jenkins test playbook syntax

**Review by ktdreyer — APPROVED** [review]

**Comment by dsavineau** [comment]
jenkins test centos-non_container-collocation

**Comment by dsavineau** [comment]
jenkins test playbook syntax

**Comment by guits** [comment]
`playbook syntax` doesn't exist anymore

**Review by guits — APPROVED** [review]

**Pull request merged**
