### PR TITLE
backport playbook execution time improvements on client nodes in stable-3.2

### PR DESCRIPTION
**Pull request by guits**
This PR is intended to backport playbook execution time improvements on client nodes in stable-3.2 branch

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1818708

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by dsavineau** [comment]
jenkins test playbook syntax

**Pull request merged**
