### PR TITLE
bump ansible testing version to 2.2.1 for the 2.2 environment

### PR DESCRIPTION
**Pull request by alfredodeza**
`2.2.1` is not released yet, but this will be what we should rely on once it gets out.

### CODE REVIEW

**Comment by alfredodeza** [comment]
Everything failing is expected since 2.2.1 is not out yet.

**Comment by leseb** [comment]
@alfredodeza so we should just wait for the release right?

**Comment by ktdreyer** [comment]
Depending on the gdeploy situation (https://github.com/gluster/gdeploy/issues/253), it might be nice to test with both 2.2.0.0 and 2.2.1.0, so we can evaluate the feasibility of keeping parity with what they're doing.

**Comment by alfredodeza** [comment]
@leseb yes, we should wait until the release is out.

@ktdreyer we can certainly add variants (we do have them available in `tox.ini` right now). But maybe we could set those to run daily (vs. for every pull request)

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by ktdreyer** [comment]
Marking for backport so we'll test stable-2.1 with this version of Ansible as well.

**Pull request merged**
