### PR TITLE
make group names definable

### PR DESCRIPTION
**Pull request by bjne**
Nice to be able to use different group-names than the defaults.

### CODE REVIEW

**Comment by leseb** [comment]
Can you add more detail in your commit message? Why is it useful?
Is the goal to get non-barcoded naming for the groups? So in your inventory file you can use something else than mons,mdss, etc...

**Comment by bjne** [comment]
Yes. This is useful because I have predefined groups, and they are in my
case, and perhaps many others, not osds and mons
and so on, but ceph_mon or whatever. When I symlink the roles into my
playbook, its very nice beeing able to hold upstream up
to date, and at the same time, not having to change everything to reflect
external dependencies.

2015-06-11 13:54 GMT+02:00 Leseb <notifications@github.com>:

> Can you add more detail in your commit message? Why is it useful?
> Is the goal to get non-barcoded naming for the groups? So in your
> inventory file you can use something else than mons,mdss, etc...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph-ansible/pull/280#issuecomment-111104208>.
>



-- 
Bj(/)rnar

**Comment by leseb** [comment]
Ok thanks!

**Comment by leseb** [comment]
@bjne can you please rebase your work? :)

**Comment by leseb** [comment]
@bjne did it myself. Thanks!

**Pull request merged**
