### PR TITLE
ceph-rgw: add cluster parameter to multisite tasks

### PR DESCRIPTION
**Pull request by dsavineau**
The rgw multisite tasks didn't use the cluster option so the
radosgw-admin commands would fail if the cluster name isn't the default
value.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
@alimaredia you should need to do the same on your current PR as well when this once will be merged

**Comment by dsavineau** [comment]
jenkins test dev-centos-non_container-rgw_multisite

**Comment by dsavineau** [comment]
jenkins test dev-centos-container-rgw_multisite

**Comment by guits** [comment]
> @alimaredia you should need to do the same on your current PR as well when this once will be merged

can't we make a single PR to fix this everywhere instead?

**Comment by dsavineau** [comment]
closing in flavor of #4688

**Pull request closed without merging**
