### PR TITLE
tests: set -e DEBUG=verbose on all docker testing scenarios

### PR DESCRIPTION
**Pull request by andrewschoen**
Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
@leseb how can we reduce the impact of debug logging so that `DEBUG=verbose` does not cause the containers to behave differently?

**Comment by andrewschoen** [comment]
@leseb I'm confused, enabling debug mode here changes the way the container operates? I was hoping it'd allow us to have more insight on why things fail on the PRs without having to modify the branch to enable debug and do a manual run of the test.

I ran this branch against the ``purge_docker_cluster`` test and got the following: https://jenkins.ceph.com/view/ceph-ansible/job/ceph-ansible-scenario/96/console

**Comment by leseb** [comment]
`verbose` activates `set -x` which enables tracing which introduces latency in the code execution. Thus this might hide potential raise conditions.

@andrewschoen I understand the intent and I agree this would be useful. With that I think we are getting back to the discussion about adding "jenkins test <scenario> debug", which ended with "boot yourself a slave and try to reproduce" :).

**Comment by ktdreyer** [comment]
Could we have Jenkins re-run with "-x" if the test fails?

**Comment by andrewschoen** [comment]
@ktdreyer not easily, as you can see from the diff it takes modifying config options in group_vars to include ``-e DEBUG=verbose`` when you deploy the container.

What @leseb is asking for is a way from a pr to say "jenkins debug $scenario" and then that slave that ran the test would stay around for manual debugging. This is non trivial because currently mita has no way to spin up a 'single-use' type of slave. There is also difficulty in knowing when a node that's used in this way should be cleaned up.

**Comment by leseb** [comment]
@andrewschoen can you have a condition in tox to add more options to `ceph_osd_docker_prepare_env` if a special flag is passed to the `jenkins test` line? And then add `-e DEBUG=verbose`?

**Pull request closed without merging**
