### PR TITLE
core: bump to ansible 2.15

### PR DESCRIPTION
**Pull request by guits**
2.12 is EOL since May 2023.

Let's bump to 2.15.

### CODE REVIEW

**Comment by berendt** [comment]
Wouldn't it make sense to go straight to 2.16?

**Comment by guits** [comment]
> Wouldn't it make sense to go straight to 2.16?

it might make sense, yes.

**Comment by berendt** [comment]
> > Wouldn't it make sense to go straight to 2.16?
> 
> it might make sense, yes. (keep in mind this is for stable-7.0)

Ah, I thought that was for the stable-8.0. For stable-7.0 I think Ansible 2.15 is fully sufficient. We have been using stable-7.0 with Ansible 2.14 for a long time without any problems.

**Comment by clwluvw** [comment]
jenkins test centos-container-all_daemons

**Pull request merged**
