### PR TITLE
Replace UTF-8 pseudo space character with real space

### PR DESCRIPTION
**Pull request by timmjd**
Lead to crash within [roles/ceph-config/tasks/main.yml](https://github.com/ceph/ceph-ansible/blob/stable-3.2/roles/ceph-config/tasks/main.yml#L77)
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 584, in _execute
    result = self._handler.run(task_vars=variables)
  File "/srv/workspace/srv/srv.ceph/ceph-ansible/plugins/actions/config_template.py", line 618, in run
    template_data = to_text(f.read())
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 6502: ordinal not in range(128)

fatal: [ip-xxx-xxx-xxx-xxx]: FAILED! => 
  msg: Unexpected failure during module execution.
  stdout: ''
```

Reason:
* Character is encoded as 0xc2a0 but should be 0x20

Environment:
* Ubuntu 18.04
* Ansible 2.6.14
* Python 3.6.7
* `ceph_origin: distro`

### CODE REVIEW

**Comment by dsavineau** [comment]
@timmjd could you update your commit message with the Signed-off-by line ?

**Comment by dsavineau** [comment]
@timmjd Could you also add more information about the configuration ?
- ceph version
- ansible version
- python version
- group_vars/*
etc...

I'm currently not able to reproduce the issue on py27 and py36 with ansible 2.6

**Comment by dsavineau** [comment]
@timmjd would you like to fix the NBSPs in the whole project instead of only the one leading to your issue ?

**Comment by timmjd** [comment]
@dsavineau here we go

**Comment by guits** [comment]
ideally this should have been made in master branch first, then backported to stable-3.2/3.1 but since there's too many changes between those branches I think it's fine to commit directly in each branches.

**Comment by guits** [comment]
closing this in favor of #3835 because of inactivity

**Pull request closed without merging**
