### PR TITLE
Update secondary.yml

### PR DESCRIPTION
**Pull request by OrFriedmann**
Create system user for the secondary site
#965

### CODE REVIEW

**Comment by leseb** [comment]
@OrFriedmann please add the issue number to close it once this gets merged :)
@jsaintrocc can you have a look at this?

**Comment by OrFriedmann** [comment]
There is another problem we should work out.
The Ceph clusters do not recognize the system user till a restart occurs in both sites.
I'll try to fix this

**Comment by jsaintrocc** [comment]
Hi @OrFriedmann,

Hum.  I've never had to manually create the zone.user on the secondary and I don't see that step in  http://docs.ceph.com/docs/jewel/radosgw/multisite/.  I'm wondering if this isn't just a bug in the latest dev release?  What version of Ceph are you seeing this on?

Thanks for your help, James

**Comment by OrFriedmann** [comment]
Right now, I have tested this on Jewel 10.2.2, Ubuntu 16.04.1.

I got an 403 error and after creating the user on the secondary site and restart the radosgw service everything went right.

**Comment by jsaintrocc** [comment]
OK.  I was testing on Jewel 10.2.2 as well.  I think the 403 would definitely be resolved by restarting the rgw but still not sure if creating the secondary user is necessary.  There is a handler that should restart the rgw automatically so I'll check that.  My test rig is down right now but I should have it up and running this weekend.  I'll want to see if the realm pull or period pull create the secondary user.

**Comment by jsaintrocc** [comment]
Ah.  One difference is that I'm testing on RHEL 7.2 instead of Ubuntu.  I wondering if the rgw restart handler isn't working properly for ubuntu 16.04.  I assumed that since everything is using Systemd now that it would work on both.

**Comment by OrFriedmann** [comment]
I checked it out.
ansible skips on the handler part in my environment.
After adding the same task from the handler(service restart) to the multisite/main.yml everything is working.
I didn't understand why ansible skips on the handler part.

**Comment by jsaintrocc** [comment]
Ah yes.  I've encountered that bug before.  Where Ansible 2 will just ignore handlers in some cases.  Are you running Ansible 2.1.0?  I think that's where the bug is.  I'm running 2.1.1 right now.

**Comment by OrFriedmann** [comment]
I ran the playbooks with ansible 2.0.0.2 and with ansible 2.1.1.
Both had a 403 error.
I saw that ansible does not skip on the handler.
Any idea?

**Comment by leseb** [comment]
Should we close this? @OrFriedmann @jsaintrocc

**Comment by jsaintrocc** [comment]
I'll try simulating the run using Vagrant and Ubuntu 16.04 today and see if I can reproduce the problem.

**Comment by leseb** [comment]
Thanks @jsaintrocc

**Comment by jsaintrocc** [comment]
Sorry it's taken me a while to get vagrant running with Ubuntu 16.04 and setting up dual clusters.  Should have this tested this weekend.

**Comment by OrFriedmann** [comment]
@jsaintrocc I can recommend on the box `bento/ubuntu-16.04`.

**Comment by jsaintrocc** [comment]
I tried the `bento/ubuntu-16.04` and I think that one had a 5 min wait for network that drove me a little nuts.  Either that or it was missing python.  I had much better luck with `geerlingguy/ubuntu1604` so I've submitted a PR to use that one.  @OrFriedmann sorry it's taking me so long to get to the bottom of this.  But now I have all the pieces together (Ubuntu 16.04 and a dual cluster vagrant setup).  It won't be much longer and thanks for your patience :-).

**Comment by Chrislevi** [comment]
@jsaintrocc the 5 min waiting is because your virtualbox version(probably 5.0...) I'm using 5.1 and I don't have any problem.

**Comment by jsaintrocc** [comment]
Quick status update @OrFriedmann @leseb:  I have a branch with several fixes for this but while testing an issue restarting on Trusty vs Xenial the Trusty repos have broken :-( #1034 .  Once they fix that I'll submit a PR that will hopefully clear this up.

**Comment by leseb** [comment]
@jsaintrocc thanks for the update!

**Comment by leseb** [comment]
@jsaintrocc any update on this one?

**Comment by maayankestler** [comment]
@jsaintrocc Can you send the PR that fixes the problem in Xenial , the bug you mention is a seperate problem
Thanks

**Comment by jsaintrocc** [comment]
?Sorry about the delay.  Just got back from vacation.  I'll check tomorrow and provide an update.

________________________________

**Comment by leseb** [comment]
Thanks @jsaintrocc

**Comment by jsaintrocc** [comment]
OK.  Managed to confirm that the repo for Trusty has been fixed so I'll proceed with testing the bug fixes for multisite.  Sorry for taking so long to get around to this.  There wasn't any movement on the bug so I didn't think they'd resolved the issue.

P.S. See that the latest master uses `check_mode: no` which is only supported in Ansible 2.2 :-(.  I'll submit a quick fix for that as well.

**Comment by leseb** [comment]
@jsaintrocc master and release 2.0 now aims to support ansible 2.2 only.
We still have an ansible-1.9 branch though which won't receive much attention, mainly bug fixes.
Is that an issue for you?

**Comment by leseb** [comment]
Inactive for a while, closing this, feel free to rebase and re-open :).

**Pull request closed without merging**
