### PR TITLE
Add ansible 2.9 support

### PR DESCRIPTION
**Pull request by dsavineau**
This commits add ansible 2.9 support in addition of 2.8.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
a change is the ansible firewalld module requires to change the ceph-infra role.

**Comment by dsavineau** [comment]
jenkins test centos-container-ooo_collocation

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-container-purge

**Comment by dsavineau** [comment]
jenkins test centos-container-update

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_auto_discovery

**Comment by dsavineau** [comment]
jenkins test centos-container-lvm_auto_discovery

**Comment by dsavineau** [comment]
jenkins test centos-non_container-rgw_multisite

**Comment by dsavineau** [comment]
jenkins test centos-container-rgw_multisite

**Comment by dsavineau** [comment]
jenkins test centos-non_container-shrink_mon

**Comment by dsavineau** [comment]
jenkins test centos-container-shrink_mon

**Comment by dsavineau** [comment]
jenkins test centos-non_container-shrink_osd

**Comment by dsavineau** [comment]
jenkins test centos-container-shrink_osd

**Comment by dsavineau** [comment]
jenkins test centos-non_container-filestore_to_bluestore

**Comment by dsavineau** [comment]
jenkins test centos-container-filestore_to_bluestore

**Comment by guits** [comment]
jenkins test centos-container-shrink_mon

**Comment by guits** [comment]
jenkins test centos-non_container-rgw_multisite

**Comment by guits** [comment]
jenkins test centos-container-rgw_multisite

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_auto_discovery

**Comment by dsavineau** [comment]
jenkins test centos-container-lvm_auto_discovery

**Comment by dsavineau** [comment]
jenkins test centos-non_container-rgw_multisite

**Comment by dsavineau** [comment]
jenkins test centos-container-rgw_multisite

**Pull request merged**
