### PR TITLE
tests/vagrant: update box version to CentOS 8.3

### PR DESCRIPTION
**Pull request by dsavineau**
This updates the CentOS libvirt box version to 8.3

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test centos-non_container-purge

**Comment by dsavineau** [comment]
jenkins test centos-non_container-purge

**Comment by dsavineau** [comment]
jenkins test centos-container-purge

**Comment by dsavineau** [comment]
jenkins test centos-non_container-update

**Comment by dsavineau** [comment]
jenkins test centos-non_container-purge

**Review by guits — DISMISSED** [review]

**Comment by dsavineau** [comment]
jenkins test centos-container-purge

**Comment by dsavineau** [comment]
jenkins test centos-non_container-purge

**Comment by dsavineau** [comment]
jenkins test centos-non_container-purge

**Comment by dsavineau** [comment]
jenkins test centos-container-purge

**Comment by dsavineau** [comment]
jenkins test centos-non_container-purge

**Comment by dsavineau** [comment]
jenkins test centos-container-purge

**Comment by dsavineau** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by dsavineau** [comment]
jenkins test centos-container-all_daemons

**Comment by dsavineau** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by dsavineau** [comment]
jenkins test centos-container-update

**Comment by dsavineau** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by dsavineau** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by dsavineau** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by dsavineau** [comment]
jenkins test centos-container-update

**Review by guits — APPROVED** [review]

**Pull request merged**
