### PR TITLE
Update start_docker_rgw.yml

### PR DESCRIPTION
**Pull request by VasishtaShastry**
Unit file to be generated in /etc/systemd/system/

### CODE REVIEW

**Comment by leseb** [comment]
Why not using the latest tag instead of merging this into this old/unmaintained tag?

**Comment by VasishtaShastry** [comment]
Sorry, missed it mistake
Really sorry for inconvenience
Shall I edit and select the appropriate base branch for this existing PR or shall I create new PR ?
Can you please suggest me ?

**Comment by leseb** [comment]
Well it depends on the bit you use from ceph-ansible. Do you run on the master branch? stable-2.1? Something else?

**Comment by leseb** [comment]
Closing this due to non-activity, feel free to re-open.

**Pull request closed without merging**
