### PR TITLE
copy certificates as root user

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Fixes: #3465

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
It worked for me but I lost the log; I'll attach it ASAP.

**Comment by rishabh-d-dave** [comment]
jenkins test container_podman

**Comment by rishabh-d-dave** [comment]
@leseb 
> use file module instead to change permissions

Done.

**Comment by leseb** [comment]
Ok, last thing, the right fix for this is to add `become: true` to https://github.com/ceph/ceph-ansible/pull/3466/files#diff-60c0915608d92d3192881947631900b3R66

**Pull request merged**
