### PR TITLE
Backport of 2424 in stable-3.0

### PR DESCRIPTION
**Pull request by leseb**
Backport of #2424 in stable-3.0

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Pull request merged**
