### PR TITLE
ceph-agent: install the correct package for the agent in Ubuntu

### PR DESCRIPTION
**Pull request by alfredodeza**
See: https://bugzilla.redhat.com/show_bug.cgi?id=1348130

### CODE REVIEW

**Comment by cdwertmann** [comment]
ceph-ansible now fails on my Ubuntu 14.04 hosts. Where can I get the ```rhscon-agent``` package for Ubuntu?

**Comment by leseb** [comment]
@cdwertmann are you installing the ceph-agent role?

**Comment by alfredodeza** [comment]
@cdwertmann why are you trying to install the agent? :) There is no public access to this package yet, and you probably don't need it for Ceph functionality.

**Comment by ktdreyer** [comment]
@cdwertmann I'm sorry there is no "rhscon-agent" package available publicly. There is an equivalent of an early Ubuntu Xenial package of the software, though, here: https://launchpad.net/~kdreyer-redhat/+archive/ubuntu/skynet . The big difference is that the package is named "skynet", not "rhscon-agent".

**Comment by cdwertmann** [comment]
Thank you for your replies. It seems that I don't need the storage agent to run ceph, so I'm skipping that role now.

**Pull request merged**
