### PR TITLE
Update ceph.conf.j2

### PR DESCRIPTION
**Pull request by marmot21**
This is just a simple change that will allow multiple gateways

### CODE REVIEW

**Comment by leseb** [comment]
AFAIR we don't support multi RGW yet, I still need to remember the reason why...

**Comment by marmot21** [comment]
If there's a reason why I'd love to know, this seemed to work in our situation

**Comment by leseb** [comment]
Ok maybe this is just me and without remembering I introduced a change to allow that :).
Do you also use HAproxy?

**Comment by marmot21** [comment]
No :)

**Comment by leseb** [comment]
Actually I had to reverse this since it breaks RGW startup.

**Comment by leseb** [comment]
However I reworked the multi-rgw, tested and validated. See #210

**Pull request merged**
