### PR TITLE
backport: added support for Sandisk FusionIO devices

### PR DESCRIPTION
**Pull request by guits**
Signed-off-by: Pascal Watteel <pascal.watteel@emc.com>
(cherry picked from commit e4ef8bb87f9df22459908f71d8cc816b081d829a)
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
backport of #1527

**Comment by leseb** [comment]
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1451811

**Comment by guits** [comment]
jenkins test this please

**Comment by leseb** [comment]
kraken-ansible2.2-update_cluster fix here: https://github.com/ceph/ceph-ansible/pull/1492 with backport here: https://github.com/ceph/ceph-ansible/pull/1550

will rebase on stable-2.2 once https://github.com/ceph/ceph-ansible/pull/1550 passes.

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-purge_dmcrypt

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-docker_dedicated_journal

**Pull request merged**
