### PR TITLE
ceph_key: remove 'update' state (backport of PR #5157)

### PR DESCRIPTION
**Pull request by guits**
With this change, the state `present` is enough to update a keyring.
If the keyring already exist, it will be updated if caps or secret
passed to the module are different.
If the keyring doen't exist, it will be created.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1808367

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>
(cherry picked from commit 553584cbd0d014429e665f998776e8d198f72d2b)

### CODE REVIEW

**Comment by guits** [comment]
jenkins test playbook syntax

**Comment by guits** [comment]
jenkins test centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test playbook syntax

**Comment by guits** [comment]
jenkins test playbook syntax

**Comment by guits** [comment]
jenkins test centos-container-all_in_one

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by dsavineau** [comment]
jenkins test centos-container-collocation

**Comment by dsavineau** [comment]
jenkins test centos-container-all_in_one

**Comment by guits** [comment]
jenkins test playbook syntax

**Comment by guits** [comment]
jenkins test playbook syntax

**Comment by guits** [comment]
jenkins test playbook syntax

**Comment by guits** [comment]
jenkins test playbook syntax

**Pull request merged**
