### PR TITLE
name includes and set_fact for clarity

### PR DESCRIPTION
**Pull request by leseb**
When Ansible is not run with verbose options it's difficult to see which
include and/or set_fact does what. So adding a name for each clarifies.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-update_cluster

**Comment by leseb** [comment]
jenkins test  luminous-ansible2.3-update_docker_cluste

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-update_docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Pull request merged**
