### PR TITLE
Revert "nfs-ganesha support removal"

### PR DESCRIPTION
**Pull request by guits**
This reverts commit 675667e1d60b7080dad7293f2954de23718c5042.

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by noonedeadpunk** [comment]
Huh, so test failures seem somehow unrelated to the patch itself, as there's some weird connection issue to the spawned containers.

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-container-lvm_batch

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_batch

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_batch

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-container-subset_update

**Comment by guits** [comment]
jenkins test centos-container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Comment by guits** [comment]
jenkins test centos-container-all_in_one

**Comment by guits** [comment]
jenkins test centos-container-external_clients

**Comment by guits** [comment]
jenkins test centos-non_container-subset_update

**Comment by guits** [comment]
jenkins test centos-non_container-rbdmirror

**Comment by guits** [comment]
jenkins test centos-non_container-external_clients

**Comment by guits** [comment]
jenkins test centos-non_container-collocation

**Comment by guits** [comment]
jenkins test centos-non_container-all_in_one

**Comment by guits** [comment]
jenkins test centos-container-rbdmirror

**Pull request merged**
