### PR TITLE
fix fragment for osd directory scenario

### PR DESCRIPTION
**Pull request by leseb**
Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by snerdish** [comment]
2016-03-09 21:11:28,285 p=1060423 u=robk |  TASK: [ceph-osd | create a ceph fragment and assemble directory] **************
2016-03-09 21:11:28,321 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux] => (item=/etc/ceph/ceph.d/)
2016-03-09 21:11:28,323 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux] => (item=/etc/ceph/ceph.d/)
2016-03-09 21:11:28,324 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux] => (item=/etc/ceph/ceph.d/osd_fragments)
2016-03-09 21:11:28,324 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux] => (item=/etc/ceph/ceph.d/)
2016-03-09 21:11:28,325 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux] => (item=/etc/ceph/ceph.d/)
2016-03-09 21:11:28,326 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux] => (item=/etc/ceph/ceph.d/osd_fragments)
2016-03-09 21:11:28,328 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux] => (item=/etc/ceph/ceph.d/osd_fragments)
2016-03-09 21:11:28,329 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux] => (item=/etc/ceph/ceph.d/osd_fragments)
2016-03-09 21:11:28,341 p=1060423 u=robk |  TASK: [ceph-osd | create the osd fragment] ************************************
2016-03-09 21:11:28,381 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux] => (item=combined_osd_id.results)
2016-03-09 21:11:28,382 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux] => (item=combined_osd_id.results)
2016-03-09 21:11:28,382 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux] => (item=combined_osd_id.results)
2016-03-09 21:11:28,383 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux] => (item=combined_osd_id.results)
2016-03-09 21:11:28,398 p=1060423 u=robk |  TASK: [ceph-osd | copy ceph.conf for assembling] ******************************
2016-03-09 21:11:28,434 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux]
2016-03-09 21:11:28,438 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux]
2016-03-09 21:11:28,439 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux]
2016-03-09 21:11:28,439 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux]
2016-03-09 21:11:28,453 p=1060423 u=robk |  TASK: [ceph-osd | assemble osd sections] **************************************
2016-03-09 21:11:28,490 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux]
2016-03-09 21:11:28,491 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux]
2016-03-09 21:11:28,493 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux]
2016-03-09 21:11:28,494 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux]
2016-03-09 21:11:28,506 p=1060423 u=robk |  TASK: [ceph-osd | assemble ceph conf and osd fragments] ***********************
2016-03-09 21:11:28,545 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux]
2016-03-09 21:11:28,546 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux]
2016-03-09 21:11:28,546 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux]
2016-03-09 21:11:28,547 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux]
2016-03-09 21:11:28,561 p=1060423 u=robk |  TASK: [ceph-osd | start and add that the osd service(s) to the init sequence (before infernalis)] ***
2016-03-09 21:11:28,598 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux]
2016-03-09 21:11:28,599 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux]
2016-03-09 21:11:28,602 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux]
2016-03-09 21:11:28,602 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux]
2016-03-09 21:11:28,616 p=1060423 u=robk |  TASK: [ceph-osd | get osd id (for or after infernalis)] ***********************
2016-03-09 21:11:28,652 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux]
2016-03-09 21:11:28,656 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux]
2016-03-09 21:11:28,657 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux]
2016-03-09 21:11:28,658 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux]
2016-03-09 21:11:28,670 p=1060423 u=robk |  TASK: [ceph-osd | enable osd service instance(s) (for or after infernalis)] ***
2016-03-09 21:11:28,713 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux] => (item=osd_id.stdout_lines)
2016-03-09 21:11:28,713 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux] => (item=osd_id.stdout_lines)
2016-03-09 21:11:28,714 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux] => (item=osd_id.stdout_lines)
2016-03-09 21:11:28,715 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux] => (item=osd_id.stdout_lines)
2016-03-09 21:11:28,729 p=1060423 u=robk |  TASK: [ceph-osd | start and add that the osd service(s) to the init sequence (for or after infernalis)] ***
2016-03-09 21:11:28,770 p=1060423 u=robk |  skipping: [storage01.bork.foo01.qux] => (item=osd_id.stdout_lines)
2016-03-09 21:11:28,771 p=1060423 u=robk |  skipping: [storage02.bork.foo01.qux] => (item=osd_id.stdout_lines)
2016-03-09 21:11:28,771 p=1060423 u=robk |  skipping: [storage01.bork.bar01.qux] => (item=osd_id.stdout_lines)
2016-03-09 21:11:28,772 p=1060423 u=robk |  skipping: [storage02.bork.bar01.qux] => (item=osd_id.stdout_lines)

**Comment by snerdish** [comment]
[osds]
storage01.bork.foo01.qux ceph_crush_root=iix ceph_crush_rack=01
storage02.bork.foo01.qux ceph_crush_root=iix ceph_crush_rack=01
storage01.bork.bar01.qux ceph_crush_root=iix ceph_crush_rack=02
storage02.bork.bar01.qux ceph_crush_root=iix ceph_crush_rack=02

**Comment by leseb** [comment]
Not sure either, so this patch makes it skipping the task?

**Comment by snerdish** [comment]
>
> Not sure either, so this patch makes it skipping the task?
>
>
> It's like  'when: osd_directory' is being ignored. Due to Real Life I
haven't had a chance to look at this over the weekend.

**Pull request merged**
