### PR TITLE
dashboard: enable https by default

### PR DESCRIPTION
**Pull request by guits**
see linked bz for details

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1889426

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Review by dsavineau — CHANGES_REQUESTED** [review]
I think we should change `dashboard_grafana_api_no_ssl_verify` depending on the `grafana_crt` and `grafana_key` values.

If those variables are empty then we need to set `dashboard_grafana_api_no_ssl_verify` to true (self signed TLS certificate)

**Comment by guits** [comment]
jenkins test centos-container-lvm_batch

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Comment by dsavineau** [comment]
jenkins test centos-non_container-purge

**Review by dsavineau — APPROVED** [review]

**Pull request merged**
