### PR TITLE
purge: remove leftover unit files

### PR DESCRIPTION
**Pull request by leseb**
Closes https://github.com/ceph/ceph-ansible/issues/1672

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-xenial_cluster

**Comment by ktdreyer** [comment]
Why the `-r` here? "rm -rf" is dangerous

**Comment by ktdreyer** [comment]
Why the `-r` here? "rm -rf" is dangerous

**Comment by leseb** [comment]
@ktdreyer `-r` because these are directories.

**Pull request merged**
