### PR TITLE
WIP - remove static references from roles

### PR DESCRIPTION
**Pull request by tynorth-cisco**
Adding static will cause roles to be run ( and skipped ) on
every run even when a seperate tag is specified.

For example, if you ran a playbook which uses these roles,
and specify "--tags foo", these ceph roles will still be run
and skipped, even though they are not part of the role.

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test this please

**Comment by tynorth-cisco** [comment]
@andrewschoen is there a keyword I can use to start off another run?

**Comment by andrewschoen** [comment]
@tynorth-cisco You can use ``jenkins test this please`` to rerun all tests, or ``jenkins test $scenario_name``, e.g. ``jenkins test ansible2.2-xenial_cluster``

**Comment by tynorth-cisco** [comment]
@andrewschoen failures might be unrelated but I'm not sure

```
usage: ceph-disk prepare [-h] [--cluster NAME] [--cluster-uuid UUID]
                         [--osd-uuid UUID] [--dmcrypt]
                         [--dmcrypt-key-dir KEYDIR] [--fs-type FS_TYPE]
                         [--zap-disk] [--data-dir] [--data-dev]
                         [--lockbox LOCKBOX] [--lockbox-uuid UUID]
                         [--journal-uuid UUID] [--journal-file]
                         [--journal-dev] [--bluestore] [--block-uuid UUID]
                         [--block-file] [--block-dev]
                         DATA [JOURNAL] [BLOCK]
ceph-disk prepare: error: too few arguments
```

**Comment by leseb** [comment]
@tynorth-cisco looks like removing this doesn't honor the `when` conditional anymore.

**Comment by tynorth-cisco** [comment]
@leseb I'm curious, what ansible version is used in the testing? I've noticed some very different behavior between 1.9.x and 2.x

**Comment by leseb** [comment]
@tynorth-cisco we use ansible 2.2.1 in the CI.

**Comment by tynorth-cisco** [comment]
jenkins test ansible2.2-xenial_cluste

**Comment by tynorth-cisco** [comment]
jenkins test ansible2.2-xenial_cluster

**Comment by tynorth-cisco** [comment]
jenkins test ansible2.2-xenial_cluster

**Comment by leseb** [comment]
jenkins test ansible2.2-docker_cluster

**Pull request closed without merging**
