### PR TITLE
tox: Refact lvm-osds scenario

### PR DESCRIPTION
**Pull request by dsavineau**
The current lvm_osds only tests filestore on one OSD node.
We also have bs_lvm_osds to test bluestore and encryption.
Let's use only one scenario to test filestore/bluestore and with or
without dmcrypt on four OSD nodes.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
@guits this requires https://github.com/ceph/ceph-build/pull/1276 first

**Comment by guits** [comment]
@dsavineau please rebase maggle!

**Comment by dsavineau** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by dsavineau** [comment]
jenkins test dev-centos-container-lvm_osds

**Comment by dsavineau** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by dsavineau** [comment]
jenkins test dev-centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Pull request merged**
