### PR TITLE
Add network Openstack

### PR DESCRIPTION
**Pull request by FranBarrera**
Solve this error: "Multiple possible networks found, use a Network ID to be more specific."

Signed-off-by: FranBarrera <franbarrera6@gmail.com>

### CODE REVIEW

**Comment by leseb** [comment]
Is it fixing this? https://github.com/ceph/ceph-ansible/issues/952

**Comment by FranBarrera** [comment]
I'm not sure, my problem was in Openstack because I don't know what net is used for default and give me the error, maybe fix #952

**Comment by leseb** [comment]
Oh yeah right, error from me. Can you also update `vagrant_variables.yml.sample`

**Comment by FranBarrera** [comment]
Done

**Comment by leseb** [comment]
Arf sorry forget about what I said, you're only touching the openstack section so we don't need to update `vagrant_variables.yml.sample`... can you rollback?

**Comment by FranBarrera** [comment]
Yes, you're right, now is rollback

**Pull request merged**
