### PR TITLE
mgr: admin keyring is not getting copied

### PR DESCRIPTION
**Pull request by vishalkanaujia**
The ceph-mgr role does not copy client admin keyring to a mgr node.

### CODE REVIEW

**Comment by leseb** [comment]
The admin key should not be copied over. The mon creates the mgr key and then publishes it to all the mgr nodes.

**Comment by leseb** [comment]
Also rebase your work on master.

**Comment by guits** [comment]
@vishalkanaujia taking @leseb's comment in consideration, I'm not sure to understand the puropose of this PR. Is there any issue/BZ related to this patch ? Can you provide more information on what has driven you to submit this PR ?

**Comment by leseb** [comment]
Closing this due to inactivity, feel free to re-open if you have any more concerns.

**Pull request closed without merging**
