### PR TITLE
ignore error when key is not exist

### PR DESCRIPTION
**Pull request by yanyixing**
ignore error when key is not exist

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-docker_cluster

**Comment by leseb** [comment]
jenkins test  jewel-ansible2.2-purge_dmcrypt

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-purge_dmcrypt

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-docker_dmcrypt_journal_collocation

**Comment by yanyixing** [comment]
@leseb will be merged?

**Pull request merged**
