### PR TITLE
backport of 2054

### PR DESCRIPTION
**Pull request by leseb**
Backport of #2054

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by leseb** [comment]
osp12 backport

**Comment by leseb** [comment]
Needs to be discussed as this is a feature backport.

**Comment by tombarron** [comment]
Just observing that we need this for OSP 13: I see a comment 'osp12 backport' which is why I mention this.

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by leseb** [comment]
This won't make it in 3.0 as a backport but 3.1 milestone just as planned.

**Pull request closed without merging**
