### PR TITLE
adds the ability to set osd_crush_chooseleaf_type

### PR DESCRIPTION
**Pull request by andrewschoen**
Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
We don't need extra parameters anymore. We can use the override variable from group_vars/all and set an extra option. 
It's a bit tricky as some options are interesting to share with users. So not sure how to deal with those PRs....

Any idea?

**Comment by andrewschoen** [comment]
@leseb In my case I wasn't aware that the override variable existed. Maybe we can just promote it's usage more with some documentation? I'm unsure if ceph-ansible is where people should look to learn how to tweak ceph though, thoughts?

I do think that the override variable makes more sense than providing a 1 to 1 mapping of ansible vars in ceph-ansible to config options in ceph. I can see how that could get difficult to maintain over time.

**Comment by leseb** [comment]
Yes, highlighting this in the documentation is probably the best we can do. We should also say that we do not accept anymore pull requests on the template file unless this is helping the deployment, #553 was a good exception for example.
Would you mind doing a bit of docs? :)

Thanks @andrewschoen

**Comment by andrewschoen** [comment]
@leseb yeah, I can write those docs. I'll close this and make a new PR for that.

**Comment by leseb** [comment]
Great thanks!

**Pull request closed without merging**
