### PR TITLE
delegate key creation to first mon

### PR DESCRIPTION
**Pull request by batrick**
Otherwise keys get scattered over the mons.

Also, create all keys on the first mon and copy those to the other mons to be
consistent.

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
@leseb I can't recall the exact error and unfortunately I didn't save it for the commit message. It had something to do with the mgr failing to start because it didn't have keys IIRC.

I'll see if I can reproduce the problem again.

**Comment by batrick** [comment]
@leseb, I don't know if it's a problem but it seems unnecessary? Anyway, I just re-verified the fix resolves the issue and included the failure in the commit message. Please check.

**Comment by guits** [comment]
@batrick could you rebase on master please

**Comment by batrick** [comment]
@guits done

**Pull request merged**
