### PR TITLE
support rolling_upgrade from Jewel to Luminous

### PR DESCRIPTION
**Pull request by pakal98**
Hello,

proposed "master.yml" for multisite RGW tasks working with "rolling_upgrades.yml" playbook and new deployments.

When using a rolling_upgrade on an existing multisite RGW cluster, master.yml gives an error:

TASK [ceph-rgw : include master multisite tasks] ****************************************************************************************************************
fatal: [rgwnode]: FAILED! => {"reason": "Syntax Error while loading YAML.\n\n\nThe error appears to have been in '/home/ansible/ceph-object/ansible-obj/roles/ceph-rgw/tasks/multisite/master.yml': line 6, column 35, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  when:\n    - 'No such file or directory' in realmcheck.stderr\n                                  ^ here\n\nexception type: <class 'yaml.parser.ParserError'>\nexception: while parsing a block collection\n  in \"<unicode string>\", line 6, column 5\ndid not find expected '-' indicator\n  in \"<unicode string>\", line 6, column 35"}

### CODE REVIEW

**Comment by leseb** [comment]
@pakal98 Please add a sign-off to your commit message.

**Comment by leseb** [comment]
Also I'm not sure why is Ansible complaining here... You basically re-wrote the same thing but it passes that what maters I guess.

**Comment by pakal98** [comment]
Hello,

TASK [ceph-rgw : include master multisite tasks] ***********************************************************************************************************************
fatal: [host01]: FAILED! => {"reason": "Syntax Error while loading YAML.\n\n\nThe error appears to have been in '/home/ansible/ceph-object/ansible-obj/roles/ceph-rgw/tasks/multisite/master.yml': line 6, column 35, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  when:\n    - 'No such file or directory' in realmcheck.stderr\n                                  ^ here\n\nexception type: <class 'yaml.parser.ParserError'>\nexception: while parsing a block collection\n  in \"<unicode string>\", line 6, column 5\ndid not find expected '-' indicator\n  in \"<unicode string>\", line 6, column 35"}
        to retry, use: --limit @/home/ansible/ceph-object/ansible-obj/.ansible-retry/site.retry

When change is applyied 

TASK [ceph-rgw : include master multisite tasks] ***********************************************************************************************************************
included: /home/ansible/ceph-object/ansible-obj/roles/ceph-rgw/tasks/multisite/master.yml for host01

And period request answers correctly :

# radosgw-admin period get
{
    "id": "f903a27a-218e-4aa4-aaed-eedadbc5c10c",
    "epoch": 1,
    "predecessor_uuid": "d99633cb-bc14-43ba-be7d-9582eba8a3bb",
    "sync_status": [],
    "period_map": {
        "id": "f903a27a-218e-4aa4-aaed-eedadbc5c10c",
        "zonegroups": [
            {
                "id": "cf0d1888-9302-4fc3-a892-dbee87a8814f",
                ......
                ......

It is strange because Ansible usage for conditional shows no diference between both syntax.

https://docs.ansible.com/ansible/2.5/user_guide/playbooks_conditionals.html

**Comment by guits** [comment]
@pakal98 i can't reproduce your failure, that's weird.

**Comment by pakal98** [comment]
@Guits : I suspect that a parameter combination in groups_vars and inventory/hosts is giving such an error. I was wondering why an equivalent Ansible syntax could lead to different results. 

On travel today with bad connection. Sharing details tomorrow. I appreciate in advance your feedback in order to reproduce the error and find the bug.

**Pull request closed without merging**
