### PR TITLE
rgw/multisite: assign 'rgw_zone' to the exact section in ceph.conf

### PR DESCRIPTION
**Pull request by guihecheng**
since the following commit:
  commit 1ac94c048ff1d1385de2892d0ecef7879ec563e9
  rgw: add support for multiple rgw instances on a single host

we have multi-instance rgw support on a single host and
the config section name of the rgw changed from
[client.rgw.$(hostname)] -> [client.rgw.$(hostname).rgwX]
when X is the sequence number: 0,1,2,...
So we should assign 'rgw_zone' item to the exact rgw instance
config section in ceph.conf

Signed-off-by: guihecheng <guihecheng@cmiot.chinamobile.com>

### CODE REVIEW

**Comment by guihecheng** [comment]
Well, there's no error indications for the failure, any ideas? @leseb @guits

**Comment by guits** [comment]
@guihecheng it's totally unrelated to your patch, I'm working on fixing this error atm

**Comment by guihecheng** [comment]
@leseb @guits any further plans on this one ?

**Comment by dsavineau** [comment]
@guihecheng sorry for the delay. Could you rebase your PR and resolve the conflict ?
Thanks !

**Comment by guihecheng** [comment]
@dsavineau thanks for your reminding, I've rebased this just now.

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
unrelated failure

**Pull request merged**
