### PR TITLE
backport: DNM: tox: add ansible2.3

### PR DESCRIPTION
**Pull request by ktdreyer**
Not sure if this is the right way to add this... But I really want us to be testing on both ansible2.2 and ansible2.3.

### CODE REVIEW

**Comment by ktdreyer** [comment]
I think this means I need to add Jenkins jobs for ansible2.3 as well? (And they'll fail on stable-2.2 until I've backported this?)

**Comment by andrewschoen** [comment]
> I think this means I need to add Jenkins jobs for ansible2.3 as well? (And they'll fail on stable-2.2 until I've backported this?)

Yeah, you'll need to update https://github.com/ceph/ceph-build/blob/master/ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml#L6. Perhaps it's time to add an ``ansible_version`` factor in that JJB so we can add ``ansible2.2`` and ``ansible2.3`` easily.

**Comment by ktdreyer** [comment]
Thanks. I will merge+backport this PR before making the ceph-build.git change.

**Comment by guits** [comment]
jenkins test kraken-ansible2.2-xenial_cluster

**Comment by leseb** [comment]
@ktdreyer status of this PR?

**Comment by ktdreyer** [comment]
This is uneeded now

**Pull request closed without merging**
