### PR TITLE
Execute a script to pull the roles

### PR DESCRIPTION
**Pull request by leseb**
WIP
Closes: #388

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
Need to modify the script to not pull if directories exists already.

**Comment by HanXHX** [comment]
Hi @leseb 

Can you merge please?

Emilien

**Comment by leseb** [comment]
Hey @HanXHX, the thing is this breaks several things and still need to figure out a proper way to not break everything :)

**Comment by leseb** [comment]
Closing this in favour of another PR

**Pull request closed without merging**
