### PR TITLE
[skip ci] library: add cephadm_adopt module

### PR DESCRIPTION
**Pull request by dsavineau**
This adds cephadm_adopt ansible module for replacing the command module
usage with the cephadm adopt command.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test ceph-container-cephadm_adopt

**Comment by dsavineau** [comment]
jenkins test centos-container-cephadm_adopt

**Comment by dsavineau** [comment]
jenkins test centos-container-cephadm_adopt

**Comment by dsavineau** [comment]
jenkins test centos-container-cephadm_adopt

**Review by guits — APPROVED** [review]

**Pull request merged**
