### PR TITLE
test adding a RGW to already deployed cluster

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Add a tox scenario that adds a new RGW node as a part of already
deployed Ceph cluster and deploys RGW there.

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
@guits
Should I go ahead and add "Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1677431" to the commit message? BZ #1677431 requests scale-up/down playbooks for MGR, RGW and RBD-Mirror which is too broad for a single PR.

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-add_rgws

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-add_mdss

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-add_rgws

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-add_rgws

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-add_rgws

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-add_rgws

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-add_rgws

**Comment by rishabh-d-dave** [comment]
jenkins test pipeline

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test dev-centos-non_container-add_rgws

**Comment by guits** [comment]
jenkins test dev-centos-container-add_rgws

**Pull request merged**
