### PR TITLE
use when_failed to make stop of non-existent service ok

### PR DESCRIPTION
**Pull request by bengland2**
This patch makes purge-cluster.yml service shutdowns idempotent.   Thus it possible to run purge-cluster.yml if ceph-ansible site.yml has not yet run or has run but only partially completed.  We use failed_when: false in systemd and sysvinit shutdown tasks - this was already being done for Ubuntu pre-systemd releases.

### CODE REVIEW

**Comment by leseb** [comment]
AFAIK the service is idempotent already, so using `failed_when` does not change anything. See:

```
[stack@leseb-tarox ~]$ cat failed_when.yml
---
- hosts: localhost
  connection: local

  tasks:

    - name: stop ceph mdss with systemd
      service:
        name: ceph-mds@{{ ansible_hostname }}
        state: stopped
        enabled: no
      failed_when: false
[stack@leseb-tarox ~]$ ansible --version
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Aug  9 2016, 15:48:18) [GCC 6.1.1 20160621 (Red Hat 6.1.1-3)]
[stack@leseb-tarox ~]$ sudo systemctl status ceph-mds@leseb-tarox
● ceph-mds@leseb-tarox.service - Ceph metadata server daemon
   Loaded: loaded (/usr/lib/systemd/system/ceph-mds@.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[stack@leseb-tarox ~]$ vim failed_when.yml
[stack@leseb-tarox ~]$ ansible-playbook failed_when.yml
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***********************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [stop ceph mdss with systemd] *****************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by bengland2** [comment]
Seb,  you won't see the problem until the software has been uninstalled and there is no unit file.
Then comment out the **failed_when: false** line above and you'll see the problem.  See [issue 1520](https://github.com/ceph/ceph-ansible/issues/1520).  It *should* be idempotent already, that's a bug in ansible service module IMO.  If you ask ansible to stop a non-existent service, that should be a noop with success status, but it isn't.

**Comment by leseb** [comment]
Right my bad. I think we might want to push this over to the Ansible project. In the meantime, let's move ahead with this. Thanks Ben!

**Comment by leseb** [comment]
Actually, the only problem I see here is that the play might continue if the service stop fails and we don't really want that...
One way to handle that might be to use the command module and look up for a `No such file or directory` and then only fail if stderr does not contain it.

**Comment by bengland2** [comment]
Is there any simpler way I could have done this?  I tried to do all this within the stop task by registering the result in a variable and testing the stdout_lines for 'service could not be found' but it gave me 

    fatal: [ip-172-31-12-170]: FAILED! => {"failed": true, "msg": "The conditional check ''service could not 
    be found' not in ceph_mds_status.stdout_lines | join | lower' failed. The error was: error while 
    evaluating conditional ('service could not be found' not in ceph_mds_status.stdout_lines | join | lower): 
    'dict object' has no attribute 'stdout_lines'"}

**Comment by bengland2** [comment]
it appears this passed according to [Sebastien's comment here](https://github.com/ceph/ceph-ansible/pull/1816#issuecomment-325301914).

**Comment by leseb** [comment]
@bengland2 what about osds? What if the osd_id list is empty?

**Comment by bengland2** [comment]
If the OSD ID list is empty, then the 'get osd numbers' task registered an empty list, which means that all the OSD filesystems were already removed.  I don't think this can happen unless the OSD daemons were shut down first.  Since the OSD ids list is empty, then there will be no attempt to stop OSD daemons.   This means the ansible problem with stopping a non-existent service is not encountered.

**Comment by leseb** [comment]
Well what you're testing is when ceph-ansible never ran so there might be no ceph-osd unit files at all so I'm expecting a failure. This task: https://github.com/bengland2/ceph-ansible/blob/c3988cca4b8d5b514b8f4433567fd3165b95cad1/infrastructure-playbooks/purge-cluster.yml#L247-L253 will never get skipped as there is no condition for osd_id.

**Comment by bengland2** [comment]
Apparently since the with_items clause points to an empty list, it never gets executed in that case either.  I tried this with ansible-2.3.1.0-3.el7.noarch and it did not fail.  In any case, what Ceph OSD number should I use to implement the status check if the osd_ids list is empty?

**Comment by bengland2** [comment]
I came up with this patch that will address your concern, I think.  Is this what you want before I commit it to this branch?

```
+  - name: see if ceph-osd.target is installed
+    shell: "systemctl status ceph-osd.target"
+    register: status_ceph_osd_target
+    failed_when: false
+
   - name: stop ceph-osd with systemd
     service:
       name: ceph-osd@{{item}}
       state: stopped
       enabled: no
     with_items: "{{ osd_ids.stdout_lines }}"
+    failed_when: "'unit ceph-osd.target could not be found' not in status_ceph_osd_target.stdout_lines | join | lower"
     when: ansible_service_mgr == 'systemd'
```

**Comment by bengland2** [comment]
do not merge yet. found a problem.

**Comment by leseb** [comment]
@bengland2 what's the status of this? Thanks!

**Comment by guits** [comment]
@bengland2 any news for this?

**Comment by bengland2** [comment]
can't work on this right now, sorry, it's up to you if you want to use it.  I'll leave development to the development team.

**Pull request closed without merging**
