### PR TITLE
ci: test luminous

### PR DESCRIPTION
**Pull request by leseb**
Luminous is out so let's test it instead of Kraken.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
I think it's fine to update the default value here, but we were never testing kraken because each ceph version factor sets ``CEPH_STABLE_RELEASE`` itself.  See: https://github.com/ceph/ceph-ansible/blob/master/tox.ini#L126

**Comment by leseb** [comment]
@andrewschoen it's weird, all the iscsi tasks were being skipped here: https://github.com/ceph/ceph-ansible/pull/1747
Looking at the logs, kraken was showing up as a release, cherry picking this commit into that PR now make the role being played...

**Comment by andrewschoen** [comment]
@leseb, it looks like you're using the wrong group name.

https://github.com/ceph/ceph-ansible/pull/1747/commits/b4ac5b3b449d65bd037842a79d47344746fde249#diff-b0b857e9bebef348b0c2b15e96769ab6R21

https://github.com/ceph/ceph-ansible/pull/1747/commits/b4ac5b3b449d65bd037842a79d47344746fde249#diff-657cf23ae65985b42e777b5c9208ec72R54

iscsi-gw and iscsi_gws are both used

**Comment by leseb** [comment]
jenkins test this please

**Pull request merged**
