### PR TITLE
Use 'package' module instead of yum, apt and dnf

### PR DESCRIPTION
**Pull request by guits**
Refactor the code using 'package' module

Fix Issue #520 

(However it doesn't cover all cases because some of them are not refactorable.
Ex: because of diverging packages name between distribution)

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
jenkins test ansible2.2-xenial-cluster

**Comment by leseb** [comment]
jenkins test ansible2.2-dmcrypt-journal-collocation
jenkins test ansible2.2-journal-collocation

**Comment by leseb** [comment]
jenkins test ansible2.2-journal-collocation

**Comment by andrewschoen** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Pull request merged**
