### PR TITLE
keywords requiring only one item shouldn't use a list for it

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Do this for `when`, `tags`, `notify`, `hosts`, `delegate_to` and `with_items` keywords.

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
@dsavineau @guits 
Do we have any more changes concerning coding style?

I think this would be good moment to add a coding style guideline file to our repository. Should I write a draft and share with you guys?

**Comment by rishabh-d-dave** [comment]
jenkins test dev-ubuntu-non_container-all_daemons

**Comment by rishabh-d-dave** [comment]
>  perhaps provide the source / doc url link

I don't understand what you mean by source/doc URL.

**Comment by guits** [comment]
@rishabh-d-dave if there's a documentation somewhere suggesting this like if it is a best practice or whatever.

**Comment by rishabh-d-dave** [comment]
Ok. Cool.

**Comment by rishabh-d-dave** [comment]
@guits @dsavineau 
Another thing that keeps poking me in the eye is leaving too many newlines. For exmaple, in add-osd.yml we have an extra newline after every key-value pair in the playbook.

There are plenty playbooks like this.

**Comment by rishabh-d-dave** [comment]
@dsavineau I thought I requested review from you too when I created this PR. But since I don't see if you removed yourself from "reviewers", I think I just thought it and forgot to it actually. :P

**Comment by rishabh-d-dave** [comment]
@guits @dsavineau 
Can you guys please review and merge this PR ASAP? Since this PR makes changes all across the repo, I get 7-8 files with merge conflict every time I rebase this PR. :P

**Comment by rishabh-d-dave** [comment]
Also, JFYKI, some of the new commits still go on to continue with mistakes fixed on this PR.  :)

**Comment by rishabh-d-dave** [comment]
jenkins test dev-ubuntu-container-all_daemons

**Comment by guits** [comment]
unrelated failure, merging anyway

**Pull request merged**
