### PR TITLE
[skip ci] handler: do not test if pgs_num = 0

### PR DESCRIPTION
**Pull request by leseb**
We don't need to wait if they are no PGS.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test all

**Comment by guits** [comment]
jenkins test all

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-bluestore_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-bluestore_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-bluestore_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-bluestore_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-bluestore_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-bluestore_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-purge_dmcrypt

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-update_cluster

**Comment by leseb** [comment]
jenkins test all

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-xenial_cluster

**Comment by leseb** [comment]
jenkins test all

**Comment by leseb** [comment]
jenkins test all

**Pull request merged**
