### PR TITLE
Ansible2

### PR DESCRIPTION
**Pull request by jfcoz**
This is syntax update for ansible 2

### CODE REVIEW

**Comment by leseb** [comment]
Thanks @jfcoz some of those will likely remove a log of deprecation warnings :).
I'm just curious, where did you find that this was the v2 way to write things?
Don't we do `{{ foo }}` but {{foo}}? Or does this only work for `groups` and `with_items`?

**Comment by jfcoz** [comment]
For `{{foo}}` it's from the deprecation warning.
For `with_items` it's from http://docs.ansible.com/ansible/playbooks_loops.html#looping-over-the-invento

**Comment by leseb** [comment]
@jfcoz unfortunately, it seems that this is breaking `1.9.4`... :(
Not sure if everyone has moved to v2 yet...

**Comment by leseb** [comment]
@jfcoz give me a couple of days, I'm rethinking how I want to manage `1.9.4` and v2

**Comment by leseb** [comment]
@jfcoz would you mind rebasing this?

**Comment by leseb** [comment]
@jfcoz thanks for the rebase. Give me some time to see where it is failing in `1.9.4` thanks!

**Comment by leseb** [comment]
test this please

**Comment by leseb** [comment]
@jfcoz can I get a sign-off from you? I just pushed #1068 and I'd like to add you as a co-author for this as you originally started this initiative. Thanks!

**Pull request closed without merging**
