### PR TITLE
tests: test master against ansible 2.7

### PR DESCRIPTION
**Pull request by guits**
Let's test ceph-ansible master against ansible 2.7 to catch early any
potential issue with this ansible version.

Closes: #3148

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
we must wait for the first 2.7 release to be available in pip

**Comment by guits** [comment]
@ktdreyer what is the ansible version available in rpm repository for 2.7 ?

**Comment by ktdreyer** [comment]
The places where we ship ceph-ansible 3.0 (RHCS 2 and 3.0) have Ansible 2.4.

The places where we ship ceph-ansible 3.1 (RHCS 3.1) [will have](https://bugzilla.redhat.com/show_bug.cgi?id=1576102) Ansible 2.4.

The places where we ship ceph-ansible 3.2 (RHCS 3.2) [will have](https://bugzilla.redhat.com/show_bug.cgi?id=1613941) Ansible 2.6 ... although there's discussion ongoing with @gfidente regarding TripleO compatibility with Ansible 2.6. It seems like it would be wise to keep Ansible 2.5 compatibility in ceph-ansible if it is not hurting anything.

**Comment by gfidente** [comment]
@ktdreyer +1

tripleo uses luminous in queens and rocky; we could try using ansible 2.6 (or 2.7) in rocky but it's much more difficult to bump it in queens

I would vote for keeping 2.5 compatibility as well

**Comment by gfidente** [comment]
pretty sure at least [1] needs to be fixed to work past 2.5

1. https://github.com/ceph/ceph-ansible/blob/v3.1.6/plugins/actions/_v2_config_template.py#L638

**Pull request merged**
