### PR TITLE
lv-create: Add missing spaces

### PR DESCRIPTION
**Pull request by IgorBMSTU**
lv-create: Add missing spaces
jenkins test infra_lv_create
Signed-off-by: Bogomolov Igor <igor95n@gmail.com>
Co-Authored-By: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by IgorBMSTU** [comment]
lv-create scenario doesn`t work for me, so I made some changes and can apply them.  But first, I want to make sure this test fails in Jenkins

**Comment by IgorBMSTU** [comment]
jenkins test infra_lv_create

**Comment by IgorBMSTU** [comment]
I can`t run this task and CI fails even if I just added spaces that don't affect anything

**Comment by IgorBMSTU** [comment]
jenkins test infra_lv_create

**Comment by IgorBMSTU** [comment]
guide: https://docs.ceph.com/ceph-ansible/master/testing/running.html
try infra_lv_create scenario: 
```
(ceph_env) ➜  ceph-ansible git:(master) pip install -r tests/requirements.txt &> install_requiremets.log
(ceph_env) ➜  ceph-ansible git:(master) pip install tox
```
make sure it is available
```
(ceph_env) ➜  ceph-ansible git:(master) tox -l|grep -c infra_lv_create
1
```
now try tox:
```
(ceph_env) ➜  ceph-ansible git:(master) tox -e infra_lv_create
infra_lv_create installed: ansible==2.8.3,apipkg==1.5,apt-clone==0.2.1,apt-xapian-index==0.47,apturl==0.5.2,atomicwrites==1.3.0,attrs==19.1.0,bcrypt==3.1.7,blinker==1.3,Brlapi==0.6.4,cffi==1.12.3,chardet==2.3.0,command-not-found==0.3,configobj==5.0.6,cryptography==1.2.3,defer==1.0.6,dirspec==13.10,execnet==1.6.1,httplib2==0.9.1,idna==2.0,importlib-metadata==0.19,Jinja2==2.10.1,jmespath==0.9.4,louis==2.6.4,lxml==3.5.0,Mako==1.0.3,MarkupSafe==0.23,mock==3.0.5,more-itertools==7.2.0,netaddr==0.7.19,notario==0.0.16,oauthlib==1.0.3,onboard==1.2.0,oneconf==0.3.9,openshot-qt==2.4.3.dev1,paramiko==2.6.0,pathlib2==2.3.4,pexpect==4.0.1,Pillow==3.1.2,piston-mini-client==0.7.5,pluggy==0.12.0,psutil==3.4.2,ptyprocess==0.5,py==1.8.0,pyasn1==0.1.9,pycparser==2.19,pycrypto==2.6.1,pycups==1.9.73,pycurl==7.43.0,pygobject==3.20.0,PyICU==1.9.2,PyJWT==1.3.0,PyNaCl==1.3.0,pytest==4.4.2,pytest-forked==1.0.2,pytest-rerunfailures==7.0,pytest-xdist==1.28.0,python-apt==1.1.0b1+ubuntu0.16.4.2,python-debian==0.1.27,python-xapp==1.0.0,pyxdg==0.25,PyYAML==5.1.2,pyzmq==15.2.0,reportlab==3.3.0,requests==2.9.1,sessioninstaller==0.0.0,setproctitle==1.1.8,six==1.10.0,system-service==0.3,testinfra==3.0.6,thin-client-config-agent==0.8,ubuntu-drivers-common==0.0.0,ufw==0.35,urllib3==1.13.1,vboxapi==1.0,virtkey==0.63.0,virtualenv==15.0.1,xkit==0.0.0,zipp==0.5.2
infra_lv_create run-test-pre: PYTHONHASHSEED='3218960978'
infra_lv_create run-test: commands[0] | vagrant up --no-provision --provider=virtualbox
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/igor/projects/ceph-ansible/Vagrantfile
Line number: 0
Message: Errno::ENOENT: No such file or directory @ rb_sysopen - /home/igor/projects/ceph-ansible/vagrant_variables.yml
ERROR: InvocationError for command /usr/bin/vagrant up --no-provision --provider=virtualbox (exited with code 1)
______________________________________________________________________________________________________________ summary _______________________________________________________________________________________________________________
ERROR:   infra_lv_create: commands failed
(ceph_env) ➜  ceph-ansible git:(master)
```


```
(ceph_env) ➜  ceph-ansible git:(master) tox --version
3.13.2 imported from /home/igor/projects/ceph_env/lib/python3.5/site-packages/tox/__init__.py
(ceph_env) ➜  ceph-ansible git:(master) vagrant --version
Vagrant 1.8.1
```

**Comment by IgorBMSTU** [comment]
description of commit above:

command:
`(ceph_env) ➜  ceph-ansible git:(master) tox -e infra_lv_create`

error:
Message: Errno::ENOENT: No such file or directory @ rb_sysopen - /home/igor/projects/ceph-ansible/vagrant_variables.yml

solution:
in tox.ini
`changedir={toxinidir}/tests/functional/centos/7/infra_lv_create` -> `changedir={toxinidir}/tests/functional/infra_lv_create`

next error:
ansible remote provisioner:
 `playbook` does not exist on the host: /home/igor/projects/ceph-ansible/tests/functional/infra_lv_create/site.yml

solution:
create symlink
`ln -s ../../../site.yml.sample site.yml`

error:
ERROR: InvocationError for command /bin/cat /home/ehrmann/projects/ceph-ansible/lv-create.log (exited with code 1)
solution:
in tox.ini:
cat {toxinidir}/lv-create.log => cat {toxinidir}/infrastructure-playbooks/lv-create.log

**Comment by guits** [comment]
@IgorBMSTU please, take a look at https://github.com/ceph/ceph-ansible/pull/4284/files#diff-1bbe7aa7b5ed53b2d4e3ea99c063c0ae

**Comment by IgorBMSTU** [comment]
Ok, I'll create new pull request with my fixes

**Pull request closed without merging**
