### PR TITLE
group_vars: remove useless files

### PR DESCRIPTION
**Pull request by dsavineau**
Delete legacy files that aren't used anymore.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-container-ooo_collocation

**Comment by guits** [comment]
jenkins test centos-container-ooo_collocation

**Comment by guits** [comment]
jenkins test centos-container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-collocation

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_batch

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_batch

**Comment by dsavineau** [comment]
jenkins test centos-container-all_daemons

**Comment by dsavineau** [comment]
jenkins test centos-container-lvm_osds

**Comment by dsavineau** [comment]
jenkins test centos-container-ooo_collocation

**Comment by dsavineau** [comment]
jenkins test centos-container-all_daemons

**Comment by dsavineau** [comment]
jenkins test centos-container-all_daemons

**Pull request merged**
