### PR TITLE
Mgr key

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Pull request merged**
