### PR TITLE
flake8 library/ceph_volume.py

### PR DESCRIPTION
**Pull request by hswong3i**
Copy to and backport from https://github.com/alvistack/ansible-role-ceph_osd/blob/develop/library/ceph_volume.py

Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Review by guits — DISMISSED** [review]

**Comment by guits** [comment]
could be nice to do same thing for other modules

**Comment by hswong3i** [comment]
> could be nice to do same thing for other modules

With another PR? I could contribute for that after this ;-)

**Comment by hswong3i** [comment]
> > could be nice to do same thing for other modules
> 
> With another PR? I could contribute for that after this ;-)

@guits Well I had try my test for `flake8 library/*`, please kindly review.

**Comment by hswong3i** [comment]
Spited into:
- #5730
- #5731 
- #5732
- #5733 
- #5734 
- #5735 
- #5736

**Comment by guits** [comment]
the errors you saw in the CI are unrelated to your PR

**Pull request closed without merging**
