### PR TITLE
bring 2 commits from stable branche into master

### PR DESCRIPTION
**Pull request by guits**
Somehow, those got merged directly in stable branches. Those commits should have been merged first in master, then in stable-3.2 and/or stable-3.1 to ease the tracking and avoid potential regression.

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test dev-container_podman

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test dev-lvm_osds_container

**Comment by leseb** [comment]
jenkins test dev-container_podman

**Comment by guits** [comment]
jenkins test dev-docker_cluster

**Comment by guits** [comment]
jenkins test dev-container_podman

**Comment by guits** [comment]
jenkins test dev-lvm_osds_container

**Comment by leseb** [comment]
jenkins test dev-lvm_osds

**Comment by leseb** [comment]
jenkins test dev-lvm_osds

**Pull request merged**
