### PR TITLE
stable-3.2: set any_errors_fatal to true for all host sections

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Attemps to fix https://bugzilla.redhat.com/show_bug.cgi?id=1646456

### CODE REVIEW

**Comment by guits** [comment]
@rishabh-d-dave I think you can backport it from master and resolve conflict if there's one ?

**Comment by rishabh-d-dave** [comment]
Ok, sure. But I am curious about why so?  :)

**Comment by guits** [comment]
@rishabh-d-dave we never commit directly in stable branches except for *very* *very* particular cases (in that case you would have to add a backport note to explain why you had to do so).
eg: when the code has really too much differences between master and the stable branch or even doesn't exist anymore.
If there's only few modifications that you'll have to resolve as conflict merge, it's fine.

**Comment by rishabh-d-dave** [comment]
@guits Hmm, ok. Thanks!

**Comment by rishabh-d-dave** [comment]
`mimic-xenial_cluster` job, too, ran successfully!
[pr-3452-mim-xenial_cluster.log](https://github.com/ceph/ceph-ansible/files/2690013/pr-3452-mim-xenial_cluster.log)

**Comment by guits** [comment]
Closing this PR, this should be backported from master once #3451 gets merged.

**Pull request closed without merging**
