### PR TITLE
validate: ceph_origin and containerized_deployment can not both be set

### PR DESCRIPTION
**Pull request by andrewschoen**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1630975

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
@leseb I realize they are mutually exclusive, but in the case where you're deploying containers you use a different playbook and I believe ``containerized_deployement`` will take precedence right?

I'd really hesitate to add another special downstream all.yml file. This patch lets a downstream user just set ``containerized_deployment: True`` and deploy, not having to worry about using different group_vars. The amount of change needed for option 1 I don't think provides a bunch of value either.

**Comment by leseb** [comment]
@andrewschoen I'm just to trying to avoid confusion and educate the user on how options should be configured. Can't instead fail if both are `ceph_origin` and `containerized_deployement` configured?

**Comment by leseb** [comment]
@andrewschoen looks good! Thanks for the followup :)

**Comment by andrewschoen** [comment]
@leseb ok, I've got this changed. Thanks.

**Comment by leseb** [comment]
@andrewschoen thanks!

**Comment by leseb** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
jenkins test pipeline

**Pull request merged**
