### PR TITLE
podman: support podman installation on rhel8

### PR DESCRIPTION
**Pull request by guits**
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1667101

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
@gfidente @fultonj FYI

**Comment by guits** [comment]
jenkins test dev-centos7_cluster

**Comment by guits** [comment]
jenkins test dev-docker_cluster

**Comment by guits** [comment]
not testing the desired scenario (podman/rhel8) but at least to see if it's not breaking existing scenario.

**Comment by guits** [comment]
jenkins test dev-docker_cluster

**Comment by guits** [comment]
jenkins test dev-centos7_cluster

**Comment by guits** [comment]
jenkins test dev-rhel-container-podman

**Comment by guits** [comment]
jenkins test dev-rhel-container-podman

**Comment by guits** [comment]
jenkins test dev-rhel-container-podman

**Comment by guits** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test dev-rhel-container-podman

**Comment by guits** [comment]
jenkins test dev-rhel-container-podman

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_batch

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_batch

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-rhel-container-podman

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_batch

**Comment by guits** [comment]
jenkins test dev-rhel-container-podman

**Comment by guits** [comment]
jenkins test dev-rhel-container-podman

**Comment by guits** [comment]
jenkins test dev-rhel-container-podman

**Comment by guits** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by guits** [comment]
the only failure in pipeline `ceph-ansible-prs-dev-centos-non_container-lvm_batch` is unrelated to this patch

**Comment by leseb** [comment]
image

**Pull request merged**
