### PR TITLE
drop use_fqdn variables

### PR DESCRIPTION
**Pull request by dsavineau**
This has been deprecated in the previous releases. Let's drop it.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test centos-container-all_daemons

**Comment by dsavineau** [comment]
jenkins test centos-container-update

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_batch

**Comment by dsavineau** [comment]
jenkins test centos-non_container-update

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_batch

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_batch

**Pull request merged**
