### PR TITLE
Preserve rolling_update backward compatibility with ansible < 2.5

### PR DESCRIPTION
**Pull request by gfidente**
Signed-off-by: Giulio Fidente <gfidente@redhat.com>

### CODE REVIEW

**Comment by gfidente** [comment]
@guits @leseb until we're ready for the better version, this looks safe to me

**Comment by gfidente** [comment]
I think @xbezdick tested and confirmed this to work

**Comment by guits** [comment]
@gfidente which one? 3512 and/or 3514 ?

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
unrelated failure

**Comment by guits** [comment]
@gfidente My bad if I didn't catch it before merging but commit message and `Fixes:` keyword would have been nice

**Pull request merged**
