### PR TITLE
wip: galaxy roles dependencies

### PR DESCRIPTION
**Pull request by leseb**
in order to have a build on the galaxy we need to have a proper
dependency set for ceph-common. On the galaxy ceph-common does not
exist, only ceph.ceph-common is available.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
test this please

**Comment by leseb** [comment]
test this please

**Comment by leseb** [comment]
test this please

**Comment by leseb** [comment]
@alfredodeza @andrewschoen do you guys see anything wrong with this patch?

**Comment by andrewschoen** [comment]
This looks good to me. +1

**Comment by leseb** [comment]
@andrewschoen I'll take the merge as a +1 then :D. Thanks!

**Pull request merged**
