### PR TITLE
Revert Improve devices validation (backport #6150)

### PR DESCRIPTION
**Pull request by dsavineau**
This reverts #6652 as this shouldn't have been merge.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by dsavineau** [comment]
jenkins test centos-container-lvm_osds

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_batch

**Comment by dsavineau** [comment]
jenkins test centos-container-lvm_batch

**Review by guits — APPROVED** [review]

**Pull request merged**
