### PR TITLE
library: fix bug in ceph_volume

### PR DESCRIPTION
**Pull request by guits**
This commit fixes a regression introduced by
0326d992c2b6b92a6d4b8ccf2a51d9343652da48.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test centos-non_container-filestore_to_bluestore

**Comment by dsavineau** [comment]
jenkins test centos-container-filestore_to_bluestore

**Comment by guits** [comment]
jenkins test centos-container-filestore_to_bluestore

**Comment by guits** [comment]
jenkins test centos-non_container-filestore_to_bluestore

**Comment by guits** [comment]
jenkins test centos-non_container-filestore_to_bluestore

**Comment by guits** [comment]
jenkins test centos-container-filestore_to_bluestore

**Comment by guits** [comment]
jenkins test centos-container-filestore_to_bluestore

**Comment by guits** [comment]
jenkins test centos-non_container-filestore_to_bluestore

**Pull request merged**
