### PR TITLE
Revert "tests: temporarily use david's flavor"

### PR DESCRIPTION
**Pull request by guits**
This reverts commit ed9f0641eee3da314a66f5ed7c2722ac973481d3.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
waiting for the nfs-ganesha patch to be merged and build available on shaman before merging this

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Pull request merged**
