### PR TITLE
Erwan aliasr1 evelu choose disk

### PR DESCRIPTION
**Pull request by leseb**
Fixes: https://github.com/ceph/ceph-ansible/issues/1084

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-docker_dedicated_journal

**Comment by leseb** [comment]
jenkins test kraken-ansible2.2-journal_collocation

**Comment by leseb** [comment]
jenkins test kraken-ansible2.2-purge_dmcrypt

**Comment by leseb** [comment]
jenkins test kraken-ansible2.2-docker_dedicated_journal

**Comment by leseb** [comment]
jenkins test kraken-ansible2.2-update_dmcrypt

**Comment by leseb** [comment]
jenkins test playbook syntax

**Comment by leseb** [comment]
jenkins test syntax-check

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-update_docker_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-dmcrypt_journal_collocation

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-docker_dedicated_journal

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-xenial_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.2-bluestore_dmcrypt_journal_collocation

**Comment by guits** [comment]
jenkins test luminous-ansible2.2-bluestore_docker_dedicated_journal

**Comment by alfredodeza** [comment]
Although I still value the problem this PR is trying to solve I am still -1 on merging this as-is today:

* This PR is heavily targeting ceph-disk and filestore (both of which should
  not be the only case moving forward)

* Introduces a level of granularity that is problematic to maintain and reason
  about: custom comparison operators, kilobyte/megabyte support, etc...

* Does a thorough effort to identify disks by-id which ends up not being
  entirely necessary once disks are handled by ceph-volume

If the scope/granularity of the PR could be drastically reduced, incorporate items that
would benefit ceph-volume, we might have something that would be nice to work
with.

**Comment by leseb** [comment]
@alfredodeza I agree, no worries we were not intended to merge this as is :). `choose_disk` requires heavy lifting, just like you said the focus is on Filestore/ceph-disk, so we need to revisit the implementation. The detection is fine. I think we need to sync up together on this. The idea will be to have legacy support for existing configuration, but for newer, it should work with ceph-volume.

**Pull request closed without merging**
