### PR TITLE
Execute common roles once on all nodes

### PR DESCRIPTION
**Pull request by dsavineau**
The common roles don't need to be executed again on each group plays
(like mons, osds, etc..).
We only need to execute them during the first play. That wat, we will
apply the changes on all nodes in parallel instead of doing it once per
group.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test centos-non_container-purge

**Pull request merged**
