### PR TITLE
Rm ceph disk scenarios

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test this pleaser

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
@andrewschoen not yet, I need to cherry-pick another commit.

**Comment by leseb** [comment]
@andrewschoen done.

**Comment by leseb** [comment]
jenkins test ceph-ansible-prs-luminous-lvm_osds

**Comment by leseb** [comment]
jenkins test lvm_osds

**Comment by leseb** [comment]
jenkins test luminous-add_osds

**Comment by andrewschoen** [comment]
The commit b59db68015b84b0c646542daa18c1c7a8d85ba4d will break setups where ``devices`` or ``lvm_volumes`` is not defined in all.yml, or another mon specific group_vars or host_vars file. For example, this breaks ceph-volume testing because we use host_vars to store OSD config in some tests.

**Comment by leseb** [comment]
@andrewschoen yeah, at the moment, it's breaking things. I think the commit was working for https://github.com/ceph/ceph-ansible/pull/3187, but it appears it needs rework.

**Comment by leseb** [comment]
The follow up on this is to change the scenarios so they can start using Ceph master.

**Comment by leseb** [comment]
jenkins test luminous-bluestore_lvm_osds_container

**Comment by leseb** [comment]
jenkins test luminous-bluestore_lvm_osds

**Comment by leseb** [comment]
jenkins test luminous-add_osds

**Comment by leseb** [comment]
jenkins test luminous-add_osds_container

**Comment by leseb** [comment]
jenkins test luminous-lvm_osds

**Comment by leseb** [comment]
jenkins test luminous-lvm_osds_container

**Comment by leseb** [comment]
jenkins test luminous-lvm_osds

**Comment by leseb** [comment]
jenkins test luminous-add_osds_container

**Comment by leseb** [comment]
We want to keep the history of the jobs that ran, so we are going to merge this with the DNM flag on.

**Pull request merged**
