### PR TITLE
osd: drop filestore support

### PR DESCRIPTION
**Pull request by guits**
filestore is about to be removed.
This commit removes the filestore support in ceph-ansible.

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-lvm_batch

**Comment by guits** [comment]
jenkins test centos-container-all_in_one

**Comment by guits** [comment]
jenkins test centos-non_container-collocation

**Comment by guits** [comment]
jenkins test centos-container-external_clients

**Comment by guits** [comment]
jenkins test centos-container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-subset_update

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Comment by guits** [comment]
jenkins test centos-non_container-all_in_one

**Review by asm0deuz — APPROVED** [review]
LGTM

**Pull request merged**
