### PR TITLE
Backport of 2451 in stable-3.1

### PR DESCRIPTION
**Pull request by leseb**
Backport of #2451 in stable-3.1

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1581403

### CODE REVIEW

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by leseb** [comment]
Master is broken on ansible2.4-update_docker_cluster. Fix is here: https://github.com/ceph/ceph-ansible/pull/2627

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-update_docker_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Pull request merged**
