### PR TITLE
Revert "Change enabling of extras repo for CentOS to use ini_file"

### PR DESCRIPTION
**Pull request by verdurin**
Reverts ceph/ceph-ansible#1042

### CODE REVIEW

**Comment by andrewschoen** [comment]
This PR is still failing the centos7 build here: 

https://jenkins.ceph.com/job/ceph-ansible-pull-requests/764/DIST=ceph_ansible_pr_centos7/console

There is still this instance of ``yum_repository`` that fails with:

"Parameter 'baseurl' or 'mirrorlist' is required.

We're not testing docker at the moment, but I imagine all the instances of ``yum_repository`` used in this PR will also fail. If we're gonna use ``yum_repository`` then we need to make sure it's using the all of the required parameters, see: 

https://docs.ansible.com/ansible/yum_repository_module.html

**Comment by alfredodeza** [comment]
The syntax check is also failing here. Please make sure this is taken care off as well

**Comment by andrewschoen** [comment]
@alfredodeza the syntax check will probably fail on most PRs until this is merged. https://github.com/ceph/ceph-ansible/pull/1051

This PR is failing on a things I fixed in #1051

**Comment by leseb** [comment]
Can we have a status on this one?
So many things happened while I was away, I kinda lost track on this one.
Thanks!

**Comment by leseb** [comment]
Oh and yeah this was breaking everything last week so if this is still the case I'd like to rollback as far as it will be necessary. Thanks!

**Comment by andrewschoen** [comment]
@leseb This PR fixed the failure we were seeing in our centos7 tests in jenkins related to this work: https://github.com/ceph/ceph-ansible/pull/1050

I'm not sure what impact this PR has on the docker tasks however.

**Pull request merged**
