### PR TITLE
ceph-infra: update handler with daemon variable

### PR DESCRIPTION
**Pull request by dsavineau**
Both ntp and chrony daemon use variable for the service name because it
could be different depending on the GNU/Linux distribution.
This has been update in 9d88d3199 for chrony but only for the start part
not for the handler.
The commit fixes this for both ntp and chrony.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
mergify failed to automerge, doing it manually

**Pull request merged**
