### PR TITLE
igw: add support for IPv6

### PR DESCRIPTION
**Pull request by dillaman**
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by dillaman** [comment]
These changes are tied to https://github.com/ceph/ceph-iscsi-config/pull/89

**Comment by dillaman** [comment]
jenkins test pipeline

**Comment by dillaman** [comment]
@leseb It's BZ1643584

**Comment by leseb** [comment]
@dillaman thanks

**Comment by dillaman** [comment]
@leseb is that colocated PR pipeline failure a known issue?

**Comment by leseb** [comment]
Unrelated, merging this, thanks

**Pull request merged**
