### PR TITLE
contrib: push all new stable branches to the galaxy

### PR DESCRIPTION
**Pull request by leseb**
Prior to this patch we were only pushing 'master' and 'ansible-1.9'
branches. Each new release also introduces a new branch so we want to
push it as well.

Yes the 'grep' is a bit ugly, feel free to come up with something nicer :)

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
This needs to wait a little bit as we will change the stable branching with names and not release version number.

**Comment by zhsj** [comment]
```

**Comment by zhsj** [comment]
```
git branch --list -r "upstream/stable-*" "upstream/master" "upstream/ansible-1.9" 
```

**Comment by andrewschoen** [comment]
@zhsj +1

Works well for me locally:

```
git branch --list -r "origin/stable-*" "origin/master" "origin/ansible-1.9" | cut -d '/' -f2
ansible-1.9
master
stable-2.1
```

**Comment by leseb** [comment]
@zhsj thanks!

**Comment by zhsj** [comment]
@leseb a quick look at your code, did you miss the `cut` ?

**Comment by leseb** [comment]
@zhsj oops yes :). Thanks!

**Comment by andrewschoen** [comment]
jenkins test ansible2.2-xenial_cluster

**Pull request merged**
