### PR TITLE
use "pre_tasks" and "post_tasks" whenever required

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Signed-off-by: Rishabh Dave <ridave@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
Please wait for https://github.com/ceph/ceph-ansible/pull/3325
Thanks

**Comment by rishabh-d-dave** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
Please wait for https://github.com/ceph/ceph-ansible/pull/3324

**Comment by leseb** [comment]
@rishabh-d-dave please rebase

**Comment by rishabh-d-dave** [comment]
Retesting this PR since the error (copied below) is transient IMO.

```
fatal: [ceph-rgw0]: FAILED! => {
    "changed": false
}

MSG:

Failure talking to yum: Cannot find a valid baseurl for repo: base/7/x86_64
changed: [ceph-rbd-mirror0] => {
```

**Comment by rishabh-d-dave** [comment]
jenkins test pipeline

**Comment by rishabh-d-dave** [comment]
While replacing `role` and `roles` by `import_role`, I lumped all tasks together under `tasks` since I thought that `pre_tasks` and `post_tasks` can only be in conjunction to `role` (that is also why I added the comment). After learning that that was incorrect, I raised this PR.

**Pull request merged**
