### PR TITLE
Use ansible_facts

### PR DESCRIPTION
**Pull request by mwhahaha**
It has come to our attention that using ansible_* vars that are
populated with INJECT_FACTS_AS_VARS=True is not very performant.  In
order to be able to support setting that to off, we need to update the
references to use ansible_facts[<thing>] instead of ansible_<thing>.

Related: ansible#73654

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1935406

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
failure is unrelated

**Comment by guits** [comment]
@gfidente / @fmount / @fultonj 

I guess you wanna see this patch in stable-4.0, right?

**Comment by fmount** [comment]
> @gfidente / @fmount / @fultonj
> 
> I guess you wanna see this patch in stable-4.0, right?

Yes, that should definitely be backported to stable-4.0 (which matches with the stable/train OpenStack branch)

**Comment by guits** [comment]
> > @gfidente / @fmount / @fultonj
> > I guess you wanna see this patch in stable-4.0, right?
> 
> Yes, that should definitely be backported to stable-4.0 (which matches with the stable/train OpenStack branch)

in that case, we need a BZ I think

**Review by cloudnull — DISMISSED** [review]

**Comment by mwhahaha** [comment]
JFYI there's likely another patch that needs to go on top of this to ensure we have mounts and interfaces facts when necessary as we're reducing the default fact gathering scope as well. For now we can disable this requirement when calling ceph-ansible https://review.opendev.org/c/openstack/tripleo-ansible/+/778553.  https://bugzilla.redhat.com/show_bug.cgi?id=1911891 is the BZ we're using for tripleo items

**Comment by guits** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=1911891 is the BZ we're using for tripleo items

we will probably need a BZ in RHCS/Ansible Product/Component

**Comment by fultonj** [comment]
> > https://bugzilla.redhat.com/show_bug.cgi?id=1911891 is the BZ we're using for tripleo items
> 
> we will probably need a BZ in RHCS/Ansible Product/Component

OK, I've opened one:  https://bugzilla.redhat.com/show_bug.cgi?id=1935406

**Comment by guits** [comment]
@fultonj thanks!

@mwhahaha could you add the `Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1935406` in your commit message please? thanks!

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Review by guits — APPROVED** [review]

**Comment by mykaul** [comment]
Would be nice to add a comment to https://docs.ansible.com/ansible/latest/reference_appendices/config.html#inject-facts-as-vars with the above information and alternative implementation.

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Pull request merged**
