### PR TITLE
support Xen xvd devices, factor regexes into vars in ceph-default

### PR DESCRIPTION
**Pull request by bengland2**
This change lets ceph-ansible work with Amazon EC2 VMs that use the /dev/xvd* block device family (Xen virtualization).  This change also factors out block device name regular expressions to make code more maintainable and extensible to future block device families.  These vars are in role ceph-defaults, so they can be easily included in any playbook that needs them.  This PR cleans up PR 1816, which I have closed.

### CODE REVIEW

**Comment by leseb** [comment]
Sorry for the wait, please rebase @bengland2

**Comment by bengland2** [comment]
I think its rebased now, my changes are smaller now because you removed check_devices_auto.yml and removed tasks from check_devices*.yml that I had changed.  Sorry about the empty "complete merge with origin" commit, git told me to do it.

**Comment by leseb** [comment]
wrong rebase!

**Comment by bengland2** [comment]
I did "git rebase master", must have been wrong to get all those commits displayed up here.  Will resubmit PR again, this is getting tiring.

**Pull request closed without merging**
