### PR TITLE
[skip ci] validate: fix validation of bluestore lvm scenario

### PR DESCRIPTION
**Pull request by andrewschoen**
Fixes: #2617

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test luminous-ansible2.4-bluestore_lvm_osds

**Comment by andrewschoen** [comment]
jenkins test luminous-ansible2.4-lvm_osds

**Comment by ErwanAliasr1** [comment]
I cannot agree more. Every commit have to answer those points in the commit message

- what is the issue / why do you need this change
- how you solved it

If the commit is tricky then an extra part is necessary to explain the commit in details to help further reader to understand the way you thought.

It's not because a commit is short that it doesn't need a {long} commit message.

**Comment by andrewschoen** [comment]
@leseb @ErwanAliasr1 I've squashed the commits together and added a long commit message. Let me know if you need any more detail there. Thanks.

**Pull request merged**
