### PR TITLE
backport of 2197

### PR DESCRIPTION
**Pull request by leseb**
Backport of #2197

### CODE REVIEW

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_container

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_container
$

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-bluestore_osds_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-filestore_osds_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-bluestore_osds_non_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-filestore_osds_non_container

**Pull request merged**
