### PR TITLE
Fix docker cluster name

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
@font if you can have a look :)

**Comment by jimcurtis** [comment]
Do we also need to to add the cluster name to the rgw role (ceph-rgw/tasks/docker/checks.yml)?

**Comment by font** [comment]
@leseb Ok this appears to all be working for a default cluster name of `ceph`. I think there are still areas where we will run into issues with a non-default cluster name as shown below. Other than that looks good.
```
$ grep -rnE '(\/etc\/ceph\/(ceph.conf|ceph.client.admin.keyring|ceph.mon.keyring|monmap[^-])|\/var\/lib\/ceph\/bootstrap-*\/ceph.keyring)'                           <<<

debug.yml:507:                "/etc/ceph/ceph.client.admin.keyring",
debug.yml:508:                "/etc/ceph/ceph.conf",
debug.yml:509:                "/etc/ceph/monmap",
debug.yml:510:                "/etc/ceph/ceph.mon.keyring",
debug.yml:789:                                "path": "/etc/ceph/ceph.client.admin.keyring"
debug.yml:793:                        "item": "/etc/ceph/ceph.client.admin.keyring",
debug.yml:811:                                "path": "/etc/ceph/ceph.conf"
debug.yml:815:                        "item": "/etc/ceph/ceph.conf",
debug.yml:833:                                "path": "/etc/ceph/monmap"
debug.yml:837:                        "item": "/etc/ceph/monmap",
debug.yml:855:                                "path": "/etc/ceph/ceph.mon.keyring"
debug.yml:859:                        "item": "/etc/ceph/ceph.mon.keyring",
infrastructure-playbooks/cluster-os-migration.yml:300:        tar -cpvzf - --one-file-system . /etc/ceph/ceph.conf | cat > {{ ansible_hostname }}.tar
tests/validate-rados.yml:16:      src=/etc/ceph/ceph.client.admin.keyring
tests/validate-rados.yml:17:      dest=/etc/ceph/ceph.client.admin.keyring
roles/ceph-mon/tasks/docker/start_docker_monitor.yml:29:      - /etc/ceph/ceph.conf:/etc/ceph/ceph.defaults
roles/ceph-mon/tasks/docker/start_docker_monitor.yml:77:      path: /etc/ceph/ceph.conf
roles/ceph-mon/tasks/docker/create_configs.yml:28:    dest: /etc/ceph/ceph.conf
roles/ceph-mds/tasks/docker/fetch_configs.yml:7:      - /etc/ceph/ceph.conf
roles/ceph-mds/tasks/docker/fetch_configs.yml:8:      - /etc/ceph/ceph.client.admin.keyring
roles/ceph-rgw/tasks/multisite/destroy.yml:24:    dest: /etc/ceph/ceph.conf
roles/ceph-rgw/tasks/multisite/main.yml:21:    dest: /etc/ceph/ceph.conf
roles/ceph-rgw/tasks/docker/fetch_configs.yml:5:      - /etc/ceph/ceph.conf
roles/ceph-rbd-mirror/tasks/docker/fetch_configs.yml:7:      - /etc/ceph/ceph.conf
roles/ceph-rbd-mirror/tasks/docker/fetch_configs.yml:8:      - /etc/ceph/ceph.client.admin.keyring
roles/ceph-osd/tasks/docker/fetch_configs.yml:5:      - /etc/ceph/ceph.conf
roles/ceph-restapi/tasks/docker/fetch_configs.yml:5:      - /etc/ceph/ceph.conf
roles/ceph-restapi/tasks/docker/fetch_configs.yml:6:      - /etc/ceph/ceph.client.admin.keyring
roles/ceph-common/templates/s3gw.fcgi.j2:3:exec /usr/bin/radosgw -c /etc/ceph/ceph.conf -n client.radosgw.{{ ansible_hostname }}
roles/ceph-nfs/tasks/docker/start_docker_nfs.yml:52:      path: /etc/ceph/ceph.conf
roles/ceph-nfs/tasks/docker/copy_configs.yml:5:      - /etc/ceph/ceph.conf
roles/ceph-nfs/tasks/docker/copy_configs.yml:6:      - /etc/ceph/ceph.client.admin.keyring
```

**Comment by leseb** [comment]
Thanks @font, I fixed the remaining issues, I just left `infrastructure-playbooks/cluster-os-migration.yml` and `tests/validate-rados.yml`.
Not sure what `debug.yml` is, perhaps a script of yours.

**Comment by font** [comment]
@leseb ah yes, I should really clean up my sandbox. :)

**Comment by leseb** [comment]
@font yup `git grep` ftw :)

**Pull request merged**
