### PR TITLE
ceph_key: fix bug in 'info' feature

### PR DESCRIPTION
**Pull request by guits**
ceph_key: fix bug in 'info' feature
    
Fix 'info' feature from ceph_key.py module
    
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by dsavineau** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test. centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
the CI failure here is related to ceph/ceph#36091

**Pull request merged**
