### PR TITLE
Add SSL cert comment 

### PR DESCRIPTION
**Pull request by ppbrown**
Fixes: #4830

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test centos-container-update

**Comment by ppbrown** [comment]
jenkins test playbook syntax

**Comment by ppbrown** [comment]
jenkins test centos-container-all_daemons

**Comment by ppbrown** [comment]
So....
the automated tests seem to be failing, for reasons that have nothing to do with my change?

now what?

**Comment by dsavineau** [comment]
you need to amend your commit and add a signoff and the line `Fixes: #4830` inside the commit body (playbook syntax job)
The other job failing is unrelated

**Comment by dsavineau** [comment]
jenkins test centos-container-all_daemons

**Comment by ppbrown** [comment]
huh. I thought "signed-off" would be only for people who have write access.

How's that now?

**Pull request merged**
