### PR TITLE
move when keyword before block keyword

### PR DESCRIPTION
**Pull request by rishabh-d-dave**

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
@guits  @dsavineau 

At many places we have -
```
  when:
      - the only condition
```

Would you too find it better to change all of them to -
```
    when: the only condition
```

**Comment by guits** [comment]
I agree when having only one condition it should be written as you suggest here since the `-` actually means `and`

**Comment by dsavineau** [comment]
+1 too if there's only one condition we shouldn't have a list on the when

**Comment by rishabh-d-dave** [comment]
Cool. I'll go ahead.

**Pull request merged**
