### PR TITLE
code cleaning

### PR DESCRIPTION
**Pull request by guits**
Remove some useless tasks in ceph-docker-common.
(legacy and duplicates)

### CODE REVIEW

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test playbook syntax

**Comment by guits** [comment]
jenkins test playbook syntax

**Comment by leseb** [comment]
Need to verify the backward compatibility with the renaming of the role ceph-docker-common for existing deployment and existing group_vars files.

**Comment by guits** [comment]
@leseb how group_vars files would be impacted?

**Comment by leseb** [comment]
jenkins test playbook syntax

**Comment by leseb** [comment]
jenkins test playbook syntax

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test dev-centos7_cluster

**Comment by leseb** [comment]
jenkins test dev-docker_cluster_collocation

**Comment by leseb** [comment]
jenkins test dev-add_osds

**Comment by leseb** [comment]
jenkins test dev-add_osds_container

**Comment by leseb** [comment]
jenkins test dev-update_cluster

**Comment by leseb** [comment]
jenkins test dev-update_docker_cluster

**Pull request merged**
