### PR TITLE
tests: rename grafana to monitoring

### PR DESCRIPTION
**Pull request by dsavineau**
Since the grafana-server group has been renamed to monitoring then
changing the associated tests.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test centos-non_container-collocation

**Comment by dsavineau** [comment]
jenkins test centos-container-collocation

**Comment by dsavineau** [comment]
jenkins test centos-non_container-all_daemons

**Comment by dsavineau** [comment]
jenkins test centos-container-all_daemons

**Review by guits — APPROVED** [review]

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Pull request merged**
