### PR TITLE
Revert "[TEST] Test setting up correct systemd file for nfs-ganesha"

### PR DESCRIPTION
**Pull request by andymcc**
The nfs-ganesha package has been fixed.

This reverts commit e88af3c4cb314f1f640447ebdce343f0aca85fb4.

### CODE REVIEW

**Comment by leseb** [comment]
The package is not on download.ceph.com yet, so let's wait a bit.

**Comment by leseb** [comment]
@andymcc thanks, let's see if the CI confirms this :)

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-xenial_cluster

**Comment by andymcc** [comment]
Followed up with Ali, the package being installed is the new one from the build log he provided:
https://jenkins.ceph.com/job/nfs-ganesha-stable/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=xenial,DIST=xenial,MACHINE_SIZE=huge/125/consoleFull

That seems to suggest the package wasn't built correctly and didn't include the fix in https://github.com/nfs-ganesha/nfs-ganesha-debian/commit/963b6681dfac459c27c947cb8decc788bc9e5422.

Lets leave this for now, once I get confirmation to try again I'll run another retest.

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by andymcc** [comment]
\o/ much rejoicing

**Pull request merged**
