### PR TITLE
containers: improve logging

### PR DESCRIPTION
**Pull request by guits**
related ceph-container PR: ceph/ceph-container#1408

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1710548

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
job failed because of a vagrant error:
```
dev-ubuntu-container-all_daemons run-test: commands[11] | vagrant destroy --force
[7712] /home/jenkins-build/build/workspace/ceph-ansible-prs-dev-ubuntu-container-all_daemons/tests/functional/all_daemons/container$ /usr/bin/vagrant destroy --force
Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/jenkins-build/.ssh/id_rsa:
Call to virConnectOpen failed: authentication failed: access denied by policy
```

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test dev-centos-non_container-lvm_auto_discovery

**Comment by dsavineau** [comment]
unrelated CI failure

**Pull request merged**
