### PR TITLE
use pre_tasks and post_tasks in shrink-mon.yml too

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
This commit should've been part of commit
2fb12ae55462f5601a439a104a5b0c01929accd9.

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-shrink_mon

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-shrink_mon

**Comment by guits** [comment]
`use pre_tasks and post_tasks in shrink-mds.yml too` => `use pre_tasks and post_tasks in shrink-mon.yml too` ?

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-shrink_mon

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-shrink_mon

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
unrelated CI failure and shrink_mon scenario passed successfully

**Pull request merged**
