### PR TITLE
don't use "include" to include tasks

### PR DESCRIPTION
**Pull request by rishabh-d-dave**

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
retest this please

**Comment by rishabh-d-dave** [comment]
> The way you declare include_tasks statement is not consistent, sometimes you use:
> ```
> - include_tasks:
>  include: checks/check_firewall.yml	    name: checks/check_firewall.yml
> ```

Although I don't see anything like the block above in diff, I think latter is better since it is more succinct. Besides, the above style is syntactically wrong.

Also, I do see a couple of places where I've used the following style which does make me inconsistent  -
```
  - include_tasks:
      name: some.yml
    when: a == b
```
It comes from #3016. I'll replace them with -
```
  - include_tasks: some.yml
      when: a == b
```

**Comment by rishabh-d-dave** [comment]
I see the error copied in the attached file on all CI jobs for this PR.  It looks like an internal error for Vagrant. Do we have a way to circumvent it? And should I report this issue to Vagrant?
[vagrant-internal-error.log](https://github.com/ceph/ceph-ansible/files/2323401/vagrant-internal-error.log)

**Comment by rishabh-d-dave** [comment]
retest this please

**Comment by rishabh-d-dave** [comment]
retest this please

**Comment by rishabh-d-dave** [comment]
I inspected few CI jobs saw that some were failing for reasons besides PR, so I continued the replacing and rebased the PR.

**Comment by rishabh-d-dave** [comment]
retest this please

**Comment by rishabh-d-dave** [comment]
The CI job ceph-ansible-pr-syntax-check failed before the actual test could begin - https://2.jenkins.ceph.com/job/ceph-ansible-pr-syntax-check/3433/

**Comment by rishabh-d-dave** [comment]
retest this please

**Comment by rishabh-d-dave** [comment]
Since most of the CI jobs were passing, I've squashed all the commits to one.

**Comment by rishabh-d-dave** [comment]
retest this please

**Comment by rishabh-d-dave** [comment]
@guits @leseb 
Can you take a look at this PR's CI jobs? The CI fails instantaneously  without running any CI jobs. This wasn't the case few hours ago.

**Comment by guits** [comment]
jenkins test pipeline

**Comment by rishabh-d-dave** [comment]
Thanks.

**Comment by rishabh-d-dave** [comment]
> Since most of the CI jobs were passing, I've squashed all the commits to one.

And I've removed the commit from [this](https://github.com/ceph/ceph-ansible/pull/3016) PR so that either of these commit can go in. IMO, it can be merged.

**Comment by leseb** [comment]
Approving the patch but still, want to discuss that with @guits.
Thanks @rishabh-d-dave for your patience.

**Comment by leseb** [comment]
@rishabh-d-dave thanks for your efforts and patience!

**Comment by guits** [comment]
@rishabh-d-dave thanks for this work 👍

**Comment by rishabh-d-dave** [comment]
Most welcomed and thanks for all the help!  :D

**Pull request merged**
