### PR TITLE
[skip ci] update: gather facts only one time

### PR DESCRIPTION
**Pull request by guits**
this play doesn't need to gather facts from localhost

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-container-update

**Review by dsavineau — APPROVED** [review]

**Comment by dsavineau** [comment]
jenkins test centos-non_container-update

**Comment by dsavineau** [comment]
jenkins test centos-container-update

**Pull request merged**
