### PR TITLE
purge-cluster: do not use sudo when checking if ceph-volume exists

### PR DESCRIPTION
**Pull request by andrewschoen**
On Ubuntu systems you can not use sudo with `command`.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1656935

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
Another option would be to use ``which``, we use that already with success here: https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/purge-cluster.yml#L261

**Comment by guits** [comment]
jenkins test dev-ubuntu-non_container-all_daemons

**Comment by guits** [comment]
dev-ubuntu-non_container-all_daemons won't pass CI until #3554 is merged

**Comment by guits** [comment]
jenkins test dev-ubuntu-non_container-all_daemons

**Comment by guits** [comment]
jenkins test dev-ubuntu-non_container-purge

**Comment by andrewschoen** [comment]
jenkins test pipeline

**Comment by guits** [comment]
Closing in favor of #3662

**Pull request closed without merging**
