### PR TITLE
remove configuration files for ceph packages on ubuntu clusters

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
For apt-get, purge command needs to be used, instead of remove command,
to remove related configuration files. Otherwise, packages might be
shown as installed while running dpkg command even after removing them.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1640061
Signed-off-by: Rishabh Dave <ridave@redhat.com>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
jenkins test luminous-xenial_cluster

**Comment by rishabh-d-dave** [comment]
jenkins test luminous-xenial_cluster

**Comment by rishabh-d-dave** [comment]
Since the scenario xenial_cluster did not get triggered, I ran it myself locally and then ran `purge-cluster.yml` to test if the PR works. I've copied that output of executing `purge-cluster.yml` to the file attached to this comment.

[purge-cluster.log](https://github.com/ceph/ceph-ansible/files/2539091/purge-cluster.log)

**Comment by rishabh-d-dave** [comment]
Packages in `ceph_packages_remaining`](https://github.com/rishabh-d-dave/ceph-ansible/blob/pass-list-instead-of-repeating/infrastructure-playbooks/purge-cluster.yml#L509) can't have configuration files, right?

**Comment by leseb** [comment]
@rishabh-d-dave right

**Pull request merged**
