### PR TITLE
Fix daemon socket checks

### PR DESCRIPTION
**Pull request by rossmartyn04**
Where there are multiple socket paths, i.e OSDs, the paths are aggregated into one long string due to the --printf option for the stat tool.

This replaces the option with --format which correctly formats the output into multiple lines. For completeness this change has been applied to every check.

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-external_clients

**Comment by guits** [comment]
jenkins test centos-container-lvm_batch

**Comment by guits** [comment]
jenkins test centos-container-ooo_collocation

**Comment by guits** [comment]
jenkins test centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-all_in_one

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by rossmartyn04** [comment]
I'm not sure I was supposed to do here, can we re-open this?

**Comment by dsavineau** [comment]
> I'm not sure I was supposed to do here, can we re-open this?

If you saw guits message then you need to amend your commit and add a sign-off

https://docs.ceph.com/ceph-ansible/master/dev/index.html#submit-a-patch
https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by guits** [comment]
@rossmartyn04 UP :slightly_smiling_face:

**Comment by rossmartyn04** [comment]
Recreated this PR as my repo got into a bit of a mess. Apologies!

https://github.com/ceph/ceph-ansible/pull/5391

**Pull request closed without merging**
