### PR TITLE
Skip GPT header creation for lvm osd scenario

### PR DESCRIPTION
**Pull request by vishalkanaujia**
commit 5429ada53399ef72bd3ba450a9bab55069b5aab2 (HEAD -> wip_lvm_bluestore, origin/wip_lvm_bluestore)
Author: Vishal Kanaujia <vishal.kanaujia@flipkart.com>
Date:   Wed May 16 15:28:31 2018 +0530

    Skip GPT header creation for lvm osd scenario
    https://github.com/ceph/ceph-ansible/issues/2592

    Signed-off-by: Vishal Kanaujia <vishal.kanaujia@flipkart.com>

### CODE REVIEW

**Comment by vishalkanaujia** [comment]
@leseb @guits:  done

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-lvm_osds

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-bluestore_osds_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Pull request merged**
