### PR TITLE
config: fix monitor_interface when not passed in the inventory file | osd:  fix old jewel container activation

### PR DESCRIPTION
**Pull request by leseb**
Setting monitor_interface in group_vars/all.yml makes the
hostvars[host]['monitor_interface'] non-existing.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1507922
Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
This PR is fixing two separate bugs now, want to re-title?

**Comment by leseb** [comment]
@ktdreyer done.

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by GregMeno** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Pull request merged**
