### PR TITLE
yamellinting ceph-ansible

### PR DESCRIPTION
**Pull request by DO1JLR**
Hello :wave: 

A very fancy ansible, this ceph-ansible. thanks a lot for this. :heart: 

After noticing a few trailing whitespaces, I noticed that there is no yamllinting here yet. This pull request might change that.

Maybe you like it? :kissing_heart: if you have other yamllinting preferences, I'll be happy to adjust it a bit. :wink:

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-collocation

**Comment by DO1JLR** [comment]
I am not sure why the ``centos-container-collocation`` is failing. If there is anything I can help to fix it, please give me a hint :heart_decoration:

**Comment by guits** [comment]
except for the extra spaces in `vagrant_variables.yml` files, that looks good to me.

thanks for this pr @DO1JLR

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Comment by DO1JLR** [comment]
:grey_question: is there anything I can do to help merge this pull request? :innocent:

**Comment by DO1JLR** [comment]
@guits  is there anything I can do to help merge this pull request? :innocent:

**Pull request closed without merging**
