### PR TITLE
ceph-config: do not use osds_per_device literally

### PR DESCRIPTION
**Pull request by andrewschoen**
Fixes: https://github.com/ceph/ceph-ansible/issues/3135

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
So this is not going to work at all. The ceph.conf file is needed to define journal sizing, and it is optional in bluestore for block.db sizing. The command is still wrong because --filestore needs to be passed in and it isn't.

At this point I would recommend to do a "best guess" of number of OSDs should be roughly the length of `devices`

**Comment by alfredodeza** [comment]
@neha-ojha @jdurgin would it be OK to default here to the number of devices to infer the number of OSDs? The caveat being that 10 HDDs and 1 SSD would produce 9 OSDs, not 11.

**Comment by andrewschoen** [comment]
> @neha-ojha @jdurgin would it be OK to default here to the number of devices to infer the number of OSDs? The caveat being that 10 HDDs and 1 SSD would produce 9 OSDs, not 11.

The only solution I can think of here that might be more accurate is to write a temporary ceph.conf and then point the ``ceph-volume`` command at it so we could retrieve the number of OSDs and then use that information to render the correct configuration file. This might be too much of a hassle though.

**Comment by andrewschoen** [comment]
For now I think the best solution is to count ``devices`` and multiply by ``osds_per_devices`` for a best guess estimate. We've cut http://tracker.ceph.com/issues/36088 to add functionality into ``ceph-volume`` that will allow us to get the number of osds without the need for a ceph.conf. Once that's complete we can change things here.

This branch is now passing ceph-volume tests again: https://jenkins.ceph.com/job/ceph-volume-scenario/951

**Comment by neha-ojha** [comment]
@andrewschoen @alfredodeza sounds good to me.

**Pull request merged**
