### PR TITLE
WIP: infra: add playbook to prepare multiple osds on a single device

### PR DESCRIPTION
**Pull request by leseb**
Not sure if it's the right approach yet.

Closes: #1064

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
jenkins test this please

**Comment by andrewschoen** [comment]
jenkins test this please

**Comment by acomisario** [comment]
can we merge this ? is an even more used scenario every day.

**Comment by leseb** [comment]
@acomisario I didn't have the time to work on this recently. I might resume this at some point, just not sure when...

**Comment by leseb** [comment]
Closing in favour of https://github.com/ceph/ceph-ansible/pull/2233

**Pull request closed without merging**
