### PR TITLE
requirements: update ansible requirements

### PR DESCRIPTION
**Pull request by SvenMW**
Signed-off-by: Sven Kieske <s.kieske@mittwald.de>

### CODE REVIEW

**Comment by SvenMW** [comment]
local testing indicates this is not enough to fix this.

I'm not deeply familiar with ansible modules but it seems it is not enough to install ansible.posix.

ansible still complains with the same error that it can't resolve module/action `selinux_permissive`

**Comment by dsavineau** [comment]
the `selinux_permissive` module is part of the `community.general` ansible collection [1]

So you probably wants to have the same collection than the main branch [2]

[1] https://github.com/ansible-collections/community.general/blob/main/plugins/modules/system/selinux_permissive.py
[2] https://github.com/ceph/ceph-ansible/blob/main/requirements.yml#L9-L10

**Comment by SvenMW** [comment]
Thanks for the hint! I was mistaken by the module "selinux" inside ansible.posix, which does different things than selinux_permissive, it seems..

**Comment by guits** [comment]
there's something unclear to me. I might be missing something but actually, I'm unsure what's the issue, @SvenMW 

With `ansible>=2.10,<2.11,!=2.9.10` we can see ansible-base 2.10.17 is pulled and seems to come with `community.general` and `ansible.posix` already (see the 'Skipping' messages at the end of this log).

```
[2347017] /home/jenkins-build/build/workspace/ceph-ansible-prs-centos-container-lvm_batch$ /tmp/venv.9CrzAIGvhS/centos-container-lvm_batch/bin/python -m pip freeze >../../../../../tmp/venv.9CrzAIGvhS/centos-container-lvm_batch/log/centos-container-lvm_batch-2.log
centos-container-lvm_batch installed: ansible==2.10.7,ansible-base==2.10.17,attrs==22.1.0,cffi==1.15.1,coverage==6.4.2,cryptography==37.0.4,execnet==1.9.0,iniconfig==1.1.1,Jinja2==3.1.2,jmespath==1.0.1,MarkupSafe==2.1.1,mock==4.0.3,netaddr==0.8.0,packaging==21.3,pluggy==1.0.0,py==1.11.0,pycparser==2.21,pyparsing==3.0.9,pytest==7.1.2,pytest-cov==3.0.0,pytest-forked==1.4.0,pytest-rerunfailures==10.2,pytest-testinfra==6.8.0,pytest-xdist==2.5.0,PyYAML==6.0,six==1.16.0,testinfra==6.0.0,tomli==2.0.1
centos-container-lvm_batch run-test-pre: PYTHONHASHSEED='591985680'
centos-container-lvm_batch run-test: commands[0] | ansible-galaxy install -r /home/jenkins-build/build/workspace/ceph-ansible-prs-centos-container-lvm_batch/requirements.yml -v
[2347018] /home/jenkins-build/build/workspace/ceph-ansible-prs-centos-container-lvm_batch/tests/functional/lvm-batch/container$ /tmp/venv.9CrzAIGvhS/centos-container-lvm_batch/bin/ansible-galaxy install -r /home/jenkins-build/build/workspace/ceph-ansible-prs-centos-container-lvm_batch/requirements.yml -v
Using /home/jenkins-build/build/workspace/ceph-ansible-prs-centos-container-lvm_batch/ansible.cfg as config file
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Skipping 'ansible.utils' as it is already installed
Skipping 'community.general' as it is already installed
Skipping 'ansible.posix' as it is already installed

```

**Comment by SvenMW** [comment]
mhm, in my case I'm manually installing `pip install ansible-base==2.10`

**Comment by guits** [comment]
I think what we see in the CI is misleading because collections aren't installed in an isolated environment. Once a collection is installed then it's available for any new job.

**Comment by guits** [comment]
I think we need something like this #7264

**Comment by guits** [comment]
> > I think we need something like this #7264
> 
> this linked PR does not address the issue of an incomplete requirements.yml file as afaik proven by me in [my previous comment ](https://github.com/ceph/ceph-ansible/pull/7262#issuecomment-1199035420)

This linked PR has never been intended for fixing the initial issue you reported.

**Comment by guits** [comment]
@SvenMW can you rebase onto stable-6.0? thanks!

**Comment by guits** [comment]
jenkins test centos-container-lvm_batch

**Comment by guits** [comment]
the errors seen are unrelated. I've tested manually, so I'm merging this as it is.

**Pull request merged**
