### PR TITLE
Lint yaml

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test dev-centos7_cluster

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-centos7_cluster

**Comment by leseb** [comment]
jenkins test luminous-docker_cluster

**Comment by guits** [comment]
unrelated failures

**Comment by alfredodeza** [comment]
This PR has broken all Debian/Ubuntu development deployments because the handler isn't executed after the development repo is added. This means that when attempting to install a development version of Ceph in Ubuntu, we will see 10.2.10 being installed

**Pull request merged**
