### PR TITLE
Revert "tests: disable nfs-ganesha deployment"

### PR DESCRIPTION
**Pull request by dsavineau**
This reverts commit 83940e624bc4faf6bc7bb1a7637711556d6b3e8c.

Because nfs-ganesha@master (2.9-dev) build has been fixed by [1] then
we can test nfs-ganesha in the CI for master/octopus.

[1] https://github.com/ceph/ceph-build/pull/1346

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
> we can test nfs-ganesha in the CI for master/octopus.

until next breakage :rofl:

**Pull request merged**
