### PR TITLE
[skip ci] collocated.yml: adding --rm just to remove the container used to prep…

### PR DESCRIPTION
**Pull request by jadebustos**
collocated.yml: adding --rm just to remove the container used to prepare the osd.

When add-osd.yml is used to add a new osd after an osd failure the execution of the playbook fails. The problem is that the container used to prepare the failed osd still exits (ceph-osd-prepare-ceph3-bs-vdb container for osd vdb). After deleting that container running the playbook again adds the new osd to the cluster.

Replacing a failed osd with a new one works fine with lvm but not using collated osds. This fix works with collocated scenario.

Fixes: #4041

Signed-off-by: Jose Angel de Bustos Perez <jadebustos@gmail.com>

### CODE REVIEW

**Comment by guits** [comment]
@jadebustos, as @dsavineau mentioned [here](https://github.com/ceph/ceph-ansible/issues/4041#issuecomment-497803956) this playbook isn't intended to replace an OSD.

by the way, this patch might break upgrades

**Comment by dLobatog** [comment]
@guits How can this break upgrades? The docker container used to add the OSD should only run once, even in the `add` use case (not replace) what is the point of keeping the container?

**Comment by dsavineau** [comment]
@dLobatog probably because the container prepare is used later https://github.com/ceph/ceph-ansible/blob/stable-3.2/roles/ceph-osd/templates/ceph-osd-run.sh.j2#L28-L32

**Comment by guits** [comment]
> @dLobatog probably because the container prepare is used later https://github.com/ceph/ceph-ansible/blob/stable-3.2/roles/ceph-osd/templates/ceph-osd-run.sh.j2#L28-L32

exactly

**Pull request closed without merging**
