### PR TITLE
Backport of 2593 in stable-3.0

### PR DESCRIPTION
**Pull request by leseb**
Backport of #2593 in stable-3.0

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1582181

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-lvm_osds

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-lvm_osds

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-lvm_osds

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-lvm_osds

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-lvm_osds

**Comment by djgalloway** [comment]
jenkins test pipeline

**Comment by djgalloway** [comment]
@leseb Can you merge https://github.com/ceph/ceph-build/pull/1060 then rebase here so we can test pipeline through completion?

**Comment by leseb** [comment]
@djgalloway done.

**Comment by djgalloway** [comment]
jenkins test luminous-ansible2.4-bluestore_osds_container

**Comment by djgalloway** [comment]
Welp a sub-job in the pipeline failed (will fail).  I restarted it in a separate job.

**Pull request merged**
