### PR TITLE
DNM: test

### PR DESCRIPTION
**Pull request by guits**

### CODE REVIEW

**Comment by guits** [comment]
jenkins test all

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-bluestore_dmcrypt_journal

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-update_dmcrypt

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-docker_dedicated_journal

**Comment by leseb** [comment]
in favor of https://github.com/ceph/ceph-ansible/pull/2014

**Pull request closed without merging**
