### PR TITLE
ceph-aio-no-vagrant.sh: check if ansible is installed

### PR DESCRIPTION
**Pull request by leseb**
Since we don't provide install-ansible.sh anymore we just check if it
exists. If not we fail and ask for installation.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
It looks like there are more things going on in this commit?

**Comment by leseb** [comment]
@ktdreyer yes some shell lint, want me to separate the commits?

**Comment by ktdreyer** [comment]
It's ok to leave this PR as is to keep it moving.

I think the future it would be great to break these out so it's easier to review and bisect.

**Comment by leseb** [comment]
@ktdreyer sure, thanks!

**Pull request merged**
