### PR TITLE
backport: Retry osd disk prep to workaround race condition

### PR DESCRIPTION
**Pull request by guits**
backport of #1531

### CODE REVIEW

**Comment by andrewschoen** [comment]
@guits is there a corresponding BZ for this? If so would you please list it here?

We can't backport this unless QE has ack'd the corresponding BZ.

**Comment by leseb** [comment]
@andrewschoen https://bugzilla.redhat.com/show_bug.cgi?id=1451802

**Comment by ktdreyer** [comment]
That BZ is targeted at RHSCON 3 and lacks "Steps to Reproduce:",  "Actual results:", and "Expected results:". Without that information, the QE team is probably not going to ack the bug.

**Comment by guits** [comment]
Hi Ken,

that issue is related to a race condition. The random behavior makes it
pretty difficult to give an exact procedure to reproduce that issue.

Erwan pushed a patch on ceph-disk: https://github.com/ceph/ceph/commit/
93e7b95ed8b4c78daebf7866bb1f0826d7199075 perhaps this commit can give more
context to fill the BZ?



*Guillaume Abrioux*Software Engineer


*PHONE : *+33 (0)1 49 70 96 2 <callto:+33%20%280%291%2049%2070%2086%2026>1
*ADDRESS :* 11 bis rue roquépine, Paris 75008

2017-05-17 21:54 GMT+02:00 Ken Dreyer <notifications@github.com>:

**Comment by guits** [comment]
Hi Ken,

that issue is related to a race condition. The random behavior makes it pretty difficult to give an exact procedure to reproduce that issue.

Erwan pushed a patch on ceph-disk: https://github.com/ceph/ceph/commit/93e7b95ed8b4c78daebf7866bb1f0826d7199075 perhaps this commit can give more context to fill the BZ?

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-docker_dmcrypt_journal_collocation

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Comment by guits** [comment]
jenkins test kraken-ansible2.2-dmcrypt_journal_collocation

**Comment by guits** [comment]
jenkins test kraken-ansible2.2-docker_cluster

**Comment by guits** [comment]
jenkins test kraken-ansible2.2-update_cluster

**Comment by leseb** [comment]
kraken-ansible2.2-update_cluster fix here: https://github.com/ceph/ceph-ansible/pull/1492 with backport here: https://github.com/ceph/ceph-ansible/pull/1550

will rebase on stable-2.2 once https://github.com/ceph/ceph-ansible/pull/1550 passes.

**Comment by leseb** [comment]
jenkins test kraken-ansible2.2-docker_cluster

**Comment by leseb** [comment]
We won't be able to fix this through ceph-ansible, we already have a fix in ceph-disk that is upstream and is been backported for both kraken and jewel.
Closing this and reverting #1531 in https://github.com/ceph/ceph-ansible/pull/1551

**Pull request closed without merging**
