### PR TITLE
Change docker_container parameter network to network_mode

### PR DESCRIPTION
**Pull request by gregoryo2014**
Addressing "populate kv_store with custom ceph.conf":
Unsupported parameters for (docker_container) module. Looking at
https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
shows that the correct parameter is network_mode, not network.

### CODE REVIEW

**Comment by dsavineau** [comment]
Do we have a BZ for that one ?

**Comment by gregoryo2014** [comment]
> Do we have a BZ for that one ?

What's a BZ?

**Comment by gregoryo2014** [comment]
> Add a sign-off to your commit. Committing to stable-3.2 is acceptable since that code disappeared from master.

Sorry I missed the -s before - my change was so small I didn't go in search of the contrib guidelines. Read now... what exactly am I agreeing to?
My git-foo is not terribly strong. Maybe `git commit --amend -s` would have worked, but now there's another later commit and mine is no longer last. I clicked "Update branch" here in the web interface, but not sure what to do next. Can you tell me what to do?

**Comment by guits** [comment]
no BZ required for that

**Comment by dsavineau** [comment]
@gregoryo2014 you just need to rebase your branch on top of the current stable-3.2 and amend your commit to add the sign-off

**Comment by gregoryo2014** [comment]
Conceptually this seems straightforward, but the commands escape me. Delete, re-fork, change again, PR. Easy.

**Pull request closed without merging**
