### PR TITLE
rhcs: drop debian support

### PR DESCRIPTION
**Pull request by dsavineau**
Support for debian with RHCS has been dropped starting RHCS 4

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test centos-container-podman

**Comment by dsavineau** [comment]
jenkins test centos-container-podman

**Comment by dsavineau** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by dsavineau** [comment]
jenkins test centos-non_container-all_daemons

**Comment by dsavineau** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
should be added to release note (#5204)

**Pull request merged**
