### PR TITLE
tests: fix docker_collocation, change jewel upgrade

### PR DESCRIPTION
**Pull request by guits**
fix docker_collocation, change jewel upgrade

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-update_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-docker_cluster

**Pull request merged**
