### PR TITLE
Using config_template

### PR DESCRIPTION
**Pull request by leseb**
Thanks to @cloudnull great patch at
https://github.com/ansible/ansible/pull/12555
we now have the ability to add more configuration options instead of
having to push a PR to add a new option to the template. So you can
dynamically add and remove flags.

To use it, edit `ceph_conf_overrides` in `group_vars/all` like so:

```
ceph_conf_overrides
 global:
     foo: 12345
     bar: 6789
```

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
@cloudnull while trying to add new values, I'm getting the following error: http://pastebin.com/bx248qVv
Any inputs would be appreciated, thanks :)

**Comment by leseb** [comment]
hum looks like 'indent' are not supported/compliant with the INI style format...

**Comment by leseb** [comment]
Sorry for everyone using the module already. This will likely perform a restart of the cluster while running the playbook again since the structure of the `ceph.conf` will change. One thing to do is to remove all the indent from the `ceph.conf`.

**Comment by cloudnull** [comment]
@leseb Just following up, I've been on holiday for the past little bit. While it seems like all is well I wanted to follow up to make. Was everything figured out regarding the `config_template`?

**Comment by leseb** [comment]
@cloudnull Hey! No worries, thanks for catching up :). Yes once I figured the indent issue everything went smooth. Thanks again for this module. Hopefully it'll get merged next early next year.

**Pull request merged**
