### PR TITLE
testing: changes to allow for concurrent functional tests

### PR DESCRIPTION
**Pull request by andrewschoen**

### CODE REVIEW

**Comment by andrewschoen** [comment]
test this please

**Comment by andrewschoen** [comment]
One clean test, lets try again.

**Comment by andrewschoen** [comment]
test this please

**Comment by alfredodeza** [comment]
test this please

**Comment by alfredodeza** [comment]
test this please

**Comment by andrewschoen** [comment]
test this please

**Comment by andrewschoen** [comment]
This should be all the changes needed to allow for multiple tests to run at once and avoid libvirt collisions.

**Pull request merged**
