### PR TITLE
don't use private option for import_role

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Since variable sharing has been made default for roles, private option
has been deprecated; so stop using it.

Signed-off-by: Rishabh Dave <ridave@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
Please wait for https://github.com/ceph/ceph-ansible/pull/3325

**Comment by rishabh-d-dave** [comment]
Thanks for letting me know. :)

**Comment by leseb** [comment]
@rishabh-d-dave default for role in which ansible version?

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave default for role in which ansible version?

According to Ansible docs, it is so since version 2.6. But I am quite sure that this wasn't the case with 2.6, since I and Andrew Schoen, both, were seeing trouble with variable sharing before 2.7 was released.

**Comment by leseb** [comment]
@rishabh-d-dave please rebase :)

**Comment by rishabh-d-dave** [comment]
That is precisely what I was upto.  :)

**Comment by leseb** [comment]
@rishabh-d-dave sorry again, it seems you will need https://github.com/ceph/ceph-ansible/pull/3412 for switch to pass.

**Comment by rishabh-d-dave** [comment]
@leseb Thanks for informing me. I'll wait.

**Comment by leseb** [comment]
One more patch :) https://github.com/ceph/ceph-ansible/pull/3419

**Comment by leseb** [comment]
jenkins test pipeline

**Pull request merged**
