### PR TITLE
tox: Don't copy infrastructure playbook

### PR DESCRIPTION
**Pull request by dsavineau**
Since a1a871c we don't need to copy the infrastructure playbooks
under the ceph-ansible root directory.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by rishabh-d-dave** [comment]
I think we must also test `add_osds` and `add_mons` on CI for this PR, since these scenarios depend on a playbook in `infrastructure-playbooks/`

**Comment by guits** [comment]
jenkins test dev-centos-non_container-update

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
unrelated failure, merging it anyway

**Pull request merged**
