### PR TITLE
rgw: don't create user on secondary zones

### PR DESCRIPTION
**Pull request by dsavineau**
The rgw user creation for the Ceph dashboard integration shouldn't be
created on secondary rgw zones.

Closes: #4707
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1794351

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by dsavineau** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
@dsavineau is there a BZ for this?

**Comment by dsavineau** [comment]
@guits no only a github issue

**Comment by dsavineau** [comment]
jenkins test centos-container-rgw_multisite

**Comment by dsavineau** [comment]
jenkins test centos-non_container-rgw_multisite

**Comment by dsavineau** [comment]
jenkins test centos-container-all_in_one

**Comment by dsavineau** [comment]
jenkins test centos-non_container-all_in_one

**Comment by dsavineau** [comment]
jenkins test centos-non_container-all_daemons

**Comment by dsavineau** [comment]
jenkins test jenkins test centos-container-all_in_one

**Comment by dsavineau** [comment]
jenkins test jenkins test centos-container-all_in_one

**Comment by dsavineau** [comment]
jenkins test centos-container-all_in_one

**Comment by dsavineau** [comment]
jenkins test centos-container-all_in_one

**Comment by dsavineau** [comment]
jenkins test centos-non_container-all_daemons

**Comment by dsavineau** [comment]
We need https://github.com/ceph/ceph-ansible/pull/5046 first to be able to run the CI

**Comment by guits** [comment]
jekins test centos-container-rgw_multisite

**Comment by guits** [comment]
jenkins test centos-container-rgw_multisite

**Pull request merged**
