### PR TITLE
stable-2.2: Eliminate RGW NFS

### PR DESCRIPTION
**Pull request by fghaas**
As evident from the discussion in #1907, it doesn't make much sense to keep the RGW NFS configuration around in the `stable-2.2` branch. Thus:

- Eliminate the RGW FSAL stanza from the `ganesha.conf` template
- Drop the `nfs_obj_gw` variable and all references
- Drop the (now-unused) remaining `ceph_nfs_rgw*` variables

This isn't intended to be merged as-is, just to give @alimaredia options to choose from as discussed in #1907.

### CODE REVIEW

**Comment by alimaredia** [comment]
@fghaas I'm inclined to merge all the commits, I don't see any harm in any of them. However, I would rather let @leseb be the final call. 

Since The automated testing doesn't work her on jenkins I want to at least have his input before merging anything.

**Comment by fghaas** [comment]
@alimaredia Sure, no problem at all.

**Comment by alimaredia** [comment]
@fghaas knit, these two comments should be removed:

https://github.com/fghaas/ceph-ansible/blob/1907/group_vars/nfss.yml.sample#L26

https://github.com/fghaas/ceph-ansible/blob/1907/roles/ceph-nfs/defaults/main.yml#L18

**Comment by fghaas** [comment]
@alimaredia Done, also rebased on current `stable-2.2`.

**Comment by leseb** [comment]
@alimaredia feel free to merge if you feel it's good.

**Comment by alimaredia** [comment]
lgtm

**Comment by alfredodeza** [comment]
How is it possible that this got merged with 0 tests passing out of 31? 

* Does this even work on stable-2.2?
* what is the explanation on merging without CI passing?

**Comment by guits** [comment]
@alfredodeza I think this obviously doesn't work on stable-2.2 because [this](https://github.com/ceph/ceph-ansible/pull/1935/files#diff-4fa370989543a95c8cc72971e1e4fdae) has been removed while [this](https://github.com/ceph/ceph-ansible/blob/gmeno-stable-2.2/roles/ceph-rgw/tasks/docker/main.yml#L42) hasn't.
As you mentioned, this should have been caught with CI testing.

**Comment by fghaas** [comment]
@alfredodeza As it happens, I did create #1927 (before this one) in which I pointed out that the automated Jenkins testing was unreliable, and that that was a problem particularly for occasional contributors like me. Basically, all contributions that I made recently failed CI one way or another, because the CI was (is?) itself in a problematic state, and I was also told that `stable-2.2` isn't being CI-tested at all.

**Comment by alfredodeza** [comment]
@fghaas the testing for ceph-ansible does not depend exclusively on Jenkins at all.

It was created to be able to run anywhere. It is entirely possible to run tests locally. This is very well documented here http://docs.ceph.com/ceph-ansible/master/testing/index.html and more specifically here http://docs.ceph.com/ceph-ansible/master/testing/running.html

I am not particularly placing you against the failures this has caused, but rather, I would like to see the leads to be able to verify things when contributors that might not know about details on how to properly test this, to thoroughly test/review/verify and to point the right way as to how to test things for the project.

Lastly, even if there was no CI at all, the questions are still valid, and should be commented/addressed before merging in such a state:

* Does this patch work? (any output with verifiable content could do)
* What is the explanation on merging a patch that fails everything

**Comment by fghaas** [comment]
@alfredodeza Yup, sorry, I was entirely unaware of the alternate testing option and did my testing, as best as I knew, on a reference Ceph cluster. Would have been happy to post output if someone had asked to review, but didn't think to do that myself — apologies for that.

**Pull request merged**
