### PR TITLE
tests: use nfs/mds instead of nfs/rgw

### PR DESCRIPTION
**Pull request by guits**
needed for the update job in stable-6.0 branch.
the upgrade from either nautilus or octopus to pacific isnt supported
when nfs/rgw is deployed.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-container-all_in_one

**Comment by guits** [comment]
jenkins test centos-non_container-collocation

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-all_in_one

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by djgalloway** [comment]
jenkins test centos-container-collocation

**Comment by djgalloway** [comment]
jenkins test centos-container-update

**Comment by djgalloway** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by djgalloway** [comment]
jenkins test centos-non_container-purge

**Comment by djgalloway** [comment]
jenkins test centos-non_container-all_daemons

**Comment by djgalloway** [comment]
centos-non_container-purge looks like a legit failure

```
=================================== FAILURES ===================================
________ TestNFSs.test_nfs_ganesha_package_is_installed[ansible://nfs0] ________
[gw3] linux -- Python 3.6.4 /tmp/venv.FpBxwJcwYi/centos-non_container-purge/bin/python

self = <test_nfs_ganesha.TestNFSs object at 0x7fabaa63a240>
node = {'ceph_release_num': {'dev': 99, 'jewel': 10, 'kraken': 11, 'luminous': 12, ...}, 'ceph_stable_release': 'octopus', 'docker': None, 'nfs_file_gw': True, ...}
host = <testinfra.host.Host object at 0x7fabaace69e8>

    @pytest.mark.no_docker
    def test_nfs_ganesha_package_is_installed(self, node, host):
        if node['nfs_file_gw']:
            pkg = ['nfs-ganesha-ceph', 'nfs-ganesha-rados-grace']
        else:
            pkg = ['nfs-ganesha', 'nfs-ganesha-rgw']
>       assert host.package(pkg).is_installed

../tests/nfs/test_nfs_ganesha.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/tmp/venv.FpBxwJcwYi/centos-non_container-purge/lib/python3.6/site-packages/testinfra/modules/package.py:151: in is_installed
    return self.run_test("rpm -q %s", self.name).rc == 0
/tmp/venv.FpBxwJcwYi/centos-non_container-purge/lib/python3.6/site-packages/testinfra/host.py:94: in run_test
    return self.run_expect([0, 1], command, *args, **kwargs)
/tmp/venv.FpBxwJcwYi/centos-non_container-purge/lib/python3.6/site-packages/testinfra/host.py:75: in run
    return self.backend.run(command, *args, **kwargs)
/tmp/venv.FpBxwJcwYi/centos-non_container-purge/lib/python3.6/site-packages/testinfra/backend/ansible.py:45: in run
    command = self.get_command(command, *args)
/tmp/venv.FpBxwJcwYi/centos-non_container-purge/lib/python3.6/site-packages/testinfra/backend/base.py:186: in get_command
    command = self.quote(command, *args)
/tmp/venv.FpBxwJcwYi/centos-non_container-purge/lib/python3.6/site-packages/testinfra/backend/base.py:176: in quote
    return command % tuple(pipes.quote(a) for a in args)
/tmp/venv.FpBxwJcwYi/centos-non_container-purge/lib/python3.6/site-packages/testinfra/backend/base.py:176: in <genexpr>
    return command % tuple(pipes.quote(a) for a in args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = ['nfs-ganesha-ceph', 'nfs-ganesha-rados-grace']

    def quote(s):
        """Return a shell-escaped version of the string *s*."""
        if not s:
            return "''"
>       if _find_unsafe(s) is None:
E       TypeError: expected string or bytes-like object

/usr/lib64/python3.6/shlex.py:314: TypeError
```

**Comment by djgalloway** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test <centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Pull request merged**
