### PR TITLE
cephadm-adopt: check for version only once in containerized_deployment

### PR DESCRIPTION
**Pull request by clwluvw**
Based on running container on the same image for all hosts it can be done with one host

Signed-off-by: Seena Fallah <seenafallah@gmail.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
> Based on running container on the same image for all hosts it can be done with one host

The task is done for both containerized and non containerized deployment so you're breaking the current workflow.

Also using `run_once: true` doesn't make sense since this task aims to check all nodes and not just one.

There no guarantee that you have the same image on all nodes. You can have an environment with nodes which were not upgrade so using `run_once: true` will hides this behaviour

**Comment by clwluvw** [comment]
@dsavineau You are not checking each container in hosts and you just running the same container on all hosts and get the same result as you can see the command in task:
```
ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag
```

This is redundant and with this PR this can be efficient!

**Comment by dsavineau** [comment]
> @dsavineau You are not checking each container in hosts and you just running the same container on all hosts and get the same result as you can see the command in task:
> 
> ```
> ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag
> ```
> 
> This is redundant and with this PR this can be efficient!

```console
$ cat group_vars/*.yml
---
ceph_docker_registry: quay.io
ceph_docker_image: ceph/daemon
ceph_docker_image_tag: latest-master
...
---
ceph_docker_registry: quay.io
ceph_docker_image: ceph/daemon
ceph_docker_image_tag: latest-master-fix_issue_42
...
```

How do you deal with different container images then ?

**Comment by clwluvw** [comment]
@dsavineau Yes, I didn't remember this situation. You are right!

**Pull request closed without merging**
