### PR TITLE
[skip ci] Revert "disable nfs scenario"

### PR DESCRIPTION
**Pull request by leseb**
This reverts commit a502327e52b2577a721790fce1cdc5e3201678bf.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
Run, this periodically until the packages are fixed.

**Comment by guits** [comment]
I think we can close this one?

**Comment by leseb** [comment]
No, the idea is to not forget about this so when we see it we run it to see if the repos have been fixed.

**Comment by dsavineau** [comment]
This has been handle in 27aad73

**Pull request closed without merging**
