### PR TITLE
rgw: Add default quota configs

### PR DESCRIPTION
**Pull request by clwluvw**
Add user max size and user max objects and bucket max size quota config to ceph conf

Signed-off-by: Seena Fallah <seeenafallah@gmail.com>

### CODE REVIEW

**Comment by guits** [comment]
Hi @clwluvw 

please, take a look at the documentation [1].

> We will no longer accept pull requests that modify the ceph.conf template unless it helps the deployment. For simple configuration tweaks please use the ceph_conf_overrides variable.

[1] https://github.com/ceph/ceph-ansible/blob/master/docs/source/index.rst#cephconf-configuration-file

**Comment by clwluvw** [comment]
@guits But why the `max_objects` is defined and `max_size` isn't defined? Isn't that inconsistency?

**Comment by guits** [comment]
this was added before we decided to stop modifying ceph.conf.j2 and was probably kept for backward compatibility concerns.

**Comment by clwluvw** [comment]
@guits Makes sense but if we could add these too the quota default section for ansible would be complete :)

**Comment by clwluvw** [comment]
@guits Makes sense but if we could add these too the quota default section for ansible would be complete :)
Now the ansible config gets dirty because one of is in `ceph_conf_overrides` the other isn't.

**Comment by guits** [comment]
> @guits Makes sense but if we could add these too the quota default section for ansible would be complete :)
> Now the ansible config gets dirty because one of is in `ceph_conf_overrides` the other isn't.

In fact, I would do the opposite: I would deprecate and remove what we've left in the ceph.conf.j2 so we keep consistency.

**Comment by clwluvw** [comment]
> > @guits Makes sense but if we could add these too the quota default section for ansible would be complete :)
> > Now the ansible config gets dirty because one of is in `ceph_conf_overrides` the other isn't.
> 
> In fact, I would do the opposite: I would deprecate and remove what we've left in the ceph.conf.j2 so we keep consistency.

Yes it fully depends on you. I think if we keep consistency here it would be so better in our ansible config.

**Pull request closed without merging**
