### PR TITLE
[skip ci] DNM - Testing tripleo train branch with ceph-ansible

### PR DESCRIPTION
**Pull request by arxcruz**
Depends-On: https://review.rdoproject.org/r/#/c/23896/

### CODE REVIEW

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by javierpena** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Pull request closed without merging**
