### PR TITLE
osd: Fixed bug in regular expression in restart_osd_daemon.sh

### PR DESCRIPTION
**Pull request by artur-fijalkowski**
OSDs can have numbers >99 which means regular expression in `restart_osd_daemon.sh` should catch OSD number of any non-zero length.

This solves https://github.com/ceph/ceph-ansible/issues/2964
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1612853

### CODE REVIEW

**Comment by artur-fijalkowski** [comment]
@guits Is it OK now?

I feel a little bit lost right now...

**Comment by guits** [comment]
@artur-fijalkowski 
almost there! just missing an explicit commit message. Thanks!

**Comment by artur-fijalkowski** [comment]
@guits So what I should put in commit message? Write in "" and I will copy&paste ;)

**Comment by guits** [comment]
@artur-fijalkowski you should explain :

- what drove you to write this patch,
- what you have changed,
- why you changed it this way ...

**Comment by artur-fijalkowski** [comment]
@guits Is it OK now? ;)

**Comment by guits** [comment]
jenkins test pipeline

**Pull request merged**
