### PR TITLE
validate: fix gpt header check

### PR DESCRIPTION
**Pull request by guits**
Check for gpt header when osd scenario is lvm or lvm batch.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1731310

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test luminous-centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test luminous-centos-non_container-lvm_osds

**Comment by dsavineau** [comment]
jenkins test luminous-centos-non_container-lvm_osds

**Comment by dsavineau** [comment]
jenkins test luminous-centos-container-lvm_osds

**Comment by dsavineau** [comment]
jenkins test luminous-centos-non_container-lvm_batch

**Comment by dsavineau** [comment]
jenkins test luminous-centos-container-lvm_batch

**Comment by dsavineau** [comment]
jenkins test luminous-centos-non_container-lvm_batch

**Comment by dsavineau** [comment]
jenkins test luminous-centos-container-lvm_batch

**Comment by dsavineau** [comment]
@guits I think we should have this fix in master/stable-4.0 too because we're still have lvm/lvm batch. wdyt ?

**Pull request merged**
