### PR TITLE
dashboard: Disable optional features

### PR DESCRIPTION
**Pull request by dp4-ms**
New config option to disable optional features in the dashboard using the `ceph dashboard feature disable` command.

Signed-off-by: David Piper <david.piper@metaswitch.com>

### CODE REVIEW

**Comment by dp4-ms** [comment]
I think this is candidate for backporting to `stable-4.0` but I don't have permission to add the appropriate label as described here: https://github.com/ceph/ceph-ansible/blob/master/CONTRIBUTING.md#backports-maintainers-only

**Comment by guits** [comment]
@dp4-ms see https://github.com/ceph/ceph-ansible/blob/master/CONTRIBUTING.md#sample-files

**Comment by dp4-ms** [comment]
@guits I followed that process before my commit, hence the changes to all.yml.sample and rhcs.yml.sample.

I did update dashboards.yml.sample manually as my new option is clearly relevant to dashboards but there seems to be no mechanism in generate_group_vars_sample.sh to produce this file. Have I missed something?

**Comment by guits** [comment]
@dp4-ms can you rebase and fix the conflict please?

thanks!

**Pull request closed without merging**
