### PR TITLE
harmonize docker names

### PR DESCRIPTION
**Pull request by ibotty**
See #1241

### CODE REVIEW

**Comment by ibotty** [comment]
I don't know why ansible2.2-docker_* fail.

**Comment by leseb** [comment]
isn't this part of https://github.com/ceph/ceph-ansible/pull/1318 already? If so please close this one.

**Comment by ibotty** [comment]
Well, it is. I thought that pull request to take longer... I am fine with closing though

**Comment by leseb** [comment]
well then remove from the other PR :)

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test ansible2.2-purge_cluster

**Comment by leseb** [comment]
jenkins test this ansible2.2-journal_collocation

**Comment by leseb** [comment]
please rebase

**Pull request merged**
