### PR TITLE
use dnf when yum is not available

### PR DESCRIPTION
**Pull request by leseb**
fixes the `importError: No module named yum` see here:
https://jenkins.ceph.com/job/ceph-ansible-pull-requests/45/console

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
weird this doesn't seem to solve the problem :/ still hitting `ImportError: No module named yum`

**Comment by leseb** [comment]
@andrewschoen isn't dnf the package manager used on this VM?

**Comment by rootfs** [comment]
@leseb or maybe it is an Atomic host?

**Comment by leseb** [comment]
@rootfs I doubt that but I'll @andrewschoen confirm or not :)

**Comment by andrewschoen** [comment]
@leseb I'm wondering if this PR just needs the code from https://github.com/ceph/ceph-ansible/pull/493 before it'll give a valid test.

This node used for this PR testing should be exactly the same as the one from this run, which passed with the code from #493 https://jenkins.ceph.com/job/ceph-ansible-pull-requests/46/consoleFull

They are both centos7 nodes created from the same image and configured by the same ansible playbook.

**Comment by leseb** [comment]
@andrewschoen well let' merge this and rebase the other patch if needed.

**Pull request merged**
