### PR TITLE
Typo fix for radosgw@ systemd file

### PR DESCRIPTION
**Pull request by andymcc**
systemd script for radosgw is radosgw@ not rgw@, the directory needs to
match the path.

(cherry picked from commit 05a1f965c8dd342e2643286d0228b5352f5afd36)

### CODE REVIEW

**Comment by andymcc** [comment]
jenkins test luminous-ansible2.3-docker_cluster_collocation

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-docker_cluster_collocation

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-docker_cluster_collocation

**Comment by leseb** [comment]
backport of https://github.com/ceph/ceph-ansible/pull/2093

**Pull request merged**
