### PR TITLE
purge-cluster: zap devices used with the lvm scenario

### PR DESCRIPTION
**Pull request by andrewschoen**
Fixes: https://github.com/ceph/ceph-ansible/issues/3156

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test dev-purge_lvm_osds

**Comment by zmc** [comment]
@andrewschoen What do we need to do to get this PR merged?

**Comment by andrewschoen** [comment]
@leseb @guits can we get this merged? The purge tests in the pipeline will fail until the next luminous release, but this does fix @zmc's issue and CI tests pass when run against ceph@master.

**Comment by andrewschoen** [comment]
This needs back ported to ``stable-3.2``. This BZ (https://bugzilla.redhat.com/show_bug.cgi?id=1650306) hit the same issue because purge was not successfully zapping devices listed in ``devices``.

**Pull request merged**
