### PR TITLE
remove agent role, no packages for it upstream yet

### PR DESCRIPTION
**Pull request by alfredodeza**
This should fix all the failures from this commit 2d21f741f53a2c05b5d1f410725cfdd8ddcaf518

### CODE REVIEW

**Comment by alfredodeza** [comment]
@leseb I am not sure how to deal with:

    mv: cannot move ‘/opt/pypy/python’ to ‘/opt/bin/python’: No such file or directory

This is for CoreOS and fully unrelated to other PRs (all PRs are currently failing because of these errors)

**Comment by leseb** [comment]
@alfredodeza my bad, thanks!
Can you remove 'ceph-common-coreos' for now as well?

**Comment by alfredodeza** [comment]
I am removing `rbd-mirror` as well. There aren't any packages yet.

**Comment by leseb** [comment]
Thanks and sorry for the pain.

**Pull request merged**
