### PR TITLE
rolling_update: remove the re-run of just the ceph-osd role

### PR DESCRIPTION
**Pull request by TamizharasiS**
Fixes: #2709

Since a rolling update is performed on an already configured cluster,
re-run of this roles is actually not required.

Signed-off-by: TamizharasiS <t.shanmugam@flipkart.com>

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by leseb** [comment]
@TamizharasiS `[skip ci]` is useless once the PR exists, this must be done during the creation of the PR.

**Comment by TamizharasiS** [comment]
Oh, sorry. I will remember that from next time, actually I missed to your message before the PR creation.

**Comment by leseb** [comment]
@TamizharasiS No worries.

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-update_cluster

**Comment by guits** [comment]
@TamizharasiS could you please rebase on master?

**Comment by TamizharasiS** [comment]
I have rebased and pushed. Could you please check now.

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-update_docker_cluster

**Comment by leseb** [comment]
@TamizharasiS please allow our CI to rebase your branch by following: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

Thanks!

**Comment by leseb** [comment]
@TamizharasiS why did you close this?

**Comment by TamizharasiS** [comment]
sorry, I could not actively work on the fix and its testing.

**Pull request closed without merging**
