### PR TITLE
Choose ceph config location

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by leseb** [comment]
@fultonj

**Comment by guits** [comment]
jenkins test kraken-ansible2.2-docker_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_docker_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-dmcrypt_journal_collocation

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_dmcrypt

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Pull request merged**
