### PR TITLE
dashboard: enable dashboard by default

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
This PR enable dashboard deployment by default

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1726739

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
@guits @dsavineau 

I've added `groups[grafana_server] | length < 1` to check if our Ceph cluster has a Grafana server for now. If there is a better/more correct way, let me know.

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test dev-centos-container-podman

**Comment by guits** [comment]
ceph-iscsi repos are broken in shaman. Therefore, this PR won't pass the CI

**Comment by alfredodeza** [comment]
This has started breaking all ceph-volume tests. What can we do to skip the dashboard for cases like ceph-volume where it doesn't need one?

**Comment by dsavineau** [comment]
`dashboard_enabled: false` in the ansible configuration

**Comment by guits** [comment]
use `dashboard_enabled: false`

**Comment by alfredodeza** [comment]
Thanks guys!

/cc @jan--f

**Comment by epuertat** [comment]
Thanks a lot, @guits, @dsavineau, @rishabh-d-dave for addressing this so quickly!

**Comment by jan--f** [comment]
Thanks indeed guys, will push a test fix shortly.

**Pull request merged**
