### PR TITLE
rgw testing stable 2.2

### PR DESCRIPTION
**Pull request by alimaredia**
This branch would add the testing for the rgw tuning, as of now, one of the RGW tests isn't passing

### CODE REVIEW

**Comment by andrewschoen** [comment]
@alimaredia is this a backport of https://github.com/ceph/ceph-ansible/pull/1484 ?

**Comment by alimaredia** [comment]
@andrewschoen yes, i won't remove the DNM label until that branch is merged.

**Comment by andrewschoen** [comment]
@alimaredia I'm confused, #1484 has already been merged. Do you mean you'll remove the DNM label after tests pass?

**Comment by alimaredia** [comment]
@andrewschoen yes, i mispoke a bit. This PR is a backport of #1484 and https://github.com/ceph/ceph-ansible/pull/1526. I won't remove the DNM label until #1526 merges and all the tests pass.

**Pull request merged**
