### PR TITLE
Remove validate action and notario dependency

### PR DESCRIPTION
**Pull request by dsavineau**
The current ceph-validate role is using both validate action and fail
module tasks to validate the ceph configuration.
The validate action is based on the notario python library. When one of
the notario validation fails then a python stack trace is reported to the
ansible task. This output isn't understandable by users.

This patch removes the validate action and the notario depencendy. The
validation is now done with only fail ansible module.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1654790

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
@guits considering that the backport in 3.2 conflicts and need to be updated due to the osd_scenario variable, should I keep https://github.com/ceph/ceph-ansible/pull/4595 for that branch or do you prefer using the backport + update method ?

**Comment by dsavineau** [comment]
jenkins test centos-non_container-collocation

**Comment by dsavineau** [comment]
jenkins test centos-non_container-collocation

**Comment by guits** [comment]
> @guits considering that the backport in 3.2 conflicts and need to be updated due to the osd_scenario variable, should I keep #4595 for that branch or do you prefer using the backport + update method ?

I think it's fine keeping #4595 

thanks maggle!

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Pull request merged**
