### PR TITLE
Simplify NTP checks/install

### PR DESCRIPTION
**Pull request by major**
This patch simplifies the checks and installation tasks for NTP.

Debian and Red Hat had a check for NTP's presence but would then
install NTP right afterwards anyways. In addition, there were
tasks for atomic that weren't used anywhere else in the role.

### CODE REVIEW

**Comment by major** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by major** [comment]
jenkins test luminous-ansible2.3-update_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-update_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by major** [comment]
Rebased the patch to get rid of the merge conflict.

**Comment by leseb** [comment]
@major are you sure you pushed your rebase?

**Comment by major** [comment]
Yes, looks like there's another conflict. ;)

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by major** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Pull request merged**
