### PR TITLE
Assign application on pools created by ceph-ansible

### PR DESCRIPTION
**Pull request by radut**
Example of config clients.yml

```
kuberbd:
  name: "kuberbd"
  pg_num: "64"
  pgp_num: "64"
  rule_name: "replicated_rack"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"


pools:
  - "{{ kuberbd }}"
```

This should also call enable application rbd on the respective pool

### CODE REVIEW

**Comment by radut** [comment]
After running ansible-playbook, you will have your application enabled on the pool.

ceph osd dump
```
pool 1 'kuberbd' replicated size 2 min_size 1 crush_rule 1 object_hash rjenkins pg_num 64 pgp_num 64 last_change 42 flags hashpspool stripe_width 0 expected_num_objects 1 application rbd
```

**Comment by dsavineau** [comment]
@radut could you update your commit message with the Signed-off-by line ?

**Comment by radut** [comment]
I've updated my commits, please check

**Comment by guits** [comment]
@radut there is no need to have 3 commits for this.
please squash them, thanks!

**Comment by radut** [comment]
updated

**Comment by radut** [comment]
@dsavineau can you check

**Comment by radut** [comment]
Hi, can you retrigger the failed subjob. From longs and previous runs(on same PR were successful) ...this fail doesn't seem related to my changes.

**Pull request merged**
