### PR TITLE
Bugfix #6102: Assumptions about consistent container runtime in a Ceph cluster running mixed OS versions

### PR DESCRIPTION
**Pull request by oneswig**
Use hostvars from the delegated host to determine container binary.

### CODE REVIEW

**Comment by dsavineau** [comment]
Could you open the PR agains the master branch and add a signoff ?

We don't allow pushing changes on stable branches directly (unless it's the only solution) so you should create the PR on master and we will create the backport to the stable branches.

**Comment by oneswig** [comment]
Thanks Dimitri!  I looked at master branch and the approach there has been refactored so applying the patch is not trivial.  The issue does appear to be still there (unless it is resolved at a different level).  Unfortunately I cannot test against master branch.

**Comment by guits** [comment]
If the issue reported here boils down to an issue because of different OS versions, I would say we have never supported deployments with a mix of different host OS versions.
That being said, from what I'm understanding here, the underlying question is about supporting to deploy with a mix of different container runtimes, regardless of the OS version.

@dsavineau why should we support this kind of deployment? I'm not 100% sure so I might be wrong but off the top of my head, this has never really been supported nor tested in the CI. (On the other hand, I'm thinking about deployments which would be collocated with nodes that already come with a container runtime installed or something like that)

A couple of questions:
- Is this patch enough to fully support this? Is it broken as well in stable-5.0 and master?
- If we decide to support this, it means we should add functional testings

**Comment by oneswig** [comment]
The situation where it arises for me is in rolling upgrades from 7 to 8.  During that process, the cluster will be partly running 7+Docker, and partly 8+Podman

**Comment by dsavineau** [comment]
> @dsavineau why should we support this kind of deployment? I'm not 100% sure so I might be wrong but off the top of my head, this has never really been supported nor tested in the CI. (On the other hand, I'm thinking about deployments which would be collocated with nodes that already come with a container runtime installed or something like that)

That's true, we never supported this kind of setup but in the same time we've never mentioned anywhere that it wasn't supported.

> * Is this patch enough to fully support this?

It's only a partial fix to me (especially for Stig's environment) because there's a lot of other part of the code where we use `delegate_to` + unscoped `container_binary/container_exec_cmd/etc variables`.

> Is it broken as well in stable-5.0 and master?

Yes. Note that it should be easier to fix this in master/stable-5.0 as we use more standalone container commands (docker/podman run) via the ansible module vs the docker/podman exec workflow in stable-4.0.

**Comment by guits** [comment]
> That's true, we never supported this kind of setup but in the same time we've never mentioned anywhere that it wasn't supported.

That doesn't mean that if we don't explicitly say something isn't supported one can state it is.
To be honest, Although I don't mind introducing patches for that I'm not sure we should start supporting this given the future of ceph-ansible, it all depends on how much effort it represents for adding this kind of support (thinking about ci testing, etc.)

**Pull request closed without merging**
