### PR TITLE
tests: disable nfs-ganesha deployment

### PR DESCRIPTION
**Pull request by guits**
nfs-ganesha repositories @ dev are broken, this commit disables the
nfs-ganesha deployment so the CI isn't stuck.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
jenkins test pipeline

**Comment by dsavineau** [comment]
weird the update scenarios are failing on nfs0...

**Comment by guits** [comment]
jenkins test dev-centos-non_container-update

**Comment by guits** [comment]
jenkins test dev-centos-container-update

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test dev-centos-container-update

**Comment by guits** [comment]
jenkins test dev-centos-non_container-update

**Comment by guits** [comment]
jenkins test dev-centos-container-update

**Comment by guits** [comment]
jenkins test dev-centos-non_container-update

**Comment by guits** [comment]
jenkins test dev-centos-container-collocation

**Pull request merged**
