### PR TITLE
library: flake8 ceph-ansible modules

### PR DESCRIPTION
**Pull request by hswong3i**
This commit ensure all ceph-ansible modules pass flake8 properly.

Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Comment by guits** [comment]
this pr should be rebased on master now, it includes a commit that was already merged in #6614

**Comment by hswong3i** [comment]
> this pr should be rebased on master now, it includes a commit that was already merged in #6614

rebase and force-pushed

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test  centos-container-collocation

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Review by guits — APPROVED** [review]

**Pull request merged**
