### PR TITLE
Backport of 2246

### PR DESCRIPTION
**Pull request by leseb**
Backport of #2246

### CODE REVIEW

**Comment by fultonj** [comment]
jenkins test luminous-ansible2.4-xenial_cluster

**Comment by fultonj** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_non_container

**Comment by leseb** [comment]
That's a feature and we need to discuss if this can be backported.

**Comment by leseb** [comment]
This won't make it in 3.0 as a backport but 3.1 milestone just as planned.

**Pull request closed without merging**
