### PR TITLE
allow adding a manager to a deployed cluster

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Add a playbook that deploys manager on a new node and adds that node to
the already deployed Ceph cluster.
    
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1677431
Signed-off-by: Rishabh Dave <ridave@redhat.com>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
This PR covers both containerized and non-containerized deployment. Locally it ran successfully; I have attached the logs to this comment.
[dev-centos-container-add_mgrs-SUCCEEDED.log](https://github.com/ceph/ceph-ansible/files/3138132/dev-centos-container-add_mgrs-SUCCEEDED.log)
[dev-centos-non_container-add_mgrs-SUCCEEDED.log](https://github.com/ceph/ceph-ansible/files/3138133/dev-centos-non_container-add_mgrs-SUCCEEDED.log)

**Comment by rishabh-d-dave** [comment]
@guits @dsavineau I've named the new node as mgr0. But should it be named as mgr1 considering that one MGR is already deployed at mon0?

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-add_mgrs

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-add_mgrs

**Comment by dsavineau** [comment]
> @guits @dsavineau I've named the new node as mgr0. But should it be named as mgr1 considering that one MGR is already deployed at mon0?

I don't think this need to be mgr1. Even if there's already a mgr node collocated on mon0, the first mgr node (dedicated) should be named mgr0

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by rishabh-d-dave** [comment]
jenkins test pipeline

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-update

**Comment by guits** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test dev-centos-container-add_mgrs

**Comment by guits** [comment]
jenkins test dev-centos-non_container-add_mgrs

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-add_mgrs

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-add_mgrs

**Pull request merged**
