### PR TITLE
common: install ceph-volume package

### PR DESCRIPTION
**Pull request by guits**
After pacific release, ceph-volume has its own package.
ceph-ansible has to explicitly install it on osd nodes.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_containers-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_containers-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by tchaikov** [comment]
@guits thank you!

**Pull request merged**
