### PR TITLE
pass the list of packages to package management modules

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Instead of looping over a list of packages or repeating the task
separately for different packages, pass the list of packages to the
task performing package management.

Signed-off-by: Rishabh Dave <ridave@redhat.com>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
Similar to PR #3295 for the rest of the codebase.

**Comment by leseb** [comment]
@rishabh-d-dave is the DNM still valid?

**Comment by rishabh-d-dave** [comment]
Sorry, slipped out of my mind; I was working on some other task.

**Comment by leseb** [comment]
jenkins test purge_cluster_container

**Comment by leseb** [comment]
jenkins test dev-purge_cluster_container

**Comment by leseb** [comment]
jenkins test dev-purge_cluster_non_container

**Pull request merged**
