### PR TITLE
tests: bump the version of ansible to 2.2.2

### PR DESCRIPTION
**Pull request by alfredodeza**
Signed-off-by: Alfredo Deza <adeza@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
We now have a disconnect between this and the Jenkins Job until pr #1410 gets merged

**Comment by leseb** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
@leseb seems we are good now

**Comment by leseb** [comment]
Yup, thanks!

**Pull request merged**
