### PR TITLE
ceph-mon: use --admin-daemon to set default crush rule

### PR DESCRIPTION
**Pull request by mihaiplasoianu**
A default crush rule is inserted into the daemon via the ceph daemon config
command. This command tries to resolve the admin socket path and fails if you
have a duplicate key in the ceph configuration.

This PR uses the `--admin-daemon` option to prevent the task from failling.

This is related to #4492 (which has been fixed with #4507)

Signed-off-by: Mihai Plasoianu <m.plasoianu@vertical.de>

### CODE REVIEW

**Comment by mihaiplasoianu** [comment]
@guits Is it possible that you merged into the wrong branch?

**Comment by dsavineau** [comment]
jenkins test centos-container-ooo_collocation

**Comment by dsavineau** [comment]
jenkins test centos-container-update

**Comment by dsavineau** [comment]
jenkins test centos-non_container-collocation

**Comment by dsavineau** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by dsavineau** [comment]
jenkins test centos-container-update

**Pull request merged**
