### PR TITLE
ceph-pool: add support updating crush rule of the pool

### PR DESCRIPTION
**Pull request by clwluvw**
Support updating crush rule of the pool via crush rule name.

### CODE REVIEW

**Comment by clwluvw** [comment]
jenkins retest this please

**Comment by clwluvw** [comment]
jenkins retest this please

**Comment by clwluvw** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
I think this is missing a unit test

**Review by guits — APPROVED** [review]

**Pull request merged**
