### PR TITLE
tox: use container latest tag for upgrades

### PR DESCRIPTION
**Pull request by leseb**
Currently tag-build-master-luminous-ubuntu-16.04 is not used anymore.
Also now, 'latest' points to CentOS so we need to make that switch here
too.

We know have latest tags for each stable release so let's use them and
point tox at them to deploy the right version.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
Needs: https://github.com/ceph/ceph-container/pull/985

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-docker_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-docker_cluster_collocation

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-ooo_collocation

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_container

**Comment by guits** [comment]
unrelated failure (race condition in ceph-disk) for luminous-ansible2.4-purge_bluestore_osds_container, merging anyway

**Pull request merged**
