### PR TITLE
Improve devices validation

### PR DESCRIPTION
**Pull request by dsavineau**
- check if the device exists and isn't using a gpt partition table for `lvm_volumes` data devices.
- check if the device exists before testing the partition table.
- don't resolve the devices since this is already done in ceph-facts role.
- refact the root_device detection.
- validate the `dedicated_devices` and `bluestore_wal_devices` too for lvm batch scenario.
- validate logical volumes used in `lvm_volumes`.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1906022

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_osds

**Review by guits — DISMISSED** [review]

**Review by guits — APPROVED** [review]

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Pull request merged**
