### PR TITLE
Sync config_template with upstream for Ansible 2.6

### PR DESCRIPTION
**Pull request by andymcc**
The original_basename option in the copy module changed to be
_original_basename in Ansible 2.6+, this PR resyncs the config_template
module to allow this to work with both Ansible 2.6+ and before.

Additionally, this PR removes the _v1_config_template.py file, since
ceph-ansible no longer supports versions of Ansible before version 2,
and so we shouldn't continue to carry that code.

Closes: #2843
Signed-off-by: Andy McCrae <andy.mccrae@gmail.com>

### CODE REVIEW

**Comment by andymcc** [comment]
One point of note - this will fix the config_template module to work with Ansible 2.6, but there may be other issues with Ansible 2.6 that are unrelated to config_template and aren't dealt with by this PR.

**Comment by M0les** [comment]
So I notice there's a clone of `plugins/actions/_v[12]_config_template.py` inside `roles/ceph-common` and more notably, this did not get your Ansbile 2.6 fixes.

I'm still pretty low-down on the Ansible+Ceph-Ansible+Ceph learning curve, but I'm wondering if the fix should be:

1. Copy the patches into the clones (easy, but possibly kicking some technical debt down the road)
1. Work-out how to remove the `roles/ceph-common` copies of these files.

**Comment by guits** [comment]
@M0les ceph-common used to be the role where the configuration were generated before we create the ceph-config role, my assumption is that from ansible galaxy point of view, it was needed to provide the plugin in ceph-common. So it's probably a legacy and I see 2 options:

1/ it should be totally removed because it's legacy,
2/ or it should probably be moved to ceph-config role + synced with this patch

@leseb could you clarify?

**Comment by andymcc** [comment]
We should be able to remove those - the module path points to plugins/actions for action_plugins, so unless you are running with an ansible.cfg that points to the one in ceph-common it shouldn't use that plugin - additionally the ceph-common role doesn't have any config_template tasks (which lines up with what you said above @guits)
In my opinion we should just remove them because they aren't being used and are just creating confusion. (I've put a PR up to do that #2932)

**Comment by guits** [comment]
@andymcc I'd like to get @leseb confirmation regarding ansible galaxy use case before merging #2932

**Comment by andymcc** [comment]
@guits yeah definitely.

**Pull request merged**
