### PR TITLE
ansible: use ansible.utils.ipwrap instead of ansible.netcommon.ipwrap

### PR DESCRIPTION
**Pull request by clwluvw**
ansible.netcommon.ipwrap is deprecated and is not being redirected with ansible 2.9.*

Signed-off-by: Seena Fallah <seenafallah@gmail.com>

### CODE REVIEW

**Comment by clwluvw** [comment]
@guits I got a problem with using `ansible.netcommon.ipwrap` with ansible 2.9.* even if I installed `ansible.netcommon` galaxy
It is solved when changing to `ansible.utils.ipwrap`

**Comment by guits** [comment]
@clwluvw how do you install ansible? is it ansible 3 ? or ansible-base 2.10 ?

**Comment by clwluvw** [comment]
> @clwluvw how do you install ansible? is it ansible 3 ? or ansible-base 2.10 ?

@guits Tested with ansible 2.9.27

**Comment by clwluvw** [comment]
Also btw it's deprecated and in `main` branch we are using `ansible.utils.ipwrap`
Seems it makes sense to use `ansible.utils.ipwrap` instead of `ansible.common.ipwrap` anyways 🤔

**Comment by guits** [comment]
> Also btw it's deprecated and in the `main` branch we are using `ansible.utils.ipwrap` Seems it makes sense to use `ansible.utils.ipwrap` instead of `ansible.netcommon.ipwrap` anyways 🤔

in fact, it's a bit more complicated. It depends on how you get your Ansible engine.

**Comment by guits** [comment]
> > @clwluvw how do you install ansible? is it ansible 3 ? or ansible-base 2.10 ?
> 
> @guits Tested with ansible 2.9.27

what version of `ansible.netcommon` did you install?

**Comment by clwluvw** [comment]
> > > @clwluvw how do you install ansible? is it ansible 3 ? or ansible-base 2.10 ?
> > 
> > 
> > @guits Tested with ansible 2.9.27
> 
> what version of `ansible.netcommon` did you install?

3.0.1

**Comment by clwluvw** [comment]
> > Also btw it's deprecated and in the `main` branch we are using `ansible.utils.ipwrap` Seems it makes sense to use `ansible.utils.ipwrap` instead of `ansible.netcommon.ipwrap` anyways 🤔
> 
> in fact, it's a bit more complicated. It depends on how you get your Ansible engine.

pip3 install ansible==2.9.27 🤔 
@guits But can you give me more hints about your fact? because I use pipenv for installing ansible so maybe other deps are in higher version or...

**Comment by guits** [comment]
how can you run `stable-6.0` with ansible 2.9 given https://github.com/ceph/ceph-ansible/blob/stable-6.0/roles/ceph-validate/tasks/check_system.yml#L7-L10 ?

**Comment by clwluvw** [comment]
> how can you run `stable-6.0` with ansible 2.9 given https://github.com/ceph/ceph-ansible/blob/stable-6.0/roles/ceph-validate/tasks/check_system.yml#L7-L10 ?

@guits Good point! =)))
Actually I was only testing your last commit here (https://github.com/ceph/ceph-ansible/commit/c9dd9a09d21a25ee67b0dd002461f1197d6f67d0) with a simple ansible ad-hoc

So seems I need to update my ansible as well :))
And I won't face this issue anymore

So it would be optional here to change to ansible.utils maybe just because of deprecation and being sync with the main branch

**Comment by guits** [comment]
> So it would be optional here to change to ansible.utils maybe just because of deprecation and being sync with the main branch

It might make sense if we change the requirement from `ansible>=3,<4` to  `ansible>=2.10,<2.11,!=2.9.10`

**Comment by clwluvw** [comment]
> It might make sense if we change the requirement from ansible>=3,<4 to ansible>=2.10,<2.11,!=2.9.10

But seems ansible 3 is based on ansible-base 2.10 (https://docs.ansible.com/ansible/latest/roadmap/COLLECTIONS_3_0.html) so this condition should work

**Comment by guits** [comment]
> > It might make sense if we change the requirement from ansible>=3,<4 to ansible>=2.10,<2.11,!=2.9.10
> 
> But seems ansible 3 is based on ansible-base 2.10 (https://docs.ansible.com/ansible/latest/roadmap/COLLECTIONS_3_0.html) so this condition should work

ansible-base 2.10 alone doesn't include the collection `ansible.utils`, hence the need of `requirements.yml`
ansible-3.x comes with ansible-base 2.10 + collections. But the `ansible.utils` collection version shipped doesn't include the filter `ipwrap`, it's still present in `ansible.netcommon`. Hence the patch I've sent yesterday.

**Comment by clwluvw** [comment]
> > > It might make sense if we change the requirement from ansible>=3,<4 to ansible>=2.10,<2.11,!=2.9.10
> > 
> > 
> > But seems ansible 3 is based on ansible-base 2.10 (https://docs.ansible.com/ansible/latest/roadmap/COLLECTIONS_3_0.html) so this condition should work
> 
> ansible-base 2.10 alone doesn't include the collection `ansible.utils`, hence the need of `requirements.yml` ansible-3.x comes with ansible-base 2.10 + collections. But the `ansible.utils` collection version (2.1.0) shipped with ansible-3.x doesn't include the filter `ipwrap`, it's still present in `ansible.netcommon`. Hence the patch I've sent yesterday.

Now I get what did you mean about how I installed the ansible 👍 😃

**Comment by guits** [comment]
yeh these recent changes from Ansible are quite confusing and prone to error 😅

**Comment by mitch000001** [comment]
> how can you run `stable-6.0` with ansible 2.9 given https://github.com/ceph/ceph-ansible/blob/stable-6.0/roles/ceph-validate/tasks/check_system.yml#L7-L10 ?

Actually, the documentation at https://docs.ceph.com/projects/ceph-ansible/en/latest/index.html#releases tells that the version to be used should be ansible 2.9. So this should definitely be corrected.

**Comment by guits** [comment]
> > how can you run `stable-6.0` with ansible 2.9 given https://github.com/ceph/ceph-ansible/blob/stable-6.0/roles/ceph-validate/tasks/check_system.yml#L7-L10 ?
> 
> Actually, the documentation at https://docs.ceph.com/projects/ceph-ansible/en/latest/index.html#releases tells that the version to be used should be ansible 2.9. So this should definitely be corrected.

yup, correct. Thanks for noticing this. The documentation  has been updated

**Comment by guits** [comment]
it looks like we can't support both `ansible 3.x` and `ansible-base 2.10`, we have to pick one.
I feel we should go with `ansible-base 2.10` to get closer to newer ansible releases, on the other hand, it might be a breaking change for users with `ansible 3.x`

any thoughts?

**Comment by clwluvw** [comment]
> it looks like we can't support both `ansible 3.x` and `ansible-base 2.10`, we have to pick one. I feel we should go with `ansible-base 2.10` to get closer to newer ansible releases, on the other hand, it might be a breaking change for users with `ansible 3.x`
> 
> any thoughts?

I'm thinking like you too. but the users with ansible 3.x won't face any breaking changes because ansible 3.x is based on 2.10, so the new users only need to take care of the collections that are missing with ansible-base (we might need to list them in requirements.yml)

**Comment by guits** [comment]
@clwluvw remember what I said:

> > But the `ansible.utils` collection version (2.1.0) shipped with ansible-3.x doesn't include the filter `ipwrap`, it's still present in `ansible.netcommon`.

**Comment by clwluvw** [comment]
@guits So we might need to include the minimum version (2.5.0) to the requirements.yml as well 🤔 (and users should take care of the changelogs btw 😃)

**Review by guits — APPROVED** [review]

**Pull request merged**
