### PR TITLE
common: set apt pinning with Red Hat Ceph Storage

### PR DESCRIPTION
**Pull request by leseb**
When `ceph_stable_rh_storage` is True, every cluster node should have a
`/etc/apt/preferences.d/rhcs.pref` file with the following contents:

```
Explanation: Prefer Red Hat packages
Package: *
Pin: release o=/Red Hat/
Pin-Priority: 999
```

ceph-deploy already did this when used with ice-setup, and we need to do
the same thing with the ceph-ansible stack.

Closes: #1182

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
@ktdreyer

**Comment by ktdreyer** [comment]
There are some changes to `name:` in here, that would make this change harder to cherry-pick, if we had to do a cherry-pick. Want to break those out into a separate commit?

**Comment by leseb** [comment]
@ktdreyer yes that'd be better :)

**Comment by leseb** [comment]
@ktdreyer done!

**Comment by andrewschoen** [comment]
jenkins test ansible2.2-docker_cluster

**Pull request merged**
