### PR TITLE
infra playbook: move untested scenario to a new dir

### PR DESCRIPTION
**Pull request by leseb**
Move untested/with few confidence playbooks in a untested-by-ci
directory.
Also removing this directory from the package build.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1461551
Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
What is the impact on https://bugzilla.redhat.com/1366807 ?

**Comment by leseb** [comment]
@ktdreyer I was actually about to say that this needs to wait for https://github.com/ceph/ceph-ansible/pull/1836 and then be rebased.

**Comment by ktdreyer** [comment]
This change will `rm` the shrink playbooks in the RPM. How will https://bugzilla.redhat.com/1366807 work after this PR goes in?

**Comment by leseb** [comment]
once https://github.com/ceph/ceph-ansible/pull/1836 gets merged I'll update this PR and move shrink* back to infrastructure-playbooks/.

**Pull request merged**
