### PR TITLE
Backport: mon/osd: bump container memory limit in stable-3.0

### PR DESCRIPTION
**Pull request by leseb**
Backport of #2775 in stable-3.0

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1591876

### CODE REVIEW

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-filestore_osds_container

**Comment by guits** [comment]
jenkins test pipeline

**Comment by guits** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
CI error is unrelated.

**Pull request merged**
