### PR TITLE
DNM - Testing tripleo - ceph integration

### PR DESCRIPTION
**Pull request by arxcruz**

### CODE REVIEW

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by arxcruz** [comment]
check-rdo

**Comment by javierpena** [comment]
check-rdo

**Pull request closed without merging**
