### PR TITLE
validate: check custom repository config options

### PR DESCRIPTION
**Pull request by zugwan**
This adds missing configuration options and corrects a typo error when
the 'custom' repository is used.

Signed-off-by: Jugwan Eom <zugwan@gmail.com>

### CODE REVIEW

**Comment by zugwan** [comment]
The failure of the test pipeline was not caused by this PR.

**Comment by guits** [comment]
@zugwan I know it's been a while, sorry for the delay.
Do you mind resolving the conflict here?

**Comment by zugwan** [comment]
@guits I updated branch to fix conflict.

**Comment by rishabh-d-dave** [comment]
@zugwan @guits Hi. This PR slipped out of my mind since I don't normally receive review requests. Sorry about the delay.

The modifications looks OK to me. And to verify that I applied and tested the patch locally which also went fine.

**Comment by rishabh-d-dave** [comment]
jenkins test ceph-ansible-prs-dev-centos-non_container-all_daemons

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-lvm_osds

**Comment by rishabh-d-dave** [comment]
@guits The jobs that failed in pipeline have passed. They had originally failed because package mirror was, apparently, unreachable for a while.

**Pull request merged**
