### PR TITLE
Backport of 2620 in stable-3.1

### PR DESCRIPTION
**Pull request by leseb**
Backport of #2620 in stable-3.1

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1581573

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by guits** [comment]
@leseb @ltoscano-rh is it fixing a bug? (are the backports really needed?)

**Comment by guits** [comment]
forget about my last comment. I've seen @leseb created a BZ for this. thanks.

**Comment by ltoscano-rh** [comment]
Thanks for starting the backport process and the bug! (I was on vacation for few days)

**Pull request merged**
