### PR TITLE
ceph-mon: docker fix run on atomic host

### PR DESCRIPTION
**Pull request by leseb**
fix template issues.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
test this please

**Comment by johnwilkins** [comment]
We're testing and trying to get 2.0 running from the puddles. Do you have
any tips?

On Thu, Mar 31, 2016 at 3:36 PM, Leseb <notifications@github.com> wrote:

> Merged #669 <https://github.com/ceph/ceph-ansible/pull/669>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph-ansible/pull/669#event-610531503>
>



-- 
John Wilkins
Red Hat
jowilkin@redhat.com
(415) 425-9599
http://redhat.com

**Comment by leseb** [comment]
I'm sorry from the puddles? 
There is a permission issue that I need to fix and 2.0 should run perfectly. Just trying to find an elegant way to fix it for all the Ceph versions. Will likely fix this tomorrow.

**Comment by dang** [comment]
Yeah, I was just chowning in the entrypoint scripts.

**Comment by leseb** [comment]
@johnwilkins it works now on 2.0 thanks to: https://github.com/ceph/ceph-ansible/pull/673 and https://github.com/ceph/ceph-ansible/pull/669

**Pull request merged**
