### PR TITLE
rolling_update: pg check refactor

### PR DESCRIPTION
**Pull request by guits**
There's no need to achieve this in two tasks.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-non_container-shrink_osds

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by dsavineau** [comment]
jenkins test centos-non_container-all_in_one

**Comment by dsavineau** [comment]
jenkins test centos-non_container-collocation

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-external_clients

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_batch

**Comment by dsavineau** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-non_container-all_in_one

**Pull request merged**
