### PR TITLE
Create fetch directory if it doesn't exist.

### PR DESCRIPTION
**Pull request by lyandrew**
Possible fix for issue #333

### CODE REVIEW

**Comment by leseb** [comment]
Possible fix or real fix? :)

**Comment by leseb** [comment]
Sorry could you please rebase and confirm that this fix works?
If it's positive I'll merge.

**Comment by lyandrew** [comment]
sure

**Comment by lyandrew** [comment]
`local_action: file path=fetch state=directory`

Rebased and can confirm that the commit fixes the issue.

**Comment by leseb** [comment]
Thanks!

**Pull request merged**
