### PR TITLE
fix add mirroring peer

### PR DESCRIPTION
**Pull request by Ameenasuhani**
Fixes add a mirroring peer through ansible.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1665877

### CODE REVIEW

**Comment by dsavineau** [comment]
Normally the `ceph_rbd_mirror_remote_user` should include this `client.` prefix but maybe the documentation is confusing [1]

[1] https://github.com/ceph/ceph-ansible/blob/master/group_vars/rbdmirrors.yml.sample#L41

**Comment by Ameenasuhani** [comment]
Referring this doc https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html/block_device_guide/block_device_mirroring ```Adding a Cluster Peer```  the above changes were successful in adding a peer.

**Comment by dsavineau** [comment]
> Referring this doc https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html/block_device_guide/block_device_mirroring `Adding a Cluster Peer` the above changes were successful in adding a peer.

The documentation says :

`rbd --cluster <cluster-name> mirror pool peer add <pool-name> <peer-client-name>@<peer-cluster-name> -n <client-name>`

So `<peer-client-name>` is the full client name including the `client.` prefix but not `client.<peer-client-name>`

**Comment by guits** [comment]
@dsavineau @Ameenasuhani what's the status on this one?

**Comment by dsavineau** [comment]
@guits from my point of view there's no issue there

**Comment by guits** [comment]
ok, according to the documentation and what @dsavineau says here, let's close this.
@Ameenasuhani feel free to reopen if you do think it's needed.

**Pull request closed without merging**
