### PR TITLE
drop rgw multisite deployment support

### PR DESCRIPTION
**Pull request by guits**
The current approach is extremely complex and introduced a lot of spaghetti code. This doesn't offer a good user experience at all.

It's time to think to another approach (dedicated playbook) and drop the current implementation in order to clean up the code.

### CODE REVIEW

**Review by clwluvw — APPROVED** [review]
:rocket:

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-collocation

**Comment by jmundack** [comment]
@guits / @clwluvw - i fully understand the need to refactor and clean up code.

But had a question on this change - did we just remove support for rgw-multisite without having an alternate /cleaner version available?

**Pull request merged**
