### PR TITLE
tests: add back nfs testing on master

### PR DESCRIPTION
**Pull request by guits**
This commit adds back nfs testing on master branch

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
still seeing selinux issues ...

**Comment by dsavineau** [comment]
@guits Could we at least enable it back for containerized deployment ?

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-ooo_collocation

**Comment by dsavineau** [comment]
jenkins test centos-non_container-all_daemons

**Pull request merged**
