### PR TITLE
purge-cluster: remove usage of `with_fileglob`

### PR DESCRIPTION
**Pull request by guits**
`with_fileglob` loops over files on the machine where ansible-playbook
is being run. Here, we want to iterate over files on the remote machine

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_non_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_non_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_non_container

**Comment by guits** [comment]
The error here is not related to the PR, merging it anyway

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_bluestore_osds_non_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_cluster

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_cluster_non_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_cluster_non_container

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-purge_cluster_non_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_cluster_non_container

**Comment by guits** [comment]
jenkins test luminous-ansible2.4-purge_cluster_non_container

**Pull request merged**
