### PR TITLE
Drop ceph-iscsi-gw role and all references

### PR DESCRIPTION
**Pull request by fghaas**
Following the suggestion from @leseb in #1031.

I suggest that this patch be reverted once @pcuzner gets around to merging his work from https://github.com/pcuzner/ceph-iscsi-ansible into this repo.

### CODE REVIEW

**Comment by fghaas** [comment]
I have no idea what `FATAL: java.io.IOException: Unexpected termination of the channel` is supposed to mean in the Jenkins log, but it doesn't seem like that would be an error that is related to a code change.

**Comment by guits** [comment]
jenkins test kraken-ansible2.2-purge_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-dmcrypt_journal

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_docker_cluster

**Comment by leseb** [comment]
These files can stay around. The issue was fixed with https://github.com/ceph/ceph-ansible/pull/1586.
I should have closed  #1031, my bad. I suggest we close this, if you have any objection @fghaas , please let me know.

I hope the sync will happen somewhere this summer.

**Comment by fghaas** [comment]
@leseb, maybe you'd also like to take a look at the other 86 open issues and see which of those are still current?

**Pull request closed without merging**
