### PR TITLE
Update README-MULTISITE.md

### PR DESCRIPTION
**Pull request by quangln94**
Don't create zone group for: "Deployment Scenario #1"

### CODE REVIEW

**Comment by guits** [comment]
I'm sorry but what is the issue exactly?
Could you elaborate a bit more?

**Comment by quangln94** [comment]
When deploying using "Deployment Scenario #1: Single Realm & Zonegroup with Multiple Ceph Clusters"
If you set the parameter "rgw_zonegroupmaster: true" on "Secondary Zone", an error will appear because in "Secondary Zone" will pull the configuration from "Cluster 1" instead of creating "zonegroup" on "Cluster 2" because on "Cluster 2" does not create realm and do not create zonegroup.
Should use "rgw_zonegroupmaster: false" on "Cluster 2"

**Comment by guits** [comment]
> When deploying using "Deployment Scenario #1: Single Realm & Zonegroup with Multiple Ceph Clusters" If you set the parameter "rgw_zonegroupmaster: true" on "Secondary Zone", an error will appear because in "Secondary Zone" will pull the configuration from "Cluster 1" instead of creating "zonegroup" on "Cluster 2" because on "Cluster 2" does not create realm and do not create zonegroup. Should use "rgw_zonegroupmaster: false" on "Cluster 2" to don't create zonegroup when deploy on "Cluster 2"

@alimaredia any thoughts?

**Comment by alimaredia** [comment]
@quangln94 It should not matter whether or not `zonegroupmaster` is set to true or false for a secondary clusters there are no zonegroups being created when a secondary zone is being created.

All secondary zone related tasks are in this file.

https://github.com/ceph/ceph-ansible/blob/main/roles/ceph-rgw/tasks/multisite/secondary.yml#L46

Do you have log output for where the playbooks are doing a realm pull and then a zonegroup is being created?

**Comment by quangln94** [comment]
image

This is error when i set "rgw_zonegroupmaster: true" on "Secondary Zone".

**Comment by alimaredia** [comment]
@quangln94 I now see that `zonegroups` is defined whenever zonegroup_master is defined. https://github.com/ceph/ceph-ansible/blob/main/roles/ceph-rgw/tasks/multisite/main.yml#L14

This should not be the case when secondary zones are being deployed. 

Could you also add to the note on line `205` here https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L205 and the values below to `false`:

https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L396

https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L417

https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L520

**Comment by quangln94** [comment]
Hi @alimaredia 
So I will close this PR and then create new PR will edit the lines bellow right ?:
- https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L396
- https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L417
- https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L520
- Add note at line 205 here https://github.com/ceph/ceph-ansible/blob/main/README-MULTISITE.md?plain=1#L205

**Comment by alimaredia** [comment]
@quangln94 No need to close this PR, you can just add another commit to your branch with those changes so that those changes are in this PR. If you'd rather open up another PR that's fine too.

Also you are correct those lines for additional changes. If you see any other places where `rgw_zonesecondary: True`, `rgw_zonemaster: False` we want `rgw_zonegroupmaster` to be `False`

**Comment by quangln94** [comment]
Hi @alimaredia,
I created new PR here: https://github.com/ceph/ceph-ansible/pull/7323

**Comment by quangln94** [comment]
This PR was merge in PR: https://github.com/ceph/ceph-ansible/pull/7327

**Pull request closed without merging**
