### PR TITLE
Switch to epel-8 mock config for make rpm

### PR DESCRIPTION
**Pull request by bshewale**
Since the Makefile is updated to build rpm on el8 but
mock config was pointing to epel-7. It needs to be fixed
to use epel-8 config.

### CODE REVIEW

**Comment by bshewale** [comment]
@gfidente

**Comment by ktdreyer** [comment]
This will alter the stable-4.0 builds without an easy way to go back to el7.

Instead of hard-coding this further, would you please copy the entire Makefile from `master` to `stable-4.0`? That will include the `$(DIST)` and `$(MOCK_CONFIG)` variables. That is far easier to maintain if we need to ever run `make rpm` for el7 again.

**Comment by ktdreyer** [comment]
Thanks. With this change, I confirmed that `make rpm` builds an RPM for CentOS 8, and `make rpm DIST=el7 MOCK_CONFIG=epel-7-x86_64` builds an RPM for CentOS 7.

**Comment by ktdreyer** [comment]
This change now cherry-picks the whole `Makefile` from master.

**Comment by guits** [comment]
> This change now cherry-picks the whole `Makefile` from master.

I don't think it's a proper cherry-pick here

**Comment by guits** [comment]
Closing this in favor of #5194

**Pull request closed without merging**
