### PR TITLE
ceph-common: fix ceph install for centos distros

### PR DESCRIPTION
**Pull request by leseb**
closes: #616

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
@dpkshetty can you give it a try?

**Comment by dpkshetty** [comment]
```
TASK: [ceph.ceph-common | install ceph] *************************************** 
ok: [10.0.0.9]

TASK: [ceph.ceph-common | install distro or red hat storage ceph mon] ********* 
fatal: [10.0.0.9] => error while evaluating conditional: (ceph_origin == "distro" or ceph_stable_rh_storage) and mon_group_name in group_names and ansible_pkg_mgr == "yum" and not is_ceph_infernalis

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/centos/site.retry

10.0.0.9                   : ok=21   changed=0    unreachable=1    failed=0   
```
@leseb  ^^ This is what I am hitting now with your fix

**Comment by egonzalez90** [comment]
I'm getting the same error as @dpkshetty

**Comment by leseb** [comment]
argh yes the fact doesn't exist yet...

**Comment by leseb** [comment]
@dpkshetty @egonzalez90 can you try again?

**Comment by dpkshetty** [comment]
@leseb It works now, but I have few questions ...

1) It install 0.80.x version from CentOS base repo. I was expecting that when i set ceph_origin to distro, it will install latest non-infernalis, which happens to be Hammer (0.94.x), which is GA'ed for quite some time now. Debugging further I see thats not happening because ceph-ansible doesn't install centos-ceph-hammer repo. What do you think about this ?

2) For some reason i see the ceph cluster status as HEALTH_WARN, it may not be related to this issue, but just wanted to put this observation here.

```
Installed Packages
Name        : ceph-common
Arch        : x86_64
Epoch       : 1
Version     : 0.80.7
Release     : 3.el7
Size        : 18 M
Repo        : installed
From repo   : base                          <=== base repo
Summary     : Ceph Common
URL         : http://ceph.com/
License     : GPLv2
Description : Common utilities to mount and interact with a ceph storage cluster.

[centos@ceph-node1 ~]$ sudo ceph -s
    cluster ef6789d7-1b41-4e42-9ddf-6c2fb43c7537
     health HEALTH_WARN 192 pgs degraded; 192 pgs stuck unclean
     monmap e1: 1 mons at {ceph-node1=192.168.122.66:6789/0}, election epoch 2, quorum 0 ceph-node1
     osdmap e8: 2 osds: 2 up, 2 in
      pgmap v13: 192 pgs, 3 pools, 0 bytes data, 0 objects
            68468 kB used, 81811 MB / 81877 MB avail
                 192 active+degraded

[centos@ceph-node1 ~]$ ls /etc/yum.repos.d/
CentOS-Base.repo  CentOS-CR.repo  CentOS-Debuginfo.repo  CentOS-fasttrack.repo  CentOS-Media.repo  CentOS-Sources.repo  CentOS-Vault.repo  epel.repo  epel-testing.repo

[centos@ceph-node1 ~]$ rpm -qa| grep ceph
python-cephfs-0.80.7-0.7.el7.x86_64
ceph-common-0.80.7-3.el7.x86_64
libcephfs1-0.80.7-0.7.el7.x86_64
ceph-0.80.7-0.7.el7.x86_64

```

**Comment by dpkshetty** [comment]
@leseb I manually installed centos-release-ceph-hammer-1.0-5.el7.centos.noarch on my ceph-node1, and then ran ceph-ansible and it now install Hammer - FYI

Maybe we should add this repo if user selected 'distro' as part of the playbook ?

```
[centos@ceph-node1 ~]$ rpm -qa| grep ceph
ceph-common-0.94.5-1.el7.x86_64
centos-release-ceph-hammer-1.0-5.el7.centos.noarch
python-cephfs-0.94.5-1.el7.x86_64
ceph-0.94.5-1.el7.x86_64
libcephfs1-0.94.5-1.el7.x86_64

[centos@ceph-node1 ~]$ sudo ceph -s
    cluster ef6789d7-1b41-4e42-9ddf-6c2fb43c7537
     health HEALTH_WARN
            64 pgs degraded
            64 pgs stuck degraded
            64 pgs stuck unclean
            64 pgs stuck undersized
            64 pgs undersized
     monmap e1: 1 mons at {ceph-node1=192.168.122.66:6789/0}
            election epoch 2, quorum 0 ceph-node1
     osdmap e8: 2 osds: 2 up, 2 in
      pgmap v13: 64 pgs, 1 pools, 0 bytes data, 0 objects
            67416 kB used, 81812 MB / 81877 MB avail
                  64 active+undersized+degraded
```

**Comment by dpkshetty** [comment]
```
[centos@ceph-node1 ~]$ ls /etc/yum.repos.d/
CentOS-Base.repo  **CentOS-Ceph-Hammer.repo**  CentOS-CR.repo  CentOS-Debuginfo.repo  CentOS-fasttrack.repo  CentOS-Media.repo  CentOS-Sources.repo  CentOS-Vault.repo  epel.repo  epel-testing.repo

```

**Comment by leseb** [comment]
If you set 'distro' it will just install Ceph from the repositories available on your workstation. If you need another repo please open another issue :).  Ill look into it

**Pull request merged**
