### PR TITLE
shrink_osd: remove volumes with c-v zap by fsid

### PR DESCRIPTION
**Pull request by noahdesu**

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test pipeline

**Comment by noahdesu** [comment]
seems like a normal missing dependency

```
[nwatkins@smash ceph-ansible]$ virtualenv env
[nwatkins@smash ceph-ansible]$ env/bin/pip install -r tests/requirements.txt 
[nwatkins@smash ceph-ansible]$ env/bin/python -c "import mock"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mock'
```

**Comment by leseb** [comment]
jenkins test dev-shrink_osd_container

**Comment by leseb** [comment]
jenkins test dev-shrink_osd

**Comment by leseb** [comment]
@noahdesu thanks this might have to wait for https://github.com/ceph/ceph-ansible/pull/3486 to pass so master will be working again.

**Comment by noahdesu** [comment]
jenkins test dev-shrink_osd_container

**Comment by noahdesu** [comment]
jenkins test dev-shrink_osd

**Comment by noahdesu** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
jenkins test dev-shrink_osd_container

**Comment by leseb** [comment]
jenkins test dev-shrink_osd

**Pull request merged**
