### PR TITLE
Common: Do not install ceph-mgr packages on jewel

### PR DESCRIPTION
**Pull request by guits**
ceph-mgr tasks have to be skipped on jewel.

Fix: #1494

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-journal_collocation

**Comment by guits** [comment]
jenkins test kraken-ansible2.2-docker_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-purge_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-xenial_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-purge_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-xenial_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-xenial_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by guits** [comment]
jenkins test kraken-ansible2.2-xenial_cluster

**Comment by andrewschoen** [comment]
@guits hmm, I was not expecting ``jewel-ansible2.2-docker_dedicated_journal`` to pass here but I guess I'll take it. I suspect we're dealing with an environmental issue of some sort.

**Pull request merged**
