### PR TITLE
infrastructure playbooks: remove lv-create error msg

### PR DESCRIPTION
**Pull request by alimaredia**
remove error message when PV creation fails

Signed-off-by: Ali Maredia <amaredia@redhat.com>

### CODE REVIEW

**Comment by alimaredia** [comment]
@leseb this does the same thing as https://github.com/ceph/ceph-ansible/pull/3075. https://github.com/ceph/ceph-ansible/pull/3072 was merged without testing and does not work. I'm not sure how you'd like to revert the code but I wanted to have this PR as an option as well.

**Comment by leseb** [comment]
@alimaredia the PR was merged because the CI passed AND had an approval if you don't want the bot to merge the PR apply the label DNM next time.

**Comment by alimaredia** [comment]
@leseb I thought I did that here: https://github.com/ceph/ceph-ansible/pull/3072 but I guess the brackets got in the way?

**Comment by leseb** [comment]
@alimaredia you didn't apply the label in #3072, you only set `[DNM]` in the title of the PR which does not do anything :). Next time set the label, thanks.

**Comment by alimaredia** [comment]
Thanks for the information! I'll set it next time.

**Pull request merged**
