### PR TITLE
validate: accept lowercase true and false as boolean values

### PR DESCRIPTION
**Pull request by andrewschoen**
This resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1638325

### CODE REVIEW

**Comment by andrewschoen** [comment]
@VasishtaShastry Would you mind adding a Signed-off-by to your commits?

**Comment by VasishtaShastry** [comment]
@andrewschoen I've squashed commits and added Signed-off-by

**Comment by leseb** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
@andrewschoen next time please use the `backport-stable-3.2` label. Thanks.

**Comment by andrewschoen** [comment]
jenkins test pipeline

**Comment by leseb** [comment]
We have no functional coverage this actually works. `osd_auto_discovery` is not working on ceph-volume and we stopped running ceph-disk based tests. At least this hasn't broken anything.

**Pull request merged**
