### PR TITLE
tests: run all tests for jewel and kraken

### PR DESCRIPTION
**Pull request by andrewschoen**
Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
Needs https://github.com/ceph/ceph-build/pull/672 to run the new tests

**Comment by andrewschoen** [comment]
jenkins test this please

**Comment by leseb** [comment]
Yeah! Thanks @andrewschoen

**Comment by andrewschoen** [comment]
jenkins test this please

**Comment by alfredodeza** [comment]
"37 pending checks"

💃

**Pull request merged**
