### PR TITLE
test adding a RBD mirror to already deployed cluster

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Add a tox scenario that adds a new RBD mirror node as a part of already
deployed Ceph cluster and deploys RBD mirror there.

Signed-off-by: Rishabh Dave <ridave@redhat.com>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
Testing this PR locally went fine for me; attaching the logs -

[dev-centos-non_container-add_rbdmirrors-SUCCEEDED.log](https://github.com/ceph/ceph-ansible/files/3053355/dev-centos-non_container-add_rbdmirrors-SUCCEEDED.log)
[dev-centos-container-add_rbdmirrors-SUCCEEDED.log](https://github.com/ceph/ceph-ansible/files/3053356/dev-centos-container-add_rbdmirrors-SUCCEEDED.log)

**Comment by rishabh-d-dave** [comment]
@guits 
Should I go ahead and add "Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1677431" to the commit message? [BZ #1677431](https://bugzilla.redhat.com/show_bug.cgi?id=1677431) requests scale-up/down playbooks for MGR, RGW and RBD-Mirror which is too broad for a single PR.

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-add_rbdmirrors

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-add_rbdmirrors

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-add_rbdmirrors

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-add_rbdmirrors

**Comment by guits** [comment]
jenkins test dev-centos-non_container-add_rbdmirrors

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-add_rbdmirrors

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-add_rbdmirrors

**Comment by rishabh-d-dave** [comment]
jenkins test pipeline

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by rishabh-d-dave** [comment]
ceph-ansible-prs-dev-centos-container-all_daemons

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-non_container-all_daemons

**Comment by rishabh-d-dave** [comment]
jenkins test dev-centos-container-all_daemons

**Comment by rishabh-d-dave** [comment]
jenkins test dev-ubuntu-non_container-all_daemons

**Pull request merged**
