### PR TITLE
backport of 2177

### PR DESCRIPTION
**Pull request by leseb**
backport of #2177

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by leseb** [comment]
Needs to be discussed as this is a feature backport.

**Comment by tombarron** [comment]
Just observing that we need this for OSP 13.  Is there anything I can add to the discussion w.r.t. the need to backport this feature?  For OSP13 we need to support failover for nfs-ganesha to a backup controller node.  To achieve this we need to persist the nfs-ganesha's exports to shared storage (we're using RADOS) rather than keeping it on local disk as was done up to this point.

**Comment by leseb** [comment]
jenkins test luminous-ansible2.4-centos7_cluster

**Comment by leseb** [comment]
This won't make it in 3.0 as a backport but 3.1 milestone just as planned.

**Pull request closed without merging**
