### PR TITLE
library/ceph_key.py: rewrite for generate_ceph_cmd()

### PR DESCRIPTION
**Pull request by hswong3i**
Also code lint with flake8

Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

### CODE REVIEW

**Comment by guits** [comment]
tests need to be updated accordingly

**Comment by hswong3i** [comment]
> tests need to be updated accordingly

@guits thank you very much, test updated and looks good now ;-)

**Comment by guits** [comment]
jenkins test centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Review by guits — APPROVED** [review]

**Pull request merged**
