### PR TITLE
backport: Docker registry bkp

### PR DESCRIPTION
**Pull request by guits**
backport of #1516

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-docker_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-docker_dedicated_journal

**Comment by andrewschoen** [comment]
jenkins test kraken-ansible2.2-centos7_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-docker_dmcrypt_journal_collocation

**Comment by andrewschoen** [comment]
The CI is being difficult here, for reasons not related to this PR, but I think it's safe to merge.

**Comment by leseb** [comment]
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1447179

**Pull request merged**
