### PR TITLE
send fs commands to one mon

### PR DESCRIPTION
**Pull request by batrick**
Add-on to #1329.

Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

### CODE REVIEW

**Comment by batrick** [comment]
Thanks @guits for writing up #1329.

**Comment by leseb** [comment]
jenkins test ansible2.2-journal_collocation

**Comment by leseb** [comment]
jenkins test ansible2.2-xenial_cluster

**Comment by leseb** [comment]
jenkins test ansible2.2-purge_cluster

**Comment by leseb** [comment]
+1 @guits comment, let's put that condition on the include.

**Comment by batrick** [comment]
Done!

**Comment by leseb** [comment]
jenkins test ansible2.2-xenial_cluster

**Comment by leseb** [comment]
jenkins test ansible2.2-xenial_cluster

**Pull request merged**
