### PR TITLE
tests: Retry generating SSH vagrant config.  Also add some debug.

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
jenkins test centos-container-all_daemons

**Comment by djgalloway** [comment]
jenkins test centos-non_container-all_daemons

**Comment by djgalloway** [comment]
jenkins test centos-non_container-all_in_one

**Comment by djgalloway** [comment]
jenkins test centos-non_container-purge

**Comment by djgalloway** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by djgalloway** [comment]
jenkins test centos-non_container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-all_in_one

**Pull request merged**
