### PR TITLE
testing: add luminous factor for testing

### PR DESCRIPTION
**Pull request by alfredodeza**
Signed-off-by: Alfredo Deza <adeza@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by guits** [comment]
jenkins test please

**Comment by guits** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test jewel-ansible2.2-docker_cluster

**Comment by leseb** [comment]
jenkins test kraken-ansible2.2-centos7_cluster

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Comment by leseb** [comment]
jenkins test this please

**Pull request closed without merging**
