### PR TITLE
Use a tempfile to store restart scripts

### PR DESCRIPTION
**Pull request by mcv21**
Make a tempfile directory and copy the restart scripts there (and then
execute them from there), rather than using insecure known filenames
in /tmp/

This is a partial fix for ceph/ceph-ansible#2937

This is a backport of the equivalent fix to master (ceph/ceph-ansible#3081) for stable-3.0

Signed-off-by: Matthew Vernon <mv3@sanger.ac.uk>

### CODE REVIEW

**Comment by leseb** [comment]
We never push directly into stable branches if the initial patch is not in master yet. Typically, you push a patch in master, add the label backport-stable-3.0, once the PR is merged on master a backport will be created automatically.

**Comment by mcv21** [comment]
OK, but the master patch needed a bit of tweaking to apply to stable-3.0...

**Comment by leseb** [comment]
I see, I guess I read too quickly, re-opening, sorry about that.

**Comment by mcv21** [comment]
retest this please

**Pull request closed without merging**
