### PR TITLE
Container fixups

### PR DESCRIPTION
**Pull request by erikh**
These are some of the errors I found running against my own setup with the roles/plugins, which I ported back into the repository. I hope you find them satisfactory.

Thanks again for the awesome work, we're still using the majority of this in volplugin and it's very useful.

### CODE REVIEW

**Comment by erikh** [comment]
Note that this also resolves some issues I had working with the suggestions in https://github.com/ceph/ceph-docker/issues/330.

**Comment by erikh** [comment]
Looks like these jenkins failures are related to jenkins itself, or am I misreading the output?

**Comment by leseb** [comment]
@erikh yes no worries, moreover we are not testing the containerized scenario yet. :)

**Comment by erikh** [comment]
@leseb there ya go!

**Comment by leseb** [comment]
@erikh looks like #878 is addressing this issue too, but is a bit more complete than your patch.
Are you fine, closing this in favour of #878?

**Comment by erikh** [comment]
Sure! The important thing is that it's resolved.

**Comment by leseb** [comment]
@erikh looks like you didn't get my update, actually we can keep this https://github.com/erikh/ceph-ansible/blob/f0c97bf9aa035d53ffc13d6f1c3d8dcfd9652de9/roles/ceph-osd/tasks/docker/start_docker_osd.yml#L46

Mind reworking the PR for this?

**Comment by erikh** [comment]
done; let me know if there's an issue still.

**Comment by erikh** [comment]
BTW sorry to get off-topic but are you on OFTC? I want to assist a little more with this project and would like to talk to you in realtime about it. :)

Thanks.

**Comment by leseb** [comment]
@erikh yes I'm on ceph-ansible :)

**Pull request merged**
