### PR TITLE
Sensitive key data now hidden in output log

### PR DESCRIPTION
**Pull request by Neelaksh-Singh**
Set **no_log: true** for all the updated files , so that sensitive information are not logged out in the ansible output, thereby increasing security and privacy.

Fixes: #6529

Signed-off-by: Neelaksh Singh <neelaksh48@gmail.com>

### CODE REVIEW

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-container-purge

**Comment by guits** [comment]
jenkins test centos-container-collocation

**Comment by guits** [comment]
jenkins test centos-non_container-collocation

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by mogindi** [comment]
Is this ready to be merged?

**Comment by Neelaksh-Singh** [comment]
I guess it requires 1 approving review from a reviewer.

**Review by guits — APPROVED** [review]

**Pull request merged**
