### PR TITLE
tests: use github workflow for ansible-lint

### PR DESCRIPTION
**Pull request by guits**
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
@guits do we have something missing in that PR ?

I would like to get rid of travisci so once https://github.com/ceph/ceph-ansible/pull/5970 will be merge then only this PR will remain.

I guess we can for now run ansible-lint the exact same way than currently (ie: without infrastructure-playbooks directory and site playbooks) and do some follow up later.

WDYT ?

**Comment by guits** [comment]
jenkins test centos-all_daemons-non_container

**Comment by guits** [comment]
jenkins test centos-all_daemons-container

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Comment by guits** [comment]
jenkins test centos-non_container-collocation

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-non_container-purge

**Comment by dsavineau** [comment]
Looks like the `set -o pipefail` added in the purge-cluster.yml playbook causes the task to fail in some case

**Comment by guits** [comment]
> Looks like the `set -o pipefail` added in the purge-cluster.yml playbook causes the task to fail in some case

yes maggle

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Review by dsavineau — APPROVED** [review]

**Pull request merged**
