### PR TITLE
[skip ci] Add support for iscsi configuration in container

### PR DESCRIPTION
**Pull request by leseb**
You can now use ceph-ansible to configure iscsi gateway when running on
a containerized cluster.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by leseb** [comment]
jenkins test dev-docker_cluster

**Comment by hoerup** [comment]
Setting up iscsi should be done via dashboard or gwcli. Please look at #3977 where the old target configuration is being deprecated

**Pull request closed without merging**
