### PR TITLE
tests: adds a test for rolling updates of containerized clusters

### PR DESCRIPTION
**Pull request by andrewschoen**
I have yet to get this test to pass so I'm not going to enable it in the CI quite yet.

The failure I see is that the first updated MON does not start and join the quorum after being updated.

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test kraken-ansible2.2-xenial_cluster

**Comment by andrewschoen** [comment]
jenkins test kraken-ansible2.2-xenial_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-purge_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-docker_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-xenial_cluster

**Comment by andrewschoen** [comment]
jenkins test kraken-ansible2.2-docker_dmcrypt_journal_collocation

**Comment by andrewschoen** [comment]
My last commits should have fixed rolling update of containerized clusters, the PR to add the CI tests is here https://github.com/ceph/ceph-build/pull/740

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-update_cluster

**Comment by andrewschoen** [comment]
jenkins test kraken-ansible2.2-docker_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_docker_cluster

**Comment by guits** [comment]
jenkins test kraken-ansible2.2-update_docker_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-xenial_cluster

**Comment by leseb** [comment]
@andrewschoen please rebase, thanks!

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_docker_cluster

**Comment by guits** [comment]
jenkins test jewel-ansible2.2-update_docker_cluster

**Comment by andrewschoen** [comment]
jenkins test ewel-ansible2.2-centos7_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-purge_cluster

**Comment by andrewschoen** [comment]
jenkins test jewel-ansible2.2-centos7_cluster

**Pull request merged**
