### PR TITLE
Correcting validation type check on rc

### PR DESCRIPTION
**Pull request by ianwatsonrh**
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1826884

rc is a number not a string. removing '' from the 0.

### CODE REVIEW

**Comment by dsavineau** [comment]
Please amend you commit and add a signoff

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-external_clients

**Comment by guits** [comment]
jenkins test centos-non_container-switch_to_containers

**Comment by guits** [comment]
jenkins test centos-non_container-all_in_one

**Comment by guits** [comment]
jenkins test centos-non_container-all_in_one

**Comment by guits** [comment]
jenkins test centos-container-ooo_collocation

**Comment by guits** [comment]
jenkins test centos-container-purge

**Comment by guits** [comment]
@ianwatsonrh may I ask you to you add the `Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1826884` in your commit message? Thanks!

**Comment by guits** [comment]
@ianwatsonrh thanks!

**Pull request merged**
