### PR TITLE
client: ability to create keys and pool with no ceph binaries

### PR DESCRIPTION
**Pull request by leseb**
On a container env, machines don't have any ceph binaries so we need to
use a container to run the commands.

Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-docker_dedicated_journal

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-purge_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-shrink_osd

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-update_docker_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-centos7_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-shrink_mon

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-bluestore_journal_collocation

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-docker_dedicated_journal

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-switch_to_containers

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-update_cluster

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-purge_cluster

**Comment by guits** [comment]
jenkins test this please

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-dmcrypt_journal_collocation

**Comment by guits** [comment]
jenkins test luminous-ansible2.3-update_dmcrypt

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-shrink_mon

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-shrink_osd

**Comment by leseb** [comment]
jenkins test luminous-ansible2.3-bluestore_journal_collocation

**Comment by leseb** [comment]
jenkins test  luminous-ansible2.3-purge_docker_cluster

**Comment by leseb** [comment]
Feature was validated by both `luminous-ansible2.3-docker_cluster` and `luminous-ansible2.3-centos7_cluster`. That's enough test.

**Pull request merged**
