### PR TITLE
osd: support creating ec profiles

### PR DESCRIPTION
**Pull request by guits**
this adds ec profiles creation support in ceph-ansible

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
removing the backport label as the `ceph_ec_profile` module doesn't exist in stable-5.0 branch

**Comment by guits** [comment]
> removing the backport label as the `ceph_ec_profile` module doesn't exist in stable-5.0 branch

it will be backported

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-container-all_daemons

**Comment by guits** [comment]
jenkins test centos-non_container-collocation

**Review by dsavineau — COMMENTED** [review]
Should we have a validation of the keys (at least name, k and v) from ec_profiles in ceph-validate ?

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-lvm_osds

**Comment by guits** [comment]
jenkins test centos-non_container-all_in_one

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-all_daemons

**Comment by guits** [comment]
jenkins test centos-container-update

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Comment by guits** [comment]
jenkins test centos-non_container-update

**Pull request closed without merging**
