### PR TITLE
generate_group_vars_sample: rhcs.yml.sample

### PR DESCRIPTION
**Pull request by leseb**
Add a pre-configured bare minimum rhcs.yml.sample that can save
configuration steps.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1478071
Signed-off-by: Sébastien Han <seb@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
The "generate group vars" thing is getting more complicated, but sure.

Good call on needs-docs.

**Comment by ktdreyer** [comment]
I must be missing the point of the "needs-docs" label

**Comment by leseb** [comment]
@ktdreyer the idea is once we branch stable-2.3 and start doing QE we will review all the PR labelled like this and discuss with the doc team accordingly.

**Comment by ktdreyer** [comment]
@leseb why not write the docs as part of the PR?

**Comment by leseb** [comment]
We have some portion of it in the commits, that's why we will revisit it with the doc team.

**Comment by ktdreyer** [comment]
I should clarify - why not update https://github.com/ceph/ceph-ansible/tree/master/docs in each PR?

**Comment by leseb** [comment]
Because I forgot and time is often limited... But yes I agree, this is not optimal.

**Pull request merged**
