### PR TITLE
Ipv6 rgw doc

### PR DESCRIPTION
**Pull request by leseb**

### CODE REVIEW

**Comment by ktdreyer** [comment]
mind waiting a bit before merging? I am not sure what the `docker-common` change has to do with this?

**Comment by leseb** [comment]
@ktdreyer it's a separate commit so it's not a problem right?

**Comment by ktdreyer** [comment]
I like "one PR per logical change, one logical change per PR"

**Comment by leseb** [comment]
Alright, will keep that in mind :)

**Pull request merged**
