### PR TITLE
openSUSE OBS repository using ceph_stable_release

### PR DESCRIPTION
**Pull request by johanneskastl**
Instead of hardcoding `luminous`, use the `ceph_stable_release` variable to point to the correct repository.

Uncomment this in `roles/ceph-defaults/defaults/main.yml` to be avaible, as it is only used if `ceph_repository` is set to `obs`.

Could not be tested due to #4361.

### CODE REVIEW

**Comment by johanneskastl** [comment]
> please, squash your commits

- [X] Done.

**Comment by guits** [comment]
> Uncomment this in `roles/ceph-defaults/defaults/main.yml` to be avaible, as it is only used if `ceph_repository` is set to `obs`.

this file isn't intended to be modified.

if you wanna override this, you must do it either in inventory, group_vars, ... but definitely not in `ceph-defaults/defaults/main.yml`

could you please amend your commit message?

thanks!

**Comment by johanneskastl** [comment]
Sorry for the confusion. I meant: I have uncommented this in `ceph-defaults/defaults/main.yml` so this variable is available. This variable is only used on SUSE/openSUSE and only in case one sets ceph_repository to `obs`, so I figure there is no harm in having that variable set.

**Comment by johanneskastl** [comment]
> do not edit sample files directly, use `./generate_group_vars_sample.sh`
> see https://github.com/ceph/ceph-ansible/blob/master/CONTRIBUTING.md#sample-files

I ran that script which made another modification to `group_vars/rhcs.yml.sample`.

I fixed a typo in my commit message and added, that I have recreated the sample files using the script.

**Pull request merged**
